# Generated by Django 5.2.7 on 2025-10-26 12:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        ("flock_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedSupplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Supplier/company name", max_length=200, unique=True
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, help_text="Contact person name", max_length=100
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Primary phone number", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email address", max_length=254
                    ),
                ),
                ("address", models.TextField(help_text="Physical address")),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Business registration number",
                        max_length=50,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Tax identification number (TIN)",
                        max_length=50,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash on Delivery"),
                            ("NET7", "Net 7 Days"),
                            ("NET14", "Net 14 Days"),
                            ("NET30", "Net 30 Days"),
                            ("CREDIT", "Credit Account"),
                        ],
                        default="CASH",
                        help_text="Default payment terms",
                        max_length=10,
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum credit limit (GHS)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_purchases",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total value of purchases (GHS)",
                        max_digits=12,
                    ),
                ),
                (
                    "last_purchase_date",
                    models.DateField(
                        blank=True, help_text="Date of most recent purchase", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether supplier is currently active"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about supplier"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Feed Supplier",
                "verbose_name_plural": "Feed Suppliers",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="feed_invent_name_ea47ed_idx"),
                    models.Index(
                        fields=["is_active"], name="feed_invent_is_acti_758c4e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the feed type (e.g., 'Layer Mash 16%')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STARTER", "Starter Feed (0-8 weeks)"),
                            ("GROWER", "Grower Feed (9-18 weeks)"),
                            ("LAYER", "Layer Feed (19+ weeks)"),
                            ("BROILER_STARTER", "Broiler Starter (0-3 weeks)"),
                            ("BROILER_FINISHER", "Broiler Finisher (4+ weeks)"),
                            ("BREEDER", "Breeder Feed"),
                            ("SUPPLEMENT", "Supplement/Premix"),
                            ("MEDICATION", "Medicated Feed"),
                        ],
                        help_text="Feed category based on bird age/type",
                        max_length=20,
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("MASH", "Mash"),
                            ("PELLET", "Pellet"),
                            ("CRUMBLE", "Crumble"),
                            ("GRAIN", "Whole Grain"),
                        ],
                        default="MASH",
                        help_text="Physical form of the feed",
                        max_length=10,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, help_text="Feed manufacturer/brand", max_length=100
                    ),
                ),
                (
                    "protein_content",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Crude protein percentage (0-50%)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("50.00")),
                        ],
                    ),
                ),
                (
                    "energy_content",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Metabolizable Energy (ME) in kcal/kg",
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "calcium_content",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calcium percentage (0-10%)",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("10.00")),
                        ],
                    ),
                ),
                (
                    "phosphorus_content",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Phosphorus percentage (0-5%)",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("5.00")),
                        ],
                    ),
                ),
                (
                    "recommended_age_weeks_min",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Minimum bird age in weeks for this feed",
                        null=True,
                    ),
                ),
                (
                    "recommended_age_weeks_max",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Maximum bird age in weeks for this feed",
                        null=True,
                    ),
                ),
                (
                    "daily_consumption_per_bird_grams",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Average daily consumption per bird in grams",
                        null=True,
                    ),
                ),
                (
                    "standard_price_per_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Standard/reference price per kg (GHS)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this feed type is currently available",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional description or notes about this feed type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Feed Type",
                "verbose_name_plural": "Feed Types",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="feed_invent_categor_1fa8dd_idx",
                    ),
                    models.Index(fields=["name"], name="feed_invent_name_7ac5aa_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("purchase_date", models.DateField(help_text="Date of purchase")),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, help_text="Supplier invoice number", max_length=50
                    ),
                ),
                (
                    "quantity_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity purchased in kilograms",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per kilogram (GHS)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost (quantity × unit_price)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Payment Pending"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Fully Paid"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="PENDING",
                        help_text="Current payment status",
                        max_length=10,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount already paid (GHS)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "payment_due_date",
                    models.DateField(
                        blank=True, help_text="Payment due date", null=True
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, help_text="Actual delivery date", null=True
                    ),
                ),
                (
                    "received_by",
                    models.CharField(
                        blank=True,
                        help_text="Person who received the delivery",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this purchase"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feed_purchases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="Farm making the purchase",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_purchases",
                        to="farms.farm",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Supplier of the feed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="feed_inventory.feedsupplier",
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        help_text="Type of feed purchased",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="feed_inventory.feedtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Purchase",
                "verbose_name_plural": "Feed Purchases",
                "ordering": ["-purchase_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["farm", "purchase_date"],
                        name="feed_invent_farm_id_d5c818_idx",
                    ),
                    models.Index(
                        fields=["supplier", "purchase_date"],
                        name="feed_invent_supplie_e0542b_idx",
                    ),
                    models.Index(
                        fields=["payment_status"], name="feed_invent_payment_14cc9f_idx"
                    ),
                    models.Index(
                        fields=["-purchase_date"], name="feed_invent_purchas_95eb2b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_stock_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current stock level in kilograms",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "min_stock_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="Minimum stock level (reorder point) in kg",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "max_stock_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        help_text="Maximum stock level (storage capacity) in kg",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "average_cost_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Weighted average cost per kg (GHS)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total stock value (current_stock_kg × average_cost_per_kg)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "last_purchase_date",
                    models.DateField(
                        blank=True, help_text="Date of last purchase", null=True
                    ),
                ),
                (
                    "last_consumption_date",
                    models.DateField(
                        blank=True, help_text="Date of last consumption", null=True
                    ),
                ),
                (
                    "low_stock_alert",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-set when stock falls below minimum level",
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        help_text="Physical storage location on farm",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="Farm storing the feed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_inventory",
                        to="farms.farm",
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        help_text="Type of feed in stock",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_records",
                        to="feed_inventory.feedtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Inventory",
                "verbose_name_plural": "Feed Inventories",
                "ordering": ["farm", "feed_type"],
                "indexes": [
                    models.Index(
                        fields=["farm", "feed_type"],
                        name="feed_invent_farm_id_46fd3e_idx",
                    ),
                    models.Index(
                        fields=["low_stock_alert"],
                        name="feed_invent_low_sto_9be137_idx",
                    ),
                ],
                "unique_together": {("farm", "feed_type")},
            },
        ),
        migrations.CreateModel(
            name="FeedConsumption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date of consumption (denormalized from daily_production)"
                    ),
                ),
                (
                    "quantity_consumed_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity consumed in kilograms",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "cost_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per kg at time of consumption (from inventory)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost (quantity × cost_per_kg)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "birds_count_at_consumption",
                    models.PositiveIntegerField(
                        help_text="Number of birds in flock at time of consumption"
                    ),
                ),
                (
                    "consumption_per_bird_grams",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Feed consumed per bird in grams (auto-calculated)",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_production",
                    models.ForeignKey(
                        help_text="Link to daily production record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_consumption_records",
                        to="flock_management.dailyproduction",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="Farm where feed was consumed (denormalized for query performance)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_consumption_records",
                        to="farms.farm",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        help_text="Flock that consumed the feed (denormalized for query performance)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_consumption_records",
                        to="flock_management.flock",
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        help_text="Type of feed consumed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumption_records",
                        to="feed_inventory.feedtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Consumption",
                "verbose_name_plural": "Feed Consumption Records",
                "ordering": ["-date", "feed_type"],
                "indexes": [
                    models.Index(
                        fields=["daily_production", "feed_type"],
                        name="feed_invent_daily_p_cc6507_idx",
                    ),
                    models.Index(
                        fields=["farm", "date"], name="feed_invent_farm_id_71f63d_idx"
                    ),
                    models.Index(
                        fields=["flock", "date"], name="feed_invent_flock_i_1813b1_idx"
                    ),
                    models.Index(fields=["-date"], name="feed_invent_date_0cffee_idx"),
                ],
            },
        ),
    ]
