# Generated by Django 5.2.7 on 2025-11-27 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        ("feed_inventory", "0001_initial"),
        ("flock_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedconsumption",
            name="daily_production",
            field=models.ForeignKey(
                help_text="Link to daily production record",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_consumption_records",
                to="flock_management.dailyproduction",
            ),
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="farm",
            field=models.ForeignKey(
                help_text="Farm where feed was consumed (denormalized for query performance)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feed_consumption_records",
                to="farms.farm",
            ),
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="flock",
            field=models.ForeignKey(
                help_text="Flock that consumed the feed (denormalized for query performance)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feed_consumption_records",
                to="flock_management.flock",
            ),
        ),
        migrations.AddField(
            model_name="feedinventory",
            name="farm",
            field=models.ForeignKey(
                help_text="Farm storing the feed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_inventory",
                to="farms.farm",
            ),
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feed_purchases_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="farm",
            field=models.ForeignKey(
                help_text="Farm making the purchase",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feed_purchases",
                to="farms.farm",
            ),
        ),
        migrations.AddIndex(
            model_name="feedsupplier",
            index=models.Index(fields=["name"], name="feed_invent_name_ea47ed_idx"),
        ),
        migrations.AddIndex(
            model_name="feedsupplier",
            index=models.Index(
                fields=["is_active"], name="feed_invent_is_acti_758c4e_idx"
            ),
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="supplier",
            field=models.ForeignKey(
                help_text="Supplier of the feed",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="feed_inventory.feedsupplier",
            ),
        ),
        migrations.AddIndex(
            model_name="feedtype",
            index=models.Index(
                fields=["category", "is_active"], name="feed_invent_categor_1fa8dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedtype",
            index=models.Index(fields=["name"], name="feed_invent_name_7ac5aa_idx"),
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="feed_type",
            field=models.ForeignKey(
                help_text="Type of feed purchased",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="feed_inventory.feedtype",
            ),
        ),
        migrations.AddField(
            model_name="feedinventory",
            name="feed_type",
            field=models.ForeignKey(
                help_text="Type of feed in stock",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_records",
                to="feed_inventory.feedtype",
            ),
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="feed_type",
            field=models.ForeignKey(
                help_text="Type of feed consumed",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumption_records",
                to="feed_inventory.feedtype",
            ),
        ),
        migrations.AddIndex(
            model_name="feedpurchase",
            index=models.Index(
                fields=["farm", "purchase_date"], name="feed_invent_farm_id_d5c818_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedpurchase",
            index=models.Index(
                fields=["supplier", "purchase_date"],
                name="feed_invent_supplie_e0542b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedpurchase",
            index=models.Index(
                fields=["payment_status"], name="feed_invent_payment_14cc9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedpurchase",
            index=models.Index(
                fields=["-purchase_date"], name="feed_invent_purchas_95eb2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedinventory",
            index=models.Index(
                fields=["farm", "feed_type"], name="feed_invent_farm_id_46fd3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedinventory",
            index=models.Index(
                fields=["low_stock_alert"], name="feed_invent_low_sto_9be137_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedinventory",
            unique_together={("farm", "feed_type")},
        ),
        migrations.AddIndex(
            model_name="feedconsumption",
            index=models.Index(
                fields=["daily_production", "feed_type"],
                name="feed_invent_daily_p_cc6507_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedconsumption",
            index=models.Index(
                fields=["farm", "date"], name="feed_invent_farm_id_71f63d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedconsumption",
            index=models.Index(
                fields=["flock", "date"], name="feed_invent_flock_i_1813b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedconsumption",
            index=models.Index(fields=["-date"], name="feed_invent_date_0cffee_idx"),
        ),
    ]
