# Generated by Django 5.1.3 on 2025-12-09 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0013_convert_housing_to_accommodation"),
        ("feed_inventory", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feedpurchase",
            name="feed_invent_supplie_e0542b_idx",
        ),
        migrations.RemoveField(
            model_name="feedpurchase",
            name="supplier",
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="supplier_name",
            field=models.CharField(
                blank=True, help_text="Name of the supplier", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="feedpurchase",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                help_text="Supplier invoice number or batch number",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="feedpurchase",
            index=models.Index(
                fields=["supplier_name", "purchase_date"],
                name="feed_invent_supplie_c80776_idx",
            ),
        ),
    ]
