# Generated by Django 5.2.7 on 2025-12-09 15:30

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0013_convert_housing_to_accommodation"),
        (
            "feed_inventory",
            "0003_remove_feedpurchase_feed_invent_supplie_e0542b_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeedSupplier",
        ),
        migrations.RemoveIndex(
            model_name="feedpurchase",
            name="feed_invent_supplie_c80776_idx",
        ),
        migrations.RemoveField(
            model_name="feedpurchase",
            name="supplier_name",
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="bag_weight_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Weight per bag in kilograms",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="brand",
            field=models.CharField(
                blank=True, help_text="Brand of the feed", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="payment_method",
            field=models.CharField(
                blank=True,
                help_text="Payment method (Cash, Mobile Money, Bank Transfer, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="quantity_bags",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of bags purchased"
            ),
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="receipt_number",
            field=models.CharField(
                blank=True, help_text="Receipt number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="supplier",
            field=models.CharField(
                blank=True, help_text="Name of the supplier", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="supplier_contact",
            field=models.CharField(
                blank=True, help_text="Supplier contact information", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="unit_cost_ghs",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cost per bag (GHS)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="feedpurchase",
            name="delivery_date",
            field=models.DateField(
                blank=True, help_text="Expected or actual delivery date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="feedpurchase",
            name="quantity_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Total quantity purchased in kilograms (auto-calculated from bags × weight)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="feedpurchase",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total cost (quantity × unit_price)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="feedpurchase",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Price per kilogram (GHS) - auto-calculated",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddIndex(
            model_name="feedpurchase",
            index=models.Index(
                fields=["supplier", "purchase_date"],
                name="feed_invent_supplie_30c444_idx",
            ),
        ),
    ]
