# Generated by Django 5.2.7 on 2025-12-09 16:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0013_convert_housing_to_accommodation"),
        ("feed_inventory", "0004_delete_feedsupplier_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedconsumption",
            name="feed_stock",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific feed stock/batch being consumed",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumption_records",
                to="feed_inventory.feedpurchase",
            ),
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="batch_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="System-generated unique batch ID (FSTK-YYYYMMDD-####)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="feedpurchase",
            name="stock_balance_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Remaining stock balance in kilograms (updated on consumption)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="feedconsumption",
            name="feed_type",
            field=models.ForeignKey(
                help_text="Type of feed consumed (denormalized from feed_stock)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumption_records",
                to="feed_inventory.feedtype",
            ),
        ),
        migrations.AddIndex(
            model_name="feedpurchase",
            index=models.Index(
                fields=["batch_number"], name="feed_invent_batch_n_765b30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedpurchase",
            index=models.Index(
                fields=["stock_balance_kg"], name="feed_invent_stock_b_20a0a0_idx"
            ),
        ),
    ]
