# Generated by Django 5.2.7 on 2025-12-09 17:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "feed_inventory",
            "0005_feedconsumption_feed_stock_feedpurchase_batch_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedconsumption",
            name="consumption_per_bird_grams",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Feed consumed per bird in grams (auto-calculated)",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="feedconsumption",
            name="cost_per_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cost per kg at time of consumption (from inventory)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="feedconsumption",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total cost (quantity × cost_per_kg)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
