# Generated by Django 5.2.7 on 2025-12-09 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "feed_inventory",
            "0006_alter_feedconsumption_consumption_per_bird_grams_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedconsumption",
            name="feed_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of feed consumed (denormalized from feed_stock)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumption_records",
                to="feed_inventory.feedtype",
            ),
        ),
    ]
