# Generated by Django 5.2.7 on 2025-12-09 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feed_inventory", "0007_alter_feedconsumption_feed_type"),
    ]

    operations = []
