# Generated by Django 5.1.3 on 2026-01-06 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Alphalogique Technologies",
                        help_text="Company name",
                        max_length=255,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Company tagline or slogan",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(help_text="Company description")),
                ("email", models.EmailField(help_text="Company email", max_length=254)),
                ("phone", models.CharField(help_text="Company phone", max_length=50)),
                ("website", models.URLField(blank=True, help_text="Company website")),
                (
                    "address_line1",
                    models.CharField(help_text="Address line 1", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, help_text="Address line 2", max_length=255
                    ),
                ),
                ("city", models.CharField(help_text="City", max_length=100)),
                ("region", models.CharField(help_text="Region/State", max_length=100)),
                (
                    "country",
                    models.CharField(
                        default="Ghana", help_text="Country", max_length=100
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, help_text="Postal code", max_length=20
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True, help_text="Company logo URL")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="Last updated by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profile",
                "db_table": "cms_company_profile",
            },
        ),
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("about_us", "About Us"),
                            ("privacy_policy", "Privacy Policy"),
                            ("terms_of_service", "Terms of Service"),
                            ("faq", "Frequently Asked Questions"),
                            ("contact_info", "Contact Information"),
                            ("custom", "Custom Page"),
                        ],
                        db_index=True,
                        help_text="Type of content page",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Page title (e.g., 'About YEA Poultry Management System')",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (e.g., 'about-us')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full page content (supports Markdown/HTML)"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, help_text="Short summary or excerpt (optional)"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta description (160 characters max)",
                        max_length=160,
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="SEO keywords (comma-separated)",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Publication status",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, help_text="Publication date/time", null=True
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, help_text="Content version number"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Deletion timestamp", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Page",
                "verbose_name_plural": "Content Pages",
                "db_table": "cms_content_page",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentPageRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField(help_text="Version number")),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("excerpt", models.TextField(blank=True)),
                (
                    "change_summary",
                    models.TextField(
                        blank=True,
                        help_text="Description of changes made in this revision",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        help_text="User who made this change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Content page this revision belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="cms.contentpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Page Revision",
                "verbose_name_plural": "Content Page Revisions",
                "db_table": "cms_content_page_revision",
                "ordering": ["-version"],
            },
        ),
        migrations.AddIndex(
            model_name="contentpage",
            index=models.Index(
                fields=["status", "published_at"], name="cms_content_status_378283_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentpage",
            index=models.Index(
                fields=["page_type", "status"], name="cms_content_page_ty_b37717_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentpagerevision",
            index=models.Index(
                fields=["page", "version"], name="cms_content_page_id_ab1ed3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentpagerevision",
            unique_together={("page", "version")},
        ),
    ]
