# Generated by Django 5.2.7 on 2026-01-26 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "search_term",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("search_count", models.PositiveIntegerField(default=1)),
                (
                    "has_results",
                    models.BooleanField(
                        default=True, help_text="Did this search return results?"
                    ),
                ),
                ("last_searched", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Popular Search",
                "verbose_name_plural": "Popular Searches",
                "db_table": "cms_popular_search",
                "ordering": ["-search_count"],
            },
        ),
        migrations.CreateModel(
            name="HelpCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'Getting Started', 'Account Management')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of what this category covers",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier (e.g., 'question-circle', 'user', 'shopping-cart')",
                        max_length=50,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which categories appear (lower = first)",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("farmers", "Farmers Only"),
                            ("buyers", "Buyers Only"),
                            ("staff", "Staff/Officials Only"),
                        ],
                        default="all",
                        help_text="Who should see this category",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is visible to users",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_help_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Help Category",
                "verbose_name_plural": "Help Categories",
                "db_table": "cms_help_category",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HelpArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Article title (e.g., 'How to Register Your Farm')",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=255, unique=True
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Brief summary shown in search results and listings",
                        max_length=500,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full article content (supports HTML/Markdown)"
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated keywords for search optimization",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("farmers", "Farmers Only"),
                            ("buyers", "Buyers Only"),
                            ("staff", "Staff/Officials Only"),
                        ],
                        default="all",
                        help_text="Who should see this article (overrides category if set)",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the article was published",
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order within category (lower = first)"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this article has been viewed",
                    ),
                ),
                (
                    "helpful_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of users who found this helpful"
                    ),
                ),
                (
                    "not_helpful_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of users who did not find this helpful",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_help_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_help_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_articles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related articles to show at the bottom",
                        to="cms.helparticle",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_help_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this article belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="cms.helpcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Help Article",
                "verbose_name_plural": "Help Articles",
                "db_table": "cms_help_article",
                "ordering": ["category__display_order", "display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="HelpArticleFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Session ID for anonymous feedback tracking",
                        max_length=100,
                    ),
                ),
                (
                    "is_helpful",
                    models.BooleanField(
                        help_text="Did the user find this article helpful?"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Optional feedback comment"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="cms.helparticle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_article_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Feedback",
                "verbose_name_plural": "Article Feedback",
                "db_table": "cms_help_article_feedback",
                "ordering": ["-created_at"],
                "unique_together": {("article", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="helparticle",
            index=models.Index(
                fields=["status", "published_at"], name="cms_help_ar_status_e3bdc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helparticle",
            index=models.Index(
                fields=["category", "status"], name="cms_help_ar_categor_b67b6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helparticle",
            index=models.Index(
                fields=["target_audience", "status"],
                name="cms_help_ar_target__572759_idx",
            ),
        ),
    ]
