# Generated by Django 5.2.7 on 2026-01-19 18:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farms", "0016_distress_tracking_fields"),
        (
            "flock_management",
            "0016_flock_total_bedding_cost_flock_total_labor_cost_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseSubCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LABOR", "Labor & Wages"),
                            ("UTILITIES", "Utilities (Electricity, Water)"),
                            ("BEDDING", "Litter & Bedding"),
                            ("TRANSPORT", "Transport & Delivery"),
                            ("MAINTENANCE", "Equipment & Maintenance"),
                            ("OVERHEAD", "Overhead & Administration"),
                            ("MORTALITY_LOSS", "Mortality Loss"),
                            ("MISCELLANEOUS", "Miscellaneous"),
                        ],
                        help_text="Parent expense category",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Subcategory name (e.g., 'Caretaker Salary', 'Electricity Bill')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this subcategory covers",
                    ),
                ),
                (
                    "default_unit",
                    models.CharField(
                        blank=True,
                        help_text="Default unit of measurement (e.g., 'hours', 'kWh', 'trips')",
                        max_length=50,
                    ),
                ),
                (
                    "default_unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default cost per unit (GHS)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="Farm that created this subcategory",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_subcategories",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Sub-Category",
                "verbose_name_plural": "Expense Sub-Categories",
                "ordering": ["category", "name"],
                "unique_together": {("farm", "category", "name")},
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LABOR", "Labor & Wages"),
                            ("UTILITIES", "Utilities (Electricity, Water)"),
                            ("BEDDING", "Litter & Bedding"),
                            ("TRANSPORT", "Transport & Delivery"),
                            ("MAINTENANCE", "Equipment & Maintenance"),
                            ("OVERHEAD", "Overhead & Administration"),
                            ("MORTALITY_LOSS", "Mortality Loss"),
                            ("MISCELLANEOUS", "Miscellaneous"),
                        ],
                        db_index=True,
                        help_text="Main expense category",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Brief description of the expense", max_length=255
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        db_index=True, help_text="Date expense was incurred"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Quantity (hours, units, kWh, etc.)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="unit", help_text="Unit of measurement", max_length=50
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit (GHS)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total expense amount (auto-calculated)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("BIWEEKLY", "Bi-Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                            ("ONE_TIME", "One-Time"),
                        ],
                        default="ONE_TIME",
                        help_text="How often this expense recurs",
                        max_length=20,
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, help_text="Whether this expense repeats"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partially Paid"),
                        ],
                        default="PAID",
                        help_text="Payment status",
                        max_length=10,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Payment method (Cash, Mobile Money, Bank, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        help_text="Receipt or reference number",
                        max_length=100,
                    ),
                ),
                (
                    "payee_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of person/company paid",
                        max_length=200,
                    ),
                ),
                (
                    "payee_contact",
                    models.CharField(
                        blank=True, help_text="Contact info of payee", max_length=100
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded this expense",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="Farm incurring this expense",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="farms.farm",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific flock (leave blank for farm-level expenses)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="flock_management.flock",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional subcategory for detailed tracking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="expenses.expensesubcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("TOTAL", "Lifetime Total"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "labor_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "utilities_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "bedding_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "transport_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "maintenance_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "overhead_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "mortality_loss_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "miscellaneous_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("expense_count", models.PositiveIntegerField(default=0)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_summaries",
                        to="farms.farm",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific flock (null for farm-wide summary)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_summaries",
                        to="flock_management.flock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Summary",
                "verbose_name_plural": "Expense Summaries",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="LaborRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "worker_name",
                    models.CharField(help_text="Name of worker", max_length=200),
                ),
                (
                    "worker_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent Staff"),
                            ("CASUAL", "Casual Worker"),
                            ("CONTRACT", "Contract Worker"),
                            ("FAMILY", "Family Labor"),
                        ],
                        help_text="Type of worker",
                        max_length=20,
                    ),
                ),
                (
                    "worker_contact",
                    models.CharField(
                        blank=True, help_text="Worker contact (phone)", max_length=100
                    ),
                ),
                ("work_date", models.DateField(help_text="Date of work")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Farm Work"),
                            ("FEEDING", "Feeding"),
                            ("CLEANING", "Cleaning & Sanitation"),
                            ("VACCINATION", "Vaccination Assistance"),
                            ("MEDICATION", "Medication Administration"),
                            ("EGG_COLLECTION", "Egg Collection"),
                            ("PROCESSING", "Processing"),
                            ("MAINTENANCE", "Maintenance Work"),
                            ("SECURITY", "Security"),
                            ("SUPERVISION", "Supervision"),
                            ("OTHER", "Other"),
                        ],
                        default="GENERAL",
                        help_text="Type of task performed",
                        max_length=20,
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hours worked",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate per hour (GHS)",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Overtime hours",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "overtime_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Overtime rate per hour (GHS)",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "base_pay",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base pay (auto-calculated)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "overtime_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Overtime pay (auto-calculated)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_pay",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total pay (auto-calculated)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expense",
                    models.OneToOneField(
                        help_text="Associated expense record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_details",
                        to="expenses.expense",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="Farm",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_records",
                        to="farms.farm",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific flock (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labor_records",
                        to="flock_management.flock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Labor Record",
                "verbose_name_plural": "Labor Records",
                "ordering": ["-work_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MortalityLossRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mortality_date", models.DateField(help_text="Date of mortality")),
                (
                    "birds_lost",
                    models.PositiveIntegerField(help_text="Number of birds lost"),
                ),
                (
                    "cause_of_death",
                    models.CharField(
                        blank=True, help_text="Cause of death", max_length=100
                    ),
                ),
                (
                    "acquisition_cost_per_bird",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original cost per bird (GHS)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "feed_cost_invested",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Estimated feed cost invested in dead birds (GHS)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "other_costs_invested",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Other costs invested (vaccination, medication)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "potential_revenue_lost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Potential revenue if birds had been sold",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_loss_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total economic loss (auto-calculated)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "age_at_death_weeks",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Age of birds at death (weeks)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expense",
                    models.OneToOneField(
                        help_text="Associated expense record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortality_loss_details",
                        to="expenses.expense",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortality_loss_records",
                        to="farms.farm",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        help_text="Flock that experienced mortality",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortality_loss_records",
                        to="flock_management.flock",
                    ),
                ),
                (
                    "mortality_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to mortality record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loss_records",
                        to="flock_management.mortalityrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mortality Loss Record",
                "verbose_name_plural": "Mortality Loss Records",
                "ordering": ["-mortality_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecurringExpenseTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Monthly Caretaker Salary')",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LABOR", "Labor & Wages"),
                            ("UTILITIES", "Utilities (Electricity, Water)"),
                            ("BEDDING", "Litter & Bedding"),
                            ("TRANSPORT", "Transport & Delivery"),
                            ("MAINTENANCE", "Equipment & Maintenance"),
                            ("OVERHEAD", "Overhead & Administration"),
                            ("MORTALITY_LOSS", "Mortality Loss"),
                            ("MISCELLANEOUS", "Miscellaneous"),
                        ],
                        help_text="Expense category",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description for generated expenses", max_length=255
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("unit", models.CharField(default="unit", max_length=50)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated recurring amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("BIWEEKLY", "Bi-Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                            ("ONE_TIME", "One-Time"),
                        ],
                        help_text="How often this expense occurs",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="When to start generating expenses"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When to stop (leave blank for indefinite)",
                        null=True,
                    ),
                ),
                (
                    "last_generated_date",
                    models.DateField(
                        blank=True,
                        help_text="Last date an expense was generated",
                        null=True,
                    ),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True, help_text="Next date expense is due", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to continue generating expenses",
                    ),
                ),
                ("payee_name", models.CharField(blank=True, max_length=200)),
                ("payee_contact", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_expense_templates",
                        to="farms.farm",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific flock (leave blank for farm-level)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_expense_templates",
                        to="flock_management.flock",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="expenses.expensesubcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring Expense Template",
                "verbose_name_plural": "Recurring Expense Templates",
                "ordering": ["next_due_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="UtilityRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "utility_type",
                    models.CharField(
                        choices=[
                            ("ELECTRICITY", "Electricity"),
                            ("WATER", "Water"),
                            ("GAS", "Gas/LPG"),
                            ("FUEL", "Fuel (Generator/Vehicle)"),
                            ("INTERNET", "Internet"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of utility",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Utility provider (ECG, GWCL, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, help_text="Account/meter number", max_length=100
                    ),
                ),
                (
                    "billing_period_start",
                    models.DateField(
                        blank=True, help_text="Start of billing period", null=True
                    ),
                ),
                (
                    "billing_period_end",
                    models.DateField(
                        blank=True, help_text="End of billing period", null=True
                    ),
                ),
                (
                    "previous_reading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Previous meter reading",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "current_reading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current meter reading",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "units_consumed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Units consumed (kWh, gallons, liters)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        default="kWh", help_text="Unit of measurement", max_length=20
                    ),
                ),
                (
                    "rate_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Rate per unit (GHS)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expense",
                    models.OneToOneField(
                        help_text="Associated expense record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_details",
                        to="expenses.expense",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_records",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utility Record",
                "verbose_name_plural": "Utility Records",
                "ordering": ["-billing_period_end", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["farm", "expense_date"], name="expenses_ex_farm_id_88e78c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["farm", "category"], name="expenses_ex_farm_id_d138ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["flock", "expense_date"], name="expenses_ex_flock_i_bcd136_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["category", "expense_date"],
                name="expenses_ex_categor_74f27d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["-expense_date"], name="expenses_ex_expense_0d5c38_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="expensesummary",
            unique_together={
                ("farm", "flock", "period_type", "period_start", "period_end")
            },
        ),
        migrations.AddIndex(
            model_name="laborrecord",
            index=models.Index(
                fields=["farm", "work_date"], name="expenses_la_farm_id_f8e593_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborrecord",
            index=models.Index(
                fields=["worker_name", "work_date"],
                name="expenses_la_worker__35068c_idx",
            ),
        ),
    ]
