# Generated by Django 5.2.7 on 2026-01-19 20:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortalitylossrecord",
            name="costs_auto_calculated",
            field=models.BooleanField(
                default=False,
                help_text="True if feed_cost_invested and other_costs_invested were auto-calculated from tracked data",
            ),
        ),
        migrations.AlterField(
            model_name="mortalitylossrecord",
            name="feed_cost_invested",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Feed cost invested in dead birds (GHS). Auto-calculated from tracked data if not provided.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="mortalitylossrecord",
            name="other_costs_invested",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Other costs invested - vaccination, medication (GHS). Auto-calculated from tracked data if not provided.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
