# Generated by Django 5.2.7 on 2026-01-19 21:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_add_costs_auto_calculated_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortalitylossrecord",
            name="additional_investment_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Investment loss excluding acquisition (feed + medication only) - used for expense tracking to avoid double-counting",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="mortalitylossrecord",
            name="total_loss_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total economic loss including acquisition (for insurance claims, analysis)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
