# Generated by Django 5.1.3 on 2026-01-06 20:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True, help_text="IP address or email", max_length=255
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[("ip", "IP Address"), ("email", "Email")],
                        help_text="Type of identifier",
                        max_length=10,
                    ),
                ),
                (
                    "count",
                    models.IntegerField(default=0, help_text="Number of submissions"),
                ),
                (
                    "window_start",
                    models.DateTimeField(help_text="Start of the rate limit window"),
                ),
                (
                    "last_submission",
                    models.DateTimeField(
                        auto_now=True, help_text="Last submission time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Form Rate Limit",
                "verbose_name_plural": "Contact Form Rate Limits",
                "db_table": "contact_form_rate_limits",
                "unique_together": {("identifier", "identifier_type")},
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the person contacting us", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address for follow-up",
                        max_length=255,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("support", "Technical Support"),
                            ("partnership", "Partnership Opportunity"),
                            ("marketplace", "Marketplace Question"),
                            ("billing", "Billing & Payments"),
                            ("feedback", "Feedback & Suggestions"),
                            ("other", "Other"),
                        ],
                        help_text="Category of the inquiry",
                        max_length=50,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The actual message content (min 10 characters)",
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="new",
                        help_text="Current status of the message",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the submitter (for spam prevention)",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Browser user agent (for spam prevention)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Internal notes from staff"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the message was submitted",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the message was last updated"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member assigned to handle this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_contact_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "db_table": "contact_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessageReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reply_message",
                    models.TextField(help_text="The reply message content"),
                ),
                (
                    "sent_via_email",
                    models.BooleanField(
                        default=True, help_text="Whether this reply was sent via email"
                    ),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the email was successfully sent",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the reply was created"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="The contact message being replied to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="contact.contactmessage",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        help_text="Staff member who sent the reply",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Message Reply",
                "verbose_name_plural": "Contact Message Replies",
                "db_table": "contact_message_replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["status", "created_at"], name="contact_mes_status_60fad8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["assigned_to", "status"], name="contact_mes_assigne_d3330b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(fields=["email"], name="contact_mes_email_a7fb56_idx"),
        ),
        migrations.AddIndex(
            model_name="contactmessagereply",
            index=models.Index(
                fields=["message", "created_at"], name="contact_mes_message_7f1e99_idx"
            ),
        ),
    ]
