# Generated by Django 5.1.3 on 2026-01-03 14:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farms", "0014_alter_farm_government_subsidy_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("feed_supplier", "Feed & Nutrition Supplier"),
                            ("equipment", "Equipment & Infrastructure"),
                            ("veterinary", "Veterinary Services"),
                            ("chicks_supplier", "Day-Old Chicks Supplier"),
                            ("financial", "Banks & Financial Services"),
                            ("insurance", "Insurance Provider"),
                            ("aggregator", "Aggregator / Offtaker"),
                            ("training", "Training & Education"),
                            ("logistics", "Logistics & Delivery"),
                            ("other", "Other Agricultural Service"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="partners/logos/"
                    ),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the partner and their services",
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=100)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this partner been verified by YEA/admin?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("contract_start_date", models.DateField(blank=True, null=True)),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                (
                    "monthly_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly advertising fee (GHS)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_partners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "advertising_partners",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="AdvertiserLead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("feed_supplier", "Feed & Nutrition Supplier"),
                            ("equipment", "Equipment & Infrastructure"),
                            ("veterinary", "Veterinary Services"),
                            ("chicks_supplier", "Day-Old Chicks Supplier"),
                            ("financial", "Banks & Financial Services"),
                            ("insurance", "Insurance Provider"),
                            ("aggregator", "Aggregator / Offtaker"),
                            ("training", "Training & Education"),
                            ("logistics", "Logistics & Delivery"),
                            ("other", "Other Agricultural Service"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                (
                    "advertising_interest",
                    models.TextField(
                        help_text="What products/services they want to advertise"
                    ),
                ),
                (
                    "target_audience",
                    models.TextField(
                        blank=True, help_text="What type of farmers they want to reach"
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("under_500", "Under GHS 500/month"),
                            ("500_2000", "GHS 500 - 2,000/month"),
                            ("2000_5000", "GHS 2,000 - 5,000/month"),
                            ("over_5000", "Over GHS 5,000/month"),
                            ("not_sure", "Not Sure Yet"),
                        ],
                        default="not_sure",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New Lead"),
                            ("contacted", "Contacted"),
                            ("meeting_scheduled", "Meeting Scheduled"),
                            ("proposal_sent", "Proposal Sent"),
                            ("negotiating", "Negotiating"),
                            ("converted", "Converted to Partner"),
                            ("declined", "Declined"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this lead"
                    ),
                ),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "converted_partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_leads",
                        to="advertising.partner",
                    ),
                ),
            ],
            options={
                "db_table": "advertiser_leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short, attention-grabbing title", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed offer description"),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("discount", "Discount / Promo Code"),
                            ("loan", "Loan / Financing"),
                            ("insurance", "Insurance Product"),
                            ("service", "Service Offering"),
                            ("product", "Product Promotion"),
                            ("event", "Event / Training"),
                            ("bulk_purchase", "Bulk Purchase Deal"),
                        ],
                        default="product",
                        max_length=30,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Banner image (recommended: 600x300px)",
                        null=True,
                        upload_to="partners/offers/",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        default="Learn More",
                        help_text="Button text (e.g., 'Get Quote', 'Apply Now', 'Shop Now')",
                        max_length=50,
                    ),
                ),
                (
                    "cta_url",
                    models.URLField(
                        blank=True, help_text="Link when farmer clicks the offer"
                    ),
                ),
                (
                    "promo_code",
                    models.CharField(
                        blank=True,
                        help_text="Promo/discount code if applicable",
                        max_length=50,
                    ),
                ),
                (
                    "targeting",
                    models.CharField(
                        choices=[
                            ("all", "All Farmers"),
                            ("region", "Specific Regions"),
                            ("flock_size", "By Flock Size"),
                            ("experience", "By Experience Level"),
                            ("production", "By Production Volume"),
                            ("marketplace", "Marketplace Active Farmers"),
                            ("government", "Government Program Farmers"),
                        ],
                        default="all",
                        max_length=30,
                    ),
                ),
                (
                    "target_regions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of regions to target (if targeting=region)",
                    ),
                ),
                (
                    "min_flock_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum flock size to show offer (if targeting=flock_size)",
                        null=True,
                    ),
                ),
                (
                    "max_flock_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum flock size to show offer",
                        null=True,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, help_text="Leave blank for indefinite", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured offers appear more prominently",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Higher priority = shown first (1-100)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="advertising.partner",
                    ),
                ),
            ],
            options={
                "db_table": "partner_offers",
                "ordering": ["-is_featured", "-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfferInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("impression", "Viewed"),
                            ("click", "Clicked"),
                            ("dismissed", "Dismissed"),
                            ("converted", "Converted (Completed Action)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_page",
                    models.CharField(
                        blank=True,
                        help_text="Where the offer was shown (dashboard, marketplace, etc.)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_interactions",
                        to="farms.farm",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="advertising.partneroffer",
                    ),
                ),
            ],
            options={
                "db_table": "offer_interactions",
            },
        ),
        migrations.AddIndex(
            model_name="partneroffer",
            index=models.Index(
                fields=["is_active", "start_date", "end_date"],
                name="partner_off_is_acti_9d1777_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partneroffer",
            index=models.Index(
                fields=["targeting"], name="partner_off_targeti_c68b78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partneroffer",
            index=models.Index(
                fields=["partner"], name="partner_off_partner_6e2ee1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offerinteraction",
            index=models.Index(
                fields=["offer", "farm"], name="offer_inter_offer_i_2b9c74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offerinteraction",
            index=models.Index(
                fields=["created_at"], name="offer_inter_created_2b6caf_idx"
            ),
        ),
    ]
