# Generated by Django 5.1.3 on 2026-01-04 12:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertising", "0001_initial"),
        ("farms", "0014_alter_farm_government_subsidy_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionWebhookKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "daily_limit",
                    models.PositiveIntegerField(
                        default=1000, help_text="Maximum conversions per day"
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_key",
                        to="advertising.partner",
                    ),
                ),
            ],
            options={
                "db_table": "conversion_webhook_keys",
            },
        ),
        migrations.CreateModel(
            name="OfferVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Control', 'Variant A', 'Green CTA'",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use offer's title",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Leave blank to use offer's description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="partners/offers/variants/"
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use offer's CTA",
                        max_length=50,
                    ),
                ),
                (
                    "traffic_percentage",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Percentage of traffic to receive this variant (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_winner",
                    models.BooleanField(
                        default=False,
                        help_text="Marked as winning variant after test completion",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="advertising.partneroffer",
                    ),
                ),
            ],
            options={
                "db_table": "offer_variants",
                "ordering": ["-traffic_percentage", "name"],
                "unique_together": {("offer", "name")},
            },
        ),
        migrations.CreateModel(
            name="ConversionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversion_type",
                    models.CharField(
                        choices=[
                            ("signup", "Partner Sign Up"),
                            ("purchase", "Purchase Made"),
                            ("application", "Application Submitted"),
                            ("registration", "Event Registration"),
                            ("quote_request", "Quote Requested"),
                            ("contact", "Contact Form Submitted"),
                            ("download", "Resource Downloaded"),
                            ("other", "Other Conversion"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "conversion_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Value of conversion in GHS (if applicable)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "promo_code_used",
                    models.CharField(
                        blank=True,
                        help_text="Promo code used in conversion",
                        max_length=50,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="External transaction/reference ID from partner",
                        max_length=100,
                    ),
                ),
                (
                    "attribution_window_hours",
                    models.PositiveIntegerField(
                        default=168, help_text="Hours between click and conversion"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("webhook", "Partner Webhook"),
                            ("manual", "Manual Entry"),
                            ("api", "Partner API"),
                            ("promo_code", "Promo Code Redemption"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Has this conversion been verified?"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "click_interaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="The click that led to this conversion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions",
                        to="advertising.offerinteraction",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_conversions",
                        to="farms.farm",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to="advertising.partneroffer",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_conversions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversion_events",
                        to="advertising.offervariant",
                    ),
                ),
            ],
            options={
                "db_table": "conversion_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["offer", "created_at"],
                        name="conversion__offer_i_5cf1c4_idx",
                    ),
                    models.Index(
                        fields=["farm", "created_at"],
                        name="conversion__farm_id_6b26d9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartnerPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="GHS", max_length=3)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("monthly_fee", "Monthly Advertising Fee"),
                            ("campaign_fee", "Campaign Fee"),
                            ("setup_fee", "Setup/Onboarding Fee"),
                            ("performance_bonus", "Performance Bonus"),
                            ("renewal", "Contract Renewal"),
                            ("one_time", "One-Time Payment"),
                            ("other", "Other"),
                        ],
                        default="monthly_fee",
                        max_length=30,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True, help_text="Start of billing period", null=True
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True, help_text="End of billing period", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("mobile_money", "Mobile Money"),
                            ("cheque", "Cheque"),
                            ("cash", "Cash"),
                            ("online", "Online Payment"),
                        ],
                        default="bank_transfer",
                        max_length=30,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True, help_text="Bank/payment reference", max_length=100
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, help_text="Invoice number", max_length=50
                    ),
                ),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="advertising.partner",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_ad_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "partner_payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["partner", "status"],
                        name="partner_pay_partner_b1bf3e_idx",
                    ),
                    models.Index(
                        fields=["status", "due_date"],
                        name="partner_pay_status_4268d2_idx",
                    ),
                    models.Index(
                        fields=["paid_at"], name="partner_pay_paid_at_a87540_idx"
                    ),
                ],
            },
        ),
    ]
