# Generated by Django 5.2.7 on 2026-01-08 17:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "advertising",
            "0002_conversionwebhookkey_offervariant_conversionevent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="partneroffer",
            name="cooldown_hours",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Hours to wait before showing offer again to same farmer after click/dismiss",
            ),
        ),
        migrations.AddField(
            model_name="partneroffer",
            name="cost_per_click",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost per click for CPC campaigns (GHS)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partneroffer",
            name="daily_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Daily budget limit for CPC campaigns (GHS)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partneroffer",
            name="daily_spend",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Current day's spend (reset daily)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="partneroffer",
            name="max_impressions_per_day",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum total impressions per day across all farmers (null = unlimited)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partneroffer",
            name="max_impressions_per_user",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum times this offer is shown to a single farmer (null = unlimited)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partneroffer",
            name="show_end_hour",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="End hour to show offer (0-23, Ghana time)",
                null=True,
                validators=[django.core.validators.MaxValueValidator(23)],
            ),
        ),
        migrations.AddField(
            model_name="partneroffer",
            name="show_on_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Days of week to show (0=Monday, 6=Sunday). Empty = all days",
            ),
        ),
        migrations.AddField(
            model_name="partneroffer",
            name="show_start_hour",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Start hour to show offer (0-23, Ghana time)",
                null=True,
                validators=[django.core.validators.MaxValueValidator(23)],
            ),
        ),
    ]
