# Generated by Django 5.1.3 on 2026-01-08 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertising", "0003_add_phase2_features"),
        ("farms", "0015_remove_verified_seller_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversionevent",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                help_text="Farm associated with conversion (may be null for unattributed conversions)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_conversions",
                to="farms.farm",
            ),
        ),
    ]
