# Generated by Django 5.2.7 on 2025-11-27 13:06

import accounts.roles
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("FARMER", "Farmer"),
                            ("CONSTITUENCY_OFFICIAL", "Constituency Official"),
                            ("NATIONAL_ADMIN", "National Administrator"),
                            ("PROCUREMENT_OFFICER", "Procurement Officer"),
                            ("VETERINARY_OFFICER", "Veterinary Officer"),
                            ("AUDITOR", "Auditor"),
                        ],
                        db_index=True,
                        default="FARMER",
                        help_text="User's primary role in the system",
                        max_length=50,
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True,
                        help_text="Phone number (Ghana format: +233XXXXXXXXX)",
                        max_length=128,
                        region="GH",
                        unique=True,
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the phone number has been verified",
                    ),
                ),
                (
                    "phone_verification_code",
                    models.CharField(
                        blank=True,
                        help_text="OTP code for phone verification",
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "phone_verification_code_expires",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expiration time for phone verification code",
                        null=True,
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False, help_text="Whether the email has been verified"
                    ),
                ),
                (
                    "email_verification_token",
                    models.CharField(
                        blank=True,
                        help_text="Token for email verification",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("PHONE", "Phone"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        default="EMAIL",
                        help_text="Preferred method of contact",
                        max_length=20,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Assigned region (for officials)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "constituency",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Assigned constituency (for constituency officials)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user account is fully verified",
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(
                        default=0,
                        help_text="Number of consecutive failed login attempts",
                    ),
                ),
                (
                    "account_locked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Account locked until this time due to failed login attempts",
                        null=True,
                    ),
                ),
                (
                    "password_reset_token",
                    models.CharField(
                        blank=True,
                        help_text="Token for password reset",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "password_reset_token_expires",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expiration time for password reset token",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
            bases=(models.Model, accounts.roles.RoleMixin),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Permission name (e.g., 'can_approve_farms', 'can_edit_reports')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        help_text="Unique code for this permission",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this permission allows",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True,
                        help_text="Category (e.g., 'farm_management', 'procurement', 'reporting')",
                        max_length=50,
                    ),
                ),
                (
                    "is_system_permission",
                    models.BooleanField(
                        default=False, help_text="System permissions cannot be deleted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "permissions",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="MFASettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mfa_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False, help_text="Whether MFA is enabled for this user"
                    ),
                ),
                (
                    "is_enforced",
                    models.BooleanField(
                        default=False,
                        help_text="Whether MFA is enforced by admin (cannot be disabled)",
                    ),
                ),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "require_for_sensitive_actions",
                    models.BooleanField(
                        default=True,
                        help_text="Require MFA for sensitive actions (password change, etc.)",
                    ),
                ),
                (
                    "remember_device_enabled",
                    models.BooleanField(
                        default=True, help_text="Allow remembering trusted devices"
                    ),
                ),
                (
                    "remember_device_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Days to remember trusted devices"
                    ),
                ),
                ("backup_codes_generated", models.BooleanField(default=False)),
                (
                    "backup_codes_generated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("backup_codes_remaining", models.PositiveIntegerField(default=0)),
                (
                    "last_successful_verification",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "failed_verification_attempts",
                    models.PositiveIntegerField(default=0),
                ),
                ("last_failed_attempt", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MFA Settings",
                "verbose_name_plural": "MFA Settings",
            },
        ),
        migrations.CreateModel(
            name="MFABackupCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="SHA256 hash of the backup code",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("used_from_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_backup_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MFAMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("totp", "Authenticator App (TOTP)"),
                            ("sms", "SMS Verification"),
                            ("email", "Email Verification"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary method used by default"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this method is currently active",
                    ),
                ),
                (
                    "totp_secret",
                    models.CharField(
                        blank=True,
                        help_text="Base32 encoded secret for TOTP",
                        max_length=64,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Phone number for SMS verification",
                        max_length=20,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        help_text="Email for email verification",
                        max_length=254,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has successfully verified this method",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-is_enabled", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MFAVerificationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("login", "Login Verification"),
                            ("setup", "MFA Setup"),
                            ("disable", "MFA Disable"),
                            ("recovery", "Account Recovery"),
                        ],
                        default="login",
                        max_length=20,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=6,
                        validators=[django.core.validators.MinLengthValidator(6)],
                    ),
                ),
                (
                    "sent_to",
                    models.CharField(
                        help_text="Phone number or email where code was sent",
                        max_length=200,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Code expires after 10 minutes"),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("verification_attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mfa_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to="accounts.mfamethod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_verification_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Role name (e.g., 'admin', 'moderator', 'farm_owner')",
                        max_length=100,
                    ),
                ),
                (
                    "resource_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the specific resource this role is scoped to",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this role can do"
                    ),
                ),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=False, help_text="System roles cannot be deleted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Content type of the resource this role is scoped to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="accounts.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
                "db_table": "role_permissions",
            },
        ),
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        help_text="User-provided device name or auto-detected",
                        max_length=200,
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        help_text="Hash of user agent + IP or device token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("is_trusted", models.BooleanField(default=True)),
                (
                    "trust_expires_at",
                    models.DateTimeField(
                        help_text="Trust expires after 30 days by default"
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiration date for temporary roles",
                        null=True,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who assigned this role",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="accounts.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "user_roles",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="users_role_a8f2ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["region", "constituency"], name="users_region_88eeb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email_verified", "phone_verified"],
                name="users_email_v_56af83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mfabackupcode",
            index=models.Index(
                fields=["user", "is_used"], name="accounts_mf_user_id_94d62a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mfamethod",
            index=models.Index(
                fields=["user", "is_enabled"], name="accounts_mf_user_id_936513_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mfamethod",
            index=models.Index(
                fields=["method_type", "is_enabled"],
                name="accounts_mf_method__3924f2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mfamethod",
            unique_together={("user", "method_type")},
        ),
        migrations.AddIndex(
            model_name="mfaverificationcode",
            index=models.Index(
                fields=["user", "code_type", "is_used"],
                name="accounts_mf_user_id_77a848_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mfaverificationcode",
            index=models.Index(
                fields=["expires_at"], name="accounts_mf_expires_8abce2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["name"], name="roles_name_a96913_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["resource_type", "resource_id"], name="roles_resourc_29a367_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("name", "resource_type", "resource_id")},
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(
                fields=["user", "is_trusted", "revoked"],
                name="accounts_tr_user_id_e2b4bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(
                fields=["device_fingerprint"], name="accounts_tr_device__626d39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(
                fields=["trust_expires_at"], name="accounts_tr_trust_e_8bfa44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "role"], name="user_roles_user_id_801a9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["expires_at"], name="user_roles_expires_aafda2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role")},
        ),
    ]
