# Generated by Django 5.1.3 on 2026-01-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Administrator"),
                    ("YEA_OFFICIAL", "YEA Official"),
                    ("NATIONAL_ADMIN", "National Administrator"),
                    ("REGIONAL_COORDINATOR", "Regional Coordinator"),
                    ("CONSTITUENCY_OFFICIAL", "Constituency Official"),
                    ("PROCUREMENT_OFFICER", "Procurement Officer"),
                    ("VETERINARY_OFFICER", "Veterinary Officer"),
                    ("EXTENSION_OFFICER", "Extension Officer"),
                    ("FINANCE_OFFICER", "Finance Officer"),
                    ("AUDITOR", "Auditor"),
                    ("FARMER", "Farmer"),
                ],
                db_index=True,
                default="FARMER",
                help_text="User's primary role in the system",
                max_length=50,
            ),
        ),
    ]
