# Generated by Django 5.2.7 on 2025-11-26 14:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MFASettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mfa_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False, help_text="Whether MFA is enabled for this user"
                    ),
                ),
                (
                    "is_enforced",
                    models.BooleanField(
                        default=False,
                        help_text="Whether MFA is enforced by admin (cannot be disabled)",
                    ),
                ),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "require_for_sensitive_actions",
                    models.BooleanField(
                        default=True,
                        help_text="Require MFA for sensitive actions (password change, etc.)",
                    ),
                ),
                (
                    "remember_device_enabled",
                    models.BooleanField(
                        default=True, help_text="Allow remembering trusted devices"
                    ),
                ),
                (
                    "remember_device_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Days to remember trusted devices"
                    ),
                ),
                ("backup_codes_generated", models.BooleanField(default=False)),
                (
                    "backup_codes_generated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("backup_codes_remaining", models.PositiveIntegerField(default=0)),
                (
                    "last_successful_verification",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "failed_verification_attempts",
                    models.PositiveIntegerField(default=0),
                ),
                ("last_failed_attempt", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MFA Settings",
                "verbose_name_plural": "MFA Settings",
            },
        ),
        migrations.CreateModel(
            name="MFAMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("totp", "Authenticator App (TOTP)"),
                            ("sms", "SMS Verification"),
                            ("email", "Email Verification"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary method used by default"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this method is currently active",
                    ),
                ),
                (
                    "totp_secret",
                    models.CharField(
                        blank=True,
                        help_text="Base32 encoded secret for TOTP",
                        max_length=64,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Phone number for SMS verification",
                        max_length=20,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        help_text="Email for email verification",
                        max_length=254,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has successfully verified this method",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-is_enabled", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MFAVerificationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("login", "Login Verification"),
                            ("setup", "MFA Setup"),
                            ("disable", "MFA Disable"),
                            ("recovery", "Account Recovery"),
                        ],
                        default="login",
                        max_length=20,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=6,
                        validators=[django.core.validators.MinLengthValidator(6)],
                    ),
                ),
                (
                    "sent_to",
                    models.CharField(
                        help_text="Phone number or email where code was sent",
                        max_length=200,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Code expires after 10 minutes"),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("verification_attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mfa_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to="accounts.mfamethod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_verification_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        help_text="User-provided device name or auto-detected",
                        max_length=200,
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        help_text="Hash of user agent + IP or device token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("is_trusted", models.BooleanField(default=True)),
                (
                    "trust_expires_at",
                    models.DateTimeField(
                        help_text="Trust expires after 30 days by default"
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MFABackupCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="SHA256 hash of the backup code",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("used_from_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_backup_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_used"],
                        name="accounts_mf_user_id_94d62a_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mfamethod",
            index=models.Index(
                fields=["user", "is_enabled"], name="accounts_mf_user_id_936513_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mfamethod",
            index=models.Index(
                fields=["method_type", "is_enabled"],
                name="accounts_mf_method__3924f2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mfamethod",
            unique_together={("user", "method_type")},
        ),
        migrations.AddIndex(
            model_name="mfaverificationcode",
            index=models.Index(
                fields=["user", "code_type", "is_used"],
                name="accounts_mf_user_id_77a848_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mfaverificationcode",
            index=models.Index(
                fields=["expires_at"], name="accounts_mf_expires_8abce2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(
                fields=["user", "is_trusted", "revoked"],
                name="accounts_tr_user_id_e2b4bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(
                fields=["device_fingerprint"], name="accounts_tr_device__626d39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(
                fields=["trust_expires_at"], name="accounts_tr_trust_e_8bfa44_idx"
            ),
        ),
    ]
