# Generated by Django 5.1.3 on 2026-01-04 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_suspended",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the user account is currently suspended",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_failed_login_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last failed login attempt",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="suspended_at",
            field=models.DateTimeField(
                blank=True, help_text="When the account was suspended", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="suspended_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who suspended this account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suspended_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="suspended_until",
            field=models.DateTimeField(
                blank=True,
                help_text="When the suspension expires (null = indefinite)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="suspension_reason",
            field=models.TextField(
                blank=True, help_text="Reason for account suspension"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="token_version",
            field=models.IntegerField(
                default=0, help_text="Increment to invalidate all existing tokens"
            ),
        ),
    ]
