# Generated by Django 5.1.3 on 2026-01-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_add_suspension_and_security_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="district",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="District (for farmers - synced from farm registration)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="constituency",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Assigned constituency (for officials) or farm constituency (for farmers)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Assigned region (for officials) or farm region (for farmers)",
                max_length=100,
                null=True,
            ),
        ),
    ]
