# Generated by Django 5.2.7 on 2026-01-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_role"),
        ("subscriptions", "0006_add_institutional_subscriber_role_and_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="institutional_subscriber",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked institutional subscriber (for INSTITUTIONAL_SUBSCRIBER role only)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="subscriptions.institutionalsubscriber",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Administrator"),
                    ("COMPANY_ADMIN", "Company Administrator"),
                    ("YEA_OFFICIAL", "YEA Official"),
                    ("NATIONAL_ADMIN", "National Administrator"),
                    ("REGIONAL_COORDINATOR", "Regional Coordinator"),
                    ("CONSTITUENCY_OFFICIAL", "Constituency Official"),
                    ("PROCUREMENT_OFFICER", "Procurement Officer"),
                    ("VETERINARY_OFFICER", "Veterinary Officer"),
                    ("EXTENSION_OFFICER", "Extension Officer"),
                    ("FINANCE_OFFICER", "Finance Officer"),
                    ("AUDITOR", "Auditor"),
                    ("INSTITUTIONAL_SUBSCRIBER", "Institutional Data Subscriber"),
                    ("FARMER", "Farmer"),
                ],
                db_index=True,
                default="FARMER",
                help_text="User's primary role in the system",
                max_length=50,
            ),
        ),
    ]
