# Generated by Django 5.2.7 on 2026-01-10 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_institutional_subscriber_role_and_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Administrator"),
                    ("NATIONAL_ADMIN", "National Administrator"),
                    ("NATIONAL_STAFF", "National Staff"),
                    ("REGIONAL_ADMIN", "Regional Administrator"),
                    ("REGIONAL_STAFF", "Regional Staff"),
                    ("CONSTITUENCY_ADMIN", "Constituency Administrator"),
                    ("CONSTITUENCY_STAFF", "Constituency Staff"),
                    ("EXTENSION_OFFICER", "Extension Officer"),
                    ("VETERINARY_OFFICER", "Veterinary Officer"),
                    ("YEA_OFFICIAL", "YEA Field Official"),
                    ("PROCUREMENT_OFFICER", "Procurement Officer"),
                    ("FINANCE_OFFICER", "Finance Officer"),
                    ("AUDITOR", "Auditor"),
                    ("INSTITUTIONAL_SUBSCRIBER", "Institutional Data Subscriber"),
                    ("FARMER", "Farmer"),
                    ("COMPANY_ADMIN", "Company Administrator"),
                    ("REGIONAL_COORDINATOR", "Regional Coordinator"),
                    ("CONSTITUENCY_OFFICIAL", "Constituency Official"),
                ],
                db_index=True,
                default="FARMER",
                help_text="User's primary role in the system",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_granted",
                    models.BooleanField(
                        default=True,
                        help_text="True = permission granted, False = permission revoked",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for granting/revoking this permission",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who granted/revoked this permission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permissions_granted_to_others",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="accounts.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Permission",
                "verbose_name_plural": "User Permissions",
                "db_table": "user_permissions",
                "indexes": [
                    models.Index(
                        fields=["user", "is_granted"],
                        name="user_permis_user_id_c656b4_idx",
                    )
                ],
                "unique_together": {("user", "permission")},
            },
        ),
    ]
