# Generated by Django 5.2.7 on 2025-10-26 12:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        ("flock_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Trade/commercial name of the medication",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "generic_name",
                    models.CharField(
                        blank=True, help_text="Generic/scientific name", max_length=200
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ANTIBIOTIC", "Antibiotic"),
                            ("VACCINE", "Vaccine"),
                            ("VITAMIN", "Vitamin/Supplement"),
                            ("DEWORMER", "Dewormer/Antiparasitic"),
                            ("COCCIDIOSTAT", "Coccidiostat"),
                            ("PROBIOTIC", "Probiotic"),
                            ("DISINFECTANT", "Disinfectant"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Category of medication",
                        max_length=20,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, help_text="Manufacturer/brand", max_length=100
                    ),
                ),
                (
                    "active_ingredient",
                    models.CharField(
                        blank=True,
                        help_text="Main active ingredient(s)",
                        max_length=200,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        blank=True,
                        help_text="Strength/concentration (e.g., '10% w/v', '250mg/ml')",
                        max_length=100,
                    ),
                ),
                (
                    "administration_route",
                    models.CharField(
                        choices=[
                            ("ORAL", "Oral (in water/feed)"),
                            ("INJECTION_IM", "Intramuscular Injection"),
                            ("INJECTION_SC", "Subcutaneous Injection"),
                            ("EYE_DROP", "Eye Drop"),
                            ("NASAL", "Nasal Drop"),
                            ("SPRAY", "Spray"),
                            ("TOPICAL", "Topical"),
                        ],
                        help_text="Route of administration",
                        max_length=20,
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        help_text="Recommended dosage (e.g., '1ml per liter water', '0.5ml per bird')",
                        max_length=200,
                    ),
                ),
                (
                    "indication",
                    models.TextField(help_text="What this medication treats/prevents"),
                ),
                (
                    "contraindications",
                    models.TextField(
                        blank=True, help_text="When NOT to use this medication"
                    ),
                ),
                (
                    "withdrawal_period_days",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Days before slaughter/egg consumption after treatment (0 if none)",
                    ),
                ),
                (
                    "egg_withdrawal_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Days before egg consumption after treatment (for layers)",
                        null=True,
                    ),
                ),
                (
                    "meat_withdrawal_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Days before slaughter after treatment (for broilers)",
                        null=True,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price per unit (GHS)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "unit_measure",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measure (e.g., 'per 100ml bottle', 'per 1000 dose vial')",
                        max_length=50,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Veterinary drug registration number",
                        max_length=100,
                    ),
                ),
                (
                    "requires_prescription",
                    models.BooleanField(
                        default=False, help_text="Whether prescription is required"
                    ),
                ),
                (
                    "storage_conditions",
                    models.TextField(
                        blank=True, help_text="Storage temperature and conditions"
                    ),
                ),
                (
                    "shelf_life_months",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Shelf life in months", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this medication is currently available",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or warnings"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Medication Type",
                "verbose_name_plural": "Medication Types",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="medication__categor_cfb932_idx",
                    ),
                    models.Index(fields=["name"], name="medication__name_47e33b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VaccinationSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "flock_type",
                    models.CharField(
                        choices=[
                            ("LAYER", "Layers"),
                            ("BROILER", "Broilers"),
                            ("BREEDER", "Breeders"),
                            ("ALL", "All Types"),
                        ],
                        help_text="Type of birds for this schedule",
                        max_length=10,
                    ),
                ),
                (
                    "age_in_weeks",
                    models.PositiveSmallIntegerField(
                        help_text="Age of birds in weeks when vaccination should occur"
                    ),
                ),
                (
                    "age_in_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Age in days (for day-old vaccinations, overrides weeks)",
                        null=True,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("ONCE", "One-time"),
                            ("ANNUAL", "Annual"),
                            ("BIANNUAL", "Twice per year"),
                            ("AS_NEEDED", "As needed"),
                        ],
                        default="ONCE",
                        help_text="How often this vaccination is needed",
                        max_length=10,
                    ),
                ),
                (
                    "dosage_per_bird",
                    models.CharField(
                        help_text="Dosage per bird (e.g., '1 dose', '0.3ml')",
                        max_length=100,
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this vaccination is legally required",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Priority level (1=lowest, 10=highest)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "disease_prevented",
                    models.CharField(
                        help_text="Disease(s) this vaccination prevents", max_length=200
                    ),
                ),
                (
                    "symptoms_to_watch",
                    models.TextField(
                        blank=True, help_text="Symptoms farmers should monitor for"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or special instructions"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this schedule is currently in use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medication_type",
                    models.ForeignKey(
                        help_text="Vaccine to be administered",
                        limit_choices_to={"category": "VACCINE"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vaccination_schedules",
                        to="medication_management.medicationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaccination Schedule",
                "verbose_name_plural": "Vaccination Schedules",
                "ordering": ["flock_type", "age_in_weeks", "priority"],
            },
        ),
        migrations.CreateModel(
            name="VaccinationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vaccination_date",
                    models.DateField(help_text="Date vaccination was given"),
                ),
                (
                    "birds_vaccinated",
                    models.PositiveIntegerField(help_text="Number of birds vaccinated"),
                ),
                (
                    "flock_age_weeks",
                    models.PositiveSmallIntegerField(
                        help_text="Age of flock in weeks at vaccination"
                    ),
                ),
                (
                    "dosage_per_bird",
                    models.CharField(help_text="Dosage per bird", max_length=100),
                ),
                (
                    "administration_route",
                    models.CharField(
                        help_text="How vaccine was administered", max_length=100
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        help_text="Vaccine batch/lot number", max_length=50
                    ),
                ),
                ("expiry_date", models.DateField(help_text="Vaccine expiry date")),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, help_text="Vaccine manufacturer", max_length=100
                    ),
                ),
                (
                    "quantity_used",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity of vaccine used (doses)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per dose (GHS)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total vaccination cost (auto-calculated)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "administered_by",
                    models.CharField(
                        help_text="Person/veterinarian who administered vaccine",
                        max_length=100,
                    ),
                ),
                (
                    "vet_license_number",
                    models.CharField(
                        blank=True,
                        help_text="Veterinarian license number (if applicable)",
                        max_length=50,
                    ),
                ),
                (
                    "is_mandatory_compliance",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this vaccination fulfills mandatory compliance requirement",
                    ),
                ),
                (
                    "next_vaccination_due",
                    models.DateField(
                        blank=True, help_text="When next dose/booster is due", null=True
                    ),
                ),
                (
                    "adverse_reactions",
                    models.TextField(
                        blank=True, help_text="Any adverse reactions observed"
                    ),
                ),
                (
                    "mortality_within_24hrs",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of birds that died within 24 hours post-vaccination",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this vaccination"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccination_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="Farm where vaccination occurred (denormalized)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vaccination_records",
                        to="farms.farm",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        help_text="Flock being vaccinated",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vaccination_records",
                        to="flock_management.flock",
                    ),
                ),
                (
                    "medication_type",
                    models.ForeignKey(
                        help_text="Vaccine administered",
                        limit_choices_to={"category": "VACCINE"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vaccination_records",
                        to="medication_management.medicationtype",
                    ),
                ),
                (
                    "vaccination_schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Schedule this vaccination follows (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccination_records",
                        to="medication_management.vaccinationschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaccination Record",
                "verbose_name_plural": "Vaccination Records",
                "ordering": ["-vaccination_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VetVisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visit_date", models.DateField(help_text="Date of visit")),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine Inspection"),
                            ("EMERGENCY", "Emergency Call"),
                            ("VACCINATION", "Vaccination Campaign"),
                            ("DISEASE_INVESTIGATION", "Disease Investigation"),
                            ("COMPLIANCE_CHECK", "Compliance Check"),
                            ("FOLLOW_UP", "Follow-up Visit"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of visit",
                        max_length=25,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        help_text="Visit status",
                        max_length=10,
                    ),
                ),
                (
                    "veterinarian_name",
                    models.CharField(
                        help_text="Name of veterinary officer", max_length=100
                    ),
                ),
                (
                    "vet_license_number",
                    models.CharField(
                        help_text="Veterinary license number", max_length=50
                    ),
                ),
                (
                    "vet_phone",
                    models.CharField(
                        blank=True,
                        help_text="Veterinarian contact number",
                        max_length=20,
                    ),
                ),
                (
                    "vet_organization",
                    models.CharField(
                        blank=True, help_text="Organization/clinic name", max_length=200
                    ),
                ),
                ("purpose", models.TextField(help_text="Purpose/reason for visit")),
                (
                    "findings",
                    models.TextField(
                        blank=True, help_text="Veterinarian's findings and observations"
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(blank=True, help_text="Diagnosis (if any)"),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, help_text="Veterinarian's recommendations"
                    ),
                ),
                (
                    "medications_prescribed",
                    models.TextField(blank=True, help_text="Medications prescribed"),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False, help_text="Whether follow-up visit is needed"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, help_text="Scheduled follow-up date", null=True
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("COMPLIANT", "Compliant"),
                            ("NON_COMPLIANT", "Non-Compliant"),
                            ("PARTIAL", "Partially Compliant"),
                            ("N/A", "Not Applicable"),
                        ],
                        default="N/A",
                        help_text="Compliance status after inspection",
                        max_length=20,
                    ),
                ),
                (
                    "issues_identified",
                    models.TextField(
                        blank=True, help_text="Compliance issues identified"
                    ),
                ),
                (
                    "certificate_issued",
                    models.BooleanField(
                        default=False, help_text="Whether health certificate was issued"
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True,
                        help_text="Certificate number (if issued)",
                        max_length=50,
                    ),
                ),
                (
                    "visit_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Veterinary visit fee (GHS)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "report_file",
                    models.CharField(
                        blank=True, help_text="Path to vet report file", max_length=500
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this visit"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vet_visits_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="Farm visited",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vet_visits",
                        to="farms.farm",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific flock inspected (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vet_visits",
                        to="flock_management.flock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veterinary Visit",
                "verbose_name_plural": "Veterinary Visits",
                "ordering": ["-visit_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "administered_date",
                    models.DateField(help_text="Date medication was given"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("TREATMENT", "Treatment (Sick birds)"),
                            ("PREVENTION", "Prevention"),
                            ("GROWTH", "Growth promotion"),
                            ("STRESS", "Stress management"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Reason for medication",
                        max_length=20,
                    ),
                ),
                (
                    "dosage_given",
                    models.CharField(
                        help_text="Actual dosage administered", max_length=200
                    ),
                ),
                (
                    "birds_treated",
                    models.PositiveIntegerField(help_text="Number of birds treated"),
                ),
                (
                    "treatment_days",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Number of days treatment will continue"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Expected end date of treatment (auto-calculated)"
                    ),
                ),
                (
                    "quantity_used",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity of medication used",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit (GHS)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total medication cost (auto-calculated)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "withdrawal_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when withdrawal period ends (auto-calculated)",
                        null=True,
                    ),
                ),
                (
                    "administered_by",
                    models.CharField(
                        blank=True,
                        help_text="Person who administered the medication",
                        max_length=100,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True,
                        help_text="Medication batch/lot number",
                        max_length=50,
                    ),
                ),
                (
                    "symptoms_before",
                    models.TextField(
                        blank=True, help_text="Symptoms observed before treatment"
                    ),
                ),
                (
                    "effectiveness_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Treatment effectiveness (1=poor, 5=excellent)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "side_effects",
                    models.TextField(blank=True, help_text="Any side effects observed"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this medication"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medication_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="Farm where medication was administered (denormalized)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medication_records",
                        to="farms.farm",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        help_text="Flock receiving medication",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medication_records",
                        to="flock_management.flock",
                    ),
                ),
                (
                    "medication_type",
                    models.ForeignKey(
                        help_text="Medication administered",
                        limit_choices_to={
                            "category__in": [
                                "ANTIBIOTIC",
                                "VITAMIN",
                                "DEWORMER",
                                "COCCIDIOSTAT",
                                "PROBIOTIC",
                                "OTHER",
                            ]
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medication_records",
                        to="medication_management.medicationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication Record",
                "verbose_name_plural": "Medication Records",
                "ordering": ["-administered_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["flock", "administered_date"],
                        name="medication__flock_i_34f4bb_idx",
                    ),
                    models.Index(
                        fields=["farm", "administered_date"],
                        name="medication__farm_id_ddff0c_idx",
                    ),
                    models.Index(
                        fields=["-administered_date"],
                        name="medication__adminis_63de8f_idx",
                    ),
                    models.Index(
                        fields=["withdrawal_end_date"],
                        name="medication__withdra_3600e1_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="vaccinationschedule",
            index=models.Index(
                fields=["flock_type", "age_in_weeks"],
                name="medication__flock_t_b94d25_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vaccinationschedule",
            index=models.Index(
                fields=["is_mandatory"], name="medication__is_mand_f481d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaccinationrecord",
            index=models.Index(
                fields=["flock", "vaccination_date"],
                name="medication__flock_i_5930f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vaccinationrecord",
            index=models.Index(
                fields=["farm", "vaccination_date"],
                name="medication__farm_id_0fc94d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vaccinationrecord",
            index=models.Index(
                fields=["-vaccination_date"], name="medication__vaccina_ee4da1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaccinationrecord",
            index=models.Index(
                fields=["batch_number"], name="medication__batch_n_fa0198_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaccinationrecord",
            index=models.Index(
                fields=["is_mandatory_compliance"],
                name="medication__is_mand_b6da45_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vetvisit",
            index=models.Index(
                fields=["farm", "visit_date"], name="medication__farm_id_7a53da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vetvisit",
            index=models.Index(
                fields=["flock", "visit_date"], name="medication__flock_i_0814a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vetvisit",
            index=models.Index(
                fields=["-visit_date"], name="medication__visit_d_587503_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vetvisit",
            index=models.Index(fields=["status"], name="medication__status_9b476f_idx"),
        ),
        migrations.AddIndex(
            model_name="vetvisit",
            index=models.Index(
                fields=["visit_type"], name="medication__visit_t_f3b27d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vetvisit",
            index=models.Index(
                fields=["follow_up_required", "follow_up_date"],
                name="medication__follow__2eb795_idx",
            ),
        ),
    ]
