# Generated by Django 5.2.7 on 2025-10-26 13:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        ("flock_management", "0002_alter_dailyproduction_feed_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("business", "Business"),
                            ("retailer", "Retailer"),
                            ("wholesaler", "Wholesaler"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Ghana phone number",
                                regex="^\\+?233\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "mobile_money_number",
                    models.CharField(
                        help_text="Mobile money number for payments",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Ghana phone number",
                                regex="^\\+?233\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "mobile_money_provider",
                    models.CharField(
                        choices=[
                            ("mtn", "MTN Mobile Money"),
                            ("vodafone", "Vodafone Cash"),
                            ("airteltigo", "AirtelTigo Money"),
                        ],
                        help_text="Mobile money provider",
                        max_length=20,
                    ),
                ),
                (
                    "mobile_money_account_name",
                    models.CharField(
                        help_text="Account holder name for mobile money", max_length=200
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("delivery_address", models.TextField(blank=True)),
                (
                    "total_purchases",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_orders",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the customer"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BirdSale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sale_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "bird_type",
                    models.CharField(
                        choices=[
                            ("layer", "Layer"),
                            ("broiler", "Broiler"),
                            ("cockerel", "Cockerel"),
                            ("spent_hen", "Spent Hen"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "price_per_bird",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "platform_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "paystack_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "farmer_payout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("paid", "Payment Received"),
                            ("processing", "Processing Payout"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bird_sales",
                        to="farms.farm",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        help_text="Flock from which birds are sold",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bird_sales",
                        to="flock_management.flock",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bird_purchases",
                        to="sales_revenue.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-sale_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EggSale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sale_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("crate", "Crate (30 eggs)"),
                            ("piece", "Individual Eggs"),
                        ],
                        default="crate",
                        max_length=10,
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per crate or per egg",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="quantity × price_per_unit",
                        max_digits=12,
                    ),
                ),
                (
                    "platform_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Platform commission (percentage-based)",
                        max_digits=10,
                    ),
                ),
                (
                    "paystack_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Paystack transaction fee (paid by platform)",
                        max_digits=10,
                    ),
                ),
                (
                    "farmer_payout",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount to be paid to farmer (subtotal - commission)",
                        max_digits=12,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount customer pays (same as subtotal)",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("paid", "Payment Received"),
                            ("processing", "Processing Payout"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="egg_purchases",
                        to="sales_revenue.customer",
                    ),
                ),
                (
                    "daily_production",
                    models.ForeignKey(
                        help_text="Link to the production record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="egg_sales",
                        to="flock_management.dailyproduction",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="egg_sales",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-sale_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FarmerPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "paystack_transfer_code",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("paystack_transfer_id", models.CharField(blank=True, max_length=100)),
                ("settlement_date", models.DateTimeField(blank=True, null=True)),
                ("recipient_mobile_number", models.CharField(max_length=15)),
                ("recipient_name", models.CharField(max_length=200)),
                ("mobile_money_provider", models.CharField(max_length=20)),
                ("retry_count", models.IntegerField(default=0)),
                ("last_retry_at", models.DateTimeField(blank=True, null=True)),
                ("previous_hash", models.CharField(blank=True, max_length=64)),
                (
                    "current_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("payout_response", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bird_sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="sales_revenue.birdsale",
                    ),
                ),
                (
                    "egg_sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="sales_revenue.eggsale",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_payouts",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Bank Transfer"),
                            ("card", "Card"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partial_refund", "Partially Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "paystack_reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("paystack_access_code", models.CharField(blank=True, max_length=100)),
                (
                    "paystack_transaction_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("last_retry_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("refund_requested", models.BooleanField(default=False)),
                ("refund_requested_at", models.DateTimeField(blank=True, null=True)),
                ("refund_reason", models.TextField(blank=True)),
                (
                    "refunded_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_response",
                    models.JSONField(
                        blank=True, default=dict, help_text="Raw Paystack API response"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="sales_revenue.customer",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="eggsale",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="egg_sale",
                to="sales_revenue.payment",
            ),
        ),
        migrations.AddField(
            model_name="birdsale",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bird_sale",
                to="sales_revenue.payment",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["farm", "phone_number"], name="sales_reven_farm_id_5ae2a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["mobile_money_number"], name="sales_reven_mobile__736f46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["-created_at"], name="sales_reven_created_fe160f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmerpayout",
            index=models.Index(
                fields=["farm", "-created_at"], name="sales_reven_farm_id_b7c346_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmerpayout",
            index=models.Index(fields=["status"], name="sales_reven_status_b3ea4d_idx"),
        ),
        migrations.AddIndex(
            model_name="farmerpayout",
            index=models.Index(
                fields=["-created_at"], name="sales_reven_created_6520ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["farm", "-created_at"], name="sales_reven_farm_id_518912_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["customer"], name="sales_reven_custome_7d1c2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="sales_reven_status_7c300e_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["paystack_reference"], name="sales_reven_paystac_b66eb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eggsale",
            index=models.Index(
                fields=["farm", "-sale_date"], name="sales_reven_farm_id_c4e2d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eggsale",
            index=models.Index(
                fields=["customer", "-sale_date"], name="sales_reven_custome_825d01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eggsale",
            index=models.Index(fields=["status"], name="sales_reven_status_c7d148_idx"),
        ),
        migrations.AddIndex(
            model_name="eggsale",
            index=models.Index(
                fields=["-created_at"], name="sales_reven_created_e93b68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="birdsale",
            index=models.Index(
                fields=["farm", "-sale_date"], name="sales_reven_farm_id_36b4f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="birdsale",
            index=models.Index(
                fields=["customer", "-sale_date"], name="sales_reven_custome_3b434c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="birdsale",
            index=models.Index(fields=["flock"], name="sales_reven_flock_i_c1bcae_idx"),
        ),
        migrations.AddIndex(
            model_name="birdsale",
            index=models.Index(fields=["status"], name="sales_reven_status_04c193_idx"),
        ),
    ]
