# Generated by Django 5.2.7 on 2025-10-26 13:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_revenue", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "commission_tier_1_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Commission for sales < GHS 100 (in percentage)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "commission_tier_1_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Maximum amount for Tier 1 (GHS)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "commission_tier_2_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=3.0,
                        help_text="Commission for sales GHS 100-500 (in percentage)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "commission_tier_2_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=500.0,
                        help_text="Maximum amount for Tier 2 (GHS)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "commission_tier_3_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="Commission for sales > GHS 500 (in percentage)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "commission_minimum_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="Minimum commission per transaction (GHS)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "paystack_fee_bearer",
                    models.CharField(
                        choices=[
                            ("account", "Platform Pays Fees"),
                            ("subaccount", "Farmer Pays Fees"),
                        ],
                        default="account",
                        help_text="Who pays Paystack transaction fees",
                        max_length=20,
                    ),
                ),
                (
                    "paystack_settlement_schedule",
                    models.CharField(
                        choices=[
                            ("auto", "Auto (24 hours)"),
                            ("instant", "Instant (2 minutes)"),
                        ],
                        default="auto",
                        help_text="How quickly farmers receive settlements",
                        max_length=20,
                    ),
                ),
                (
                    "payment_retry_max_attempts",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum payment retry attempts",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "payment_retry_delay_seconds",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="Delay between retry attempts (seconds)",
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(3600),
                        ],
                    ),
                ),
                (
                    "refund_eligibility_hours",
                    models.PositiveIntegerField(
                        default=48,
                        help_text="Hours within which customers can request refunds",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                (
                    "payment_auto_refund_hours",
                    models.PositiveIntegerField(
                        default=72,
                        help_text="Hours after which failed payments are auto-refunded",
                        validators=[
                            django.core.validators.MinValueValidator(24),
                            django.core.validators.MaxValueValidator(336),
                        ],
                    ),
                ),
                (
                    "enable_instant_settlements",
                    models.BooleanField(
                        default=False,
                        help_text="Allow instant settlements (with extra fee)",
                    ),
                ),
                (
                    "enable_refunds",
                    models.BooleanField(
                        default=True, help_text="Allow customer refund requests"
                    ),
                ),
                (
                    "enable_auto_refunds",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically refund failed payments after timeout",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about setting changes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_settings_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Settings",
                "verbose_name_plural": "Platform Settings",
                "db_table": "platform_settings",
            },
        ),
    ]
