# Generated by Django 5.1.3 on 2026-01-01 12:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0013_convert_housing_to_accommodation"),
        ("sales_revenue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon class name", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
                "db_table": "marketplace_product_categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("ready", "Ready for Pickup/Delivery"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("partial", "Partially Paid"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("pickup", "Farm Pickup"), ("delivery", "Delivery")],
                        default="pickup",
                        max_length=20,
                    ),
                ),
                ("delivery_address", models.TextField(blank=True)),
                ("delivery_notes", models.TextField(blank=True)),
                ("estimated_delivery_date", models.DateField(blank=True, null=True)),
                ("actual_delivery_date", models.DateTimeField(blank=True, null=True)),
                ("customer_notes", models.TextField(blank=True)),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not visible to customer)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_orders",
                        to="sales_revenue.customer",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="The farm that receives this order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_orders",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceStatistics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("completed_orders", models.PositiveIntegerField(default=0)),
                ("cancelled_orders", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_items_sold", models.PositiveIntegerField(default=0)),
                ("new_customers", models.PositiveIntegerField(default=0)),
                ("returning_customers", models.PositiveIntegerField(default=0)),
                ("products_listed", models.PositiveIntegerField(default=0)),
                ("products_out_of_stock", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_statistics",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_statistics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Stock Keeping Unit - unique per farm",
                        max_length=50,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "Piece"),
                            ("crate", "Crate (30 eggs)"),
                            ("tray", "Tray"),
                            ("kg", "Kilogram"),
                            ("bird", "Bird"),
                            ("dozen", "Dozen"),
                            ("bag", "Bag"),
                        ],
                        default="piece",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original price for showing discounts",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=10, help_text="Alert when stock falls below this level"
                    ),
                ),
                ("track_inventory", models.BooleanField(default=True)),
                ("allow_backorder", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("out_of_stock", "Out of Stock"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("min_order_quantity", models.PositiveIntegerField(default=1)),
                (
                    "max_order_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum quantity per order (blank for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "primary_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="marketplace/products/"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("specifications", models.JSONField(blank=True, default=dict)),
                ("total_sold", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="The farm that owns this product listing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_products",
                        to="farms.farm",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="sales_revenue.productcategory",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("product_sku", models.CharField(blank=True, max_length=50)),
                ("unit", models.CharField(max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fulfilled_quantity", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales_revenue.marketplaceorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="sales_revenue.product",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_order_items",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="marketplace/products/")),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="sales_revenue.product",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_product_images",
                "ordering": ["display_order"],
            },
        ),
        migrations.AddIndex(
            model_name="marketplaceorder",
            index=models.Index(
                fields=["farm", "-created_at"], name="marketplace_farm_id_864a27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplaceorder",
            index=models.Index(
                fields=["farm", "status"], name="marketplace_farm_id_bdc7f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplaceorder",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="marketplace_custome_de13fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketplaceorder",
            index=models.Index(
                fields=["order_number"], name="marketplace_order_n_eeddd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacestatistics",
            index=models.Index(
                fields=["farm", "-date"], name="marketplace_farm_id_9b8ee8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketplacestatistics",
            unique_together={("farm", "date")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["farm", "status"], name="marketplace_farm_id_51ac3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "status"], name="marketplace_categor_82c049_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["farm", "-created_at"], name="marketplace_farm_id_ea2a46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "is_featured"], name="marketplace_status_5773dc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("sku__isnull", False), models.Q(("sku", ""), _negated=True)
                ),
                fields=("farm", "sku"),
                name="unique_sku_per_farm",
            ),
        ),
    ]
