# Generated by Django 5.2.7 on 2025-10-26 13:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0002_farm_paystack_settlement_account_and_more"),
        ("sales_revenue", "0002_platformsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "risk_score",
                    models.IntegerField(
                        default=0,
                        help_text="Calculated risk score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("CLEAN", "Clean (No Issues)"),
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "alerts",
                    models.JSONField(
                        default=list, help_text="List of specific alerts detected"
                    ),
                ),
                ("analysis_period_days", models.IntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("under_review", "Under Review"),
                            ("false_positive", "False Positive"),
                            ("confirmed", "Confirmed Fraud"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "action_taken",
                    models.TextField(
                        blank=True, help_text="Actions taken in response to this alert"
                    ),
                ),
                ("audit_scheduled", models.BooleanField(default=False)),
                ("audit_date", models.DateField(blank=True, null=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_alerts",
                        to="farms.farm",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_fraud_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fraud_alerts",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["farm", "-detected_at"],
                        name="fraud_alert_farm_id_130e84_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "status"],
                        name="fraud_alert_risk_le_1234c8_idx",
                    ),
                    models.Index(
                        fields=["-detected_at"], name="fraud_alert_detecte_c43b47_idx"
                    ),
                ],
            },
        ),
    ]
