# Generated by Django 5.1.3 on 2026-01-01 12:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_revenue", "0002_marketplace_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceorder",
            name="delivery_contact_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="delivery_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="delivery_gps_coordinates",
            field=models.CharField(
                blank=True, help_text="GPS coordinates (lat,lng)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="farmer_delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fee charged by farmer for delivery",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="farmer_delivery_radius_km",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum delivery distance in kilometers",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="negotiated_price_applied",
            field=models.BooleanField(
                default=False, help_text="Whether a negotiated price was agreed upon"
            ),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="negotiation_notes",
            field=models.TextField(
                blank=True, help_text="Notes about price negotiation"
            ),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="pickup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="pickup_time_slot",
            field=models.CharField(
                blank=True, help_text='e.g., "9:00 AM - 12:00 PM"', max_length=50
            ),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="third_party_delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="third_party_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bolt", "Bolt"),
                    ("uber", "Uber"),
                    ("glovo", "Glovo"),
                    ("yango", "Yango"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="third_party_tracking_id",
            field=models.CharField(
                blank=True,
                help_text="Tracking ID from delivery provider",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="min_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum acceptable price (only visible to farmer)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_negotiable",
            field=models.BooleanField(
                default=False, help_text="Allow customers to negotiate price"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_notes",
            field=models.CharField(
                blank=True,
                help_text='Public notes about pricing (e.g., "Bulk discounts available")',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="marketplaceorder",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("pickup", "Farm Pickup"),
                    ("farmer_delivery", "Farmer Delivers"),
                    ("third_party", "Third-Party Delivery"),
                ],
                default="pickup",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Asking price (or fixed price if not negotiable)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
