# Generated by Django 5.1.3 on 2026-01-01 12:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0013_convert_housing_to_accommodation"),
        (
            "flock_management",
            "0015_rename_health_reco_farm_id_27b62f_idx_health_reco_farm_id_bf0557_idx_and_more",
        ),
        ("sales_revenue", "0003_marketplace_negotiable_pricing_delivery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("eggs", "Eggs"),
                            ("birds", "Live Birds"),
                            ("processed", "Processed Products"),
                            ("chicks", "Day Old Chicks"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text='Descriptive name (e.g., "Fresh Eggs - Grade A", "Broilers 6-8 weeks")',
                        max_length=200,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Stock Keeping Unit for tracking",
                        max_length=50,
                    ),
                ),
                (
                    "quantity_available",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current quantity available for sale",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "Piece"),
                            ("crate", "Crate (30 eggs)"),
                            ("tray", "Tray (30 eggs)"),
                            ("dozen", "Dozen"),
                            ("kg", "Kilogram"),
                            ("bird", "Bird"),
                        ],
                        default="piece",
                        max_length=20,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average cost per unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total inventory value",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        help_text="Alert when stock falls below",
                        max_digits=10,
                    ),
                ),
                ("is_low_stock", models.BooleanField(default=False)),
                (
                    "oldest_stock_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of oldest unsold stock (for eggs: freshness tracking)",
                        null=True,
                    ),
                ),
                (
                    "average_age_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Average age of current stock in days"
                    ),
                ),
                (
                    "max_shelf_life_days",
                    models.PositiveIntegerField(
                        default=21,
                        help_text="Maximum days before stock expires (21 for eggs)",
                    ),
                ),
                (
                    "total_added",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total quantity ever added",
                        max_digits=14,
                    ),
                ),
                (
                    "total_sold",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total quantity ever sold",
                        max_digits=14,
                    ),
                ),
                (
                    "total_lost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total quantity lost (spoilage, breakage, etc.)",
                        max_digits=14,
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total revenue from sales",
                        max_digits=14,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_stock_update", models.DateTimeField(blank=True, null=True)),
                ("last_sale_date", models.DateTimeField(blank=True, null=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="farms.farm",
                    ),
                ),
                (
                    "marketplace_product",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked marketplace listing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_record",
                        to="sales_revenue.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Inventory",
                "verbose_name_plural": "Farm Inventories",
                "db_table": "farm_inventory",
                "ordering": ["farm", "category", "product_name"],
            },
        ),
        migrations.CreateModel(
            name="BirdsReadyForMarket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_ready",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date birds were marked as ready for market",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Number of birds ready for market",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "bird_type",
                    models.CharField(
                        choices=[
                            ("broiler", "Broiler"),
                            ("layer", "Layer"),
                            ("spent_hen", "Spent Hen"),
                            ("cockerel", "Cockerel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "average_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average weight per bird in kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "estimated_price_per_bird",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Expected selling price per bird",
                        max_digits=10,
                    ),
                ),
                (
                    "total_estimated_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("quantity_sold", models.PositiveIntegerField(default=0)),
                ("quantity_remaining", models.PositiveIntegerField(default=0)),
                ("is_fully_sold", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birds_ready_for_market",
                        to="farms.farm",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_ready_records",
                        to="flock_management.flock",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="birds_ready_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bird_ready_records",
                        to="sales_revenue.farminventory",
                    ),
                ),
            ],
            options={
                "db_table": "birds_ready_for_market",
                "ordering": ["-date_ready"],
            },
        ),
        migrations.CreateModel(
            name="FarmInventoryAnalytics",
            fields=[],
            options={
                "verbose_name": "Inventory Analytics",
                "verbose_name_plural": "Inventory Analytics",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sales_revenue.farminventory",),
        ),
        migrations.CreateModel(
            name="InventoryBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        help_text="Auto-generated batch identifier", max_length=50
                    ),
                ),
                (
                    "initial_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "production_date",
                    models.DateField(
                        help_text="Date the items were produced/collected"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Calculated expiry date", null=True
                    ),
                ),
                (
                    "is_depleted",
                    models.BooleanField(
                        default=False,
                        help_text="True when all items have been sold/used",
                    ),
                ),
                (
                    "is_expired",
                    models.BooleanField(
                        default=False, help_text="True when batch has expired"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("depleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="sales_revenue.farminventory",
                    ),
                ),
                (
                    "source_flock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_batches",
                        to="flock_management.flock",
                    ),
                ),
                (
                    "source_production",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_batches",
                        to="flock_management.dailyproduction",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_batches",
                "ordering": ["production_date"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("production", "Production (Eggs Collected)"),
                            ("market_ready", "Birds Ready for Market"),
                            ("purchase", "Purchased Stock"),
                            ("transfer_in", "Transfer In"),
                            ("adjustment_add", "Inventory Adjustment (Add)"),
                            ("sale", "Sold"),
                            ("spoilage", "Spoiled/Expired"),
                            ("breakage", "Breakage/Loss"),
                            ("personal_use", "Personal/Farm Use"),
                            ("transfer_out", "Transfer Out"),
                            ("adjustment_remove", "Inventory Adjustment (Remove)"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive for additions, negative for removals",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost/price per unit at time of movement",
                        max_digits=10,
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Stock balance after this movement",
                        max_digits=12,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        help_text="Model name of source record (DailyProduction, EggSale, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        help_text="UUID of source record",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "stock_date",
                    models.DateField(help_text="Date the stock was produced/received"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="farms.farm",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="sales_revenue.farminventory",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stock_movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="farminventory",
            index=models.Index(
                fields=["farm", "category"], name="farm_invent_farm_id_50a5f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farminventory",
            index=models.Index(
                fields=["farm", "is_low_stock"], name="farm_invent_farm_id_0902da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farminventory",
            index=models.Index(
                fields=["category", "quantity_available"],
                name="farm_invent_categor_33c960_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="farminventory",
            index=models.Index(
                fields=["oldest_stock_date"], name="farm_invent_oldest__0370a4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="farminventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sku", ""), _negated=True),
                fields=("farm", "category", "sku"),
                name="unique_inventory_sku_per_farm",
            ),
        ),
        migrations.AddIndex(
            model_name="birdsreadyformarket",
            index=models.Index(
                fields=["farm", "-date_ready"], name="birds_ready_farm_id_12ddc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="birdsreadyformarket",
            index=models.Index(
                fields=["flock", "-date_ready"], name="birds_ready_flock_i_01e91b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="birdsreadyformarket",
            index=models.Index(
                fields=["is_fully_sold"], name="birds_ready_is_full_563673_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorybatch",
            index=models.Index(
                fields=["inventory", "is_depleted"],
                name="inventory_b_invento_8607a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorybatch",
            index=models.Index(
                fields=["production_date"], name="inventory_b_product_00920c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorybatch",
            index=models.Index(
                fields=["expiry_date"], name="inventory_b_expiry__d9a11e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["inventory", "-created_at"],
                name="stock_movem_invento_93e886_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["farm", "-created_at"], name="stock_movem_farm_id_414521_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type", "-created_at"],
                name="stock_movem_movemen_829843_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["source_type", "source_id"],
                name="stock_movem_source__868de0_idx",
            ),
        ),
    ]
