# Generated by Django 5.1.3 on 2026-01-01 14:01

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0013_convert_housing_to_accommodation"),
        (
            "flock_management",
            "0015_rename_health_reco_farm_id_27b62f_idx_health_reco_farm_id_bf0557_idx_and_more",
        ),
        ("sales_revenue", "0004_inventory_tracking_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("production", "Production (Eggs Collected)"),
                    ("market_ready", "Birds Ready for Market"),
                    ("purchase", "Purchased Stock"),
                    ("transfer_in", "Transfer In"),
                    ("adjustment_add", "Inventory Adjustment (Add)"),
                    ("processing", "From Processing Batch"),
                    ("sale", "Sold"),
                    ("spoilage", "Spoiled/Expired"),
                    ("breakage", "Breakage/Loss"),
                    ("personal_use", "Personal/Farm Use"),
                    ("transfer_out", "Transfer Out"),
                    ("adjustment_remove", "Inventory Adjustment (Remove)"),
                    ("sent_to_processing", "Sent to Processing"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ProcessingBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this processing batch",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "birds_processed",
                    models.PositiveIntegerField(
                        help_text="Number of birds processed in this batch",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "processing_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when processing occurred",
                    ),
                ),
                (
                    "processing_type",
                    models.CharField(
                        choices=[
                            ("slaughter", "Slaughter & Dressing"),
                            ("portioning", "Portioning"),
                            ("packaging", "Packaging"),
                            ("smoking", "Smoking"),
                            ("freezing", "Freezing"),
                            ("mixed", "Mixed Processing"),
                        ],
                        default="slaughter",
                        max_length=20,
                    ),
                ),
                (
                    "bird_cost_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost per bird (auto-calculated from flock if not provided)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Labor cost for this processing batch",
                        max_digits=10,
                    ),
                ),
                (
                    "processing_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Other processing costs (equipment, utilities, etc.)",
                        max_digits=10,
                    ),
                ),
                (
                    "packaging_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Packaging materials cost",
                        max_digits=10,
                    ),
                ),
                (
                    "birds_lost_in_processing",
                    models.PositiveIntegerField(
                        default=0, help_text="Birds lost due to processing issues"
                    ),
                ),
                (
                    "loss_reason",
                    models.TextField(blank=True, help_text="Reason for any losses"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the batch was marked as completed",
                        null=True,
                    ),
                ),
                (
                    "inventory_updated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether inventory has been updated with outputs",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this processing batch",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_batches",
                        to="farms.farm",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_batches_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_birds_ready",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link if birds came from market-ready inventory",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_batches",
                        to="sales_revenue.birdsreadyformarket",
                    ),
                ),
                (
                    "source_flock",
                    models.ForeignKey(
                        help_text="The flock from which birds were taken for processing",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_batches",
                        to="flock_management.flock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Batch",
                "verbose_name_plural": "Processing Batches",
                "ordering": ["-processing_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingOutput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("whole_bird", "Whole Dressed Bird"),
                            ("breast", "Breast"),
                            ("thigh", "Thigh"),
                            ("drumstick", "Drumstick"),
                            ("wing", "Wing"),
                            ("back", "Back"),
                            ("gizzard", "Gizzard"),
                            ("liver", "Liver"),
                            ("heart", "Heart"),
                            ("neck", "Neck"),
                            ("feet", "Feet"),
                            ("offal", "Offal/By-products"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Number of units produced",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="piece",
                        help_text="Unit of measurement (piece, kg, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "unit_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Weight per unit in kilograms",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "Grade A - Premium"),
                            ("B", "Grade B - Standard"),
                            ("C", "Grade C - Economy"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "production_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when this output was produced",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Expiry date for perishable products",
                        null=True,
                    ),
                ),
                (
                    "shelf_life_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Expected shelf life in days (used to calculate expiry if not set)",
                    ),
                ),
                (
                    "allocated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Portion of batch cost allocated to this output",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cost_allocation_method",
                    models.CharField(
                        choices=[
                            ("weight", "By Weight"),
                            ("quantity", "By Quantity"),
                            ("manual", "Manual Entry"),
                        ],
                        default="quantity",
                        max_length=20,
                    ),
                ),
                (
                    "inventory_updated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this output has been added to inventory",
                    ),
                ),
                ("inventory_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marketplace_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to marketplace product for selling",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_outputs",
                        to="sales_revenue.product",
                    ),
                ),
                (
                    "processing_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="sales_revenue.processingbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Output",
                "verbose_name_plural": "Processing Outputs",
                "ordering": ["product_category", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingOutputAnalytics",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sales_revenue.processingoutput",),
            managers=[
                ("analytics", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="processingbatch",
            index=models.Index(
                fields=["farm", "status"], name="sales_reven_farm_id_5d39d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingbatch",
            index=models.Index(
                fields=["processing_date"], name="sales_reven_process_0eb153_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingbatch",
            index=models.Index(
                fields=["source_flock"], name="sales_reven_source__ffe994_idx"
            ),
        ),
    ]
