# Generated by Django 5.1.3 on 2026-01-01 14:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_revenue", "0005_processing_batch_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingbatch",
            name="actual_yield_weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual total weight of all products produced in kg",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="processingbatch",
            name="average_bird_weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Average weight per bird in kg (e.g., 4.0 kg)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="processingbatch",
            name="expected_yield_weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Expected total yield in kg (birds_processed × average_bird_weight_kg)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="processingoutput",
            name="weight_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total weight of this product output in kilograms (PRIMARY UNIT)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="processingoutput",
            name="quantity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional: Number of pieces/units (for reference only, not primary tracking)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="processingoutput",
            name="unit",
            field=models.CharField(
                default="kg",
                help_text="Unit of measurement (kg is default for processed products)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="processingoutput",
            name="unit_weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Weight per piece in kg (if tracking pieces: weight_kg = quantity × unit_weight_kg)",
                max_digits=6,
                null=True,
            ),
        ),
    ]
