# Generated by Django 5.2.7 on 2026-01-02 17:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0013_convert_housing_to_accommodation"),
        ("sales_revenue", "0006_weight_based_processing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="birdsale",
            name="sale_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="eggsale",
            name="sale_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="processingbatch",
            name="processing_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Date when processing occurred",
            ),
        ),
        migrations.AlterField(
            model_name="processingoutput",
            name="production_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Date when this output was produced",
            ),
        ),
        migrations.CreateModel(
            name="GuestCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Ghana phone number (e.g., 0241234567 or +233241234567)",
                                regex="^\\+?233\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("phone_verified", models.BooleanField(default=False)),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("completed_orders", models.PositiveIntegerField(default=0)),
                ("cancelled_orders", models.PositiveIntegerField(default=0)),
                ("is_blocked", models.BooleanField(default=False)),
                ("blocked_reason", models.TextField(blank=True)),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_order_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "guest_customers",
                "indexes": [
                    models.Index(
                        fields=["phone_number"], name="guest_custo_phone_n_8252fd_idx"
                    ),
                    models.Index(
                        fields=["phone_verified"], name="guest_custo_phone_v_2ce9ea_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GuestOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "Pending Phone Verification"),
                            ("pending_confirmation", "Awaiting Farmer Confirmation"),
                            ("confirmed", "Confirmed - Awaiting Payment"),
                            ("payment_confirmed", "Payment Confirmed"),
                            ("processing", "Processing"),
                            ("ready", "Ready for Pickup/Delivery"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending_verification",
                        max_length=25,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("pickup", "Farm Pickup"), ("delivery", "Delivery")],
                        default="pickup",
                        max_length=20,
                    ),
                ),
                ("delivery_address", models.TextField(blank=True)),
                (
                    "delivery_gps",
                    models.CharField(
                        blank=True, help_text="GPS coordinates", max_length=50
                    ),
                ),
                ("preferred_date", models.DateField(blank=True, null=True)),
                (
                    "preferred_time",
                    models.CharField(
                        blank=True, help_text="e.g., Morning, Afternoon", max_length=50
                    ),
                ),
                ("customer_notes", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_method_used",
                    models.CharField(
                        blank=True,
                        help_text="How customer paid (e.g., MoMo, Cash, Bank Transfer)",
                        max_length=50,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference from payment (e.g., MoMo transaction ID)",
                        max_length=100,
                    ),
                ),
                ("payment_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("farmer_notes", models.TextField(blank=True)),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer_request", "Customer Requested"),
                            ("farmer_unavailable", "Product Unavailable"),
                            ("payment_timeout", "Payment Timeout"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("cancellation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Order expires if not confirmed by this time",
                        null=True,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_orders",
                        to="farms.farm",
                    ),
                ),
                (
                    "guest_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="sales_revenue.guestcustomer",
                    ),
                ),
                (
                    "payment_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_guest_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "guest_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("product_sku", models.CharField(blank=True, max_length=50)),
                ("unit", models.CharField(max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales_revenue.guestorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_order_items",
                        to="sales_revenue.product",
                    ),
                ),
            ],
            options={
                "db_table": "guest_order_items",
            },
        ),
        migrations.CreateModel(
            name="GuestOrderOTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=15)),
                ("code", models.CharField(max_length=6)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "guest_order_otps",
                "indexes": [
                    models.Index(
                        fields=["phone_number", "code"],
                        name="guest_order_phone_n_500388_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="guest_order_expires_313016_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GuestOrderRateLimit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=15)),
                ("date", models.DateField(db_index=True)),
                ("order_count", models.PositiveIntegerField(default=0)),
                ("otp_requests", models.PositiveIntegerField(default=0)),
                ("failed_otps", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "guest_order_rate_limits",
                "unique_together": {("phone_number", "date")},
            },
        ),
        migrations.CreateModel(
            name="POSSale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sale_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                ("customer_phone", models.CharField(blank=True, max_length=15)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("momo_mtn", "MTN Mobile Money"),
                            ("momo_voda", "Vodafone Cash"),
                            ("momo_tigo", "AirtelTigo Money"),
                            ("bank_transfer", "Bank Transfer"),
                            ("credit", "On Credit"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID for mobile money payments",
                        max_length=100,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "amount_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount actually received (for credit sales, this may be 0)",
                        max_digits=12,
                    ),
                ),
                ("is_credit_sale", models.BooleanField(default=False)),
                ("credit_due_date", models.DateField(blank=True, null=True)),
                ("credit_paid", models.BooleanField(default=False)),
                ("credit_paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sale_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_sales",
                        to="sales_revenue.customer",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos_sales",
                        to="farms.farm",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_pos_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pos_sales",
                "ordering": ["-sale_date"],
            },
        ),
        migrations.CreateModel(
            name="POSSaleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("unit", models.CharField(max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_sale_items",
                        to="sales_revenue.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales_revenue.possale",
                    ),
                ),
            ],
            options={
                "db_table": "pos_sale_items",
            },
        ),
        migrations.AddIndex(
            model_name="guestorder",
            index=models.Index(
                fields=["farm", "-created_at"], name="guest_order_farm_id_771e12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestorder",
            index=models.Index(
                fields=["farm", "status"], name="guest_order_farm_id_12748d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestorder",
            index=models.Index(
                fields=["guest_customer", "-created_at"],
                name="guest_order_guest_c_231737_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guestorder",
            index=models.Index(
                fields=["order_number"], name="guest_order_order_n_f9247d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestorder",
            index=models.Index(
                fields=["status", "expires_at"], name="guest_order_status_79f940_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="possale",
            index=models.Index(
                fields=["farm", "-sale_date"], name="pos_sales_farm_id_12a6db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="possale",
            index=models.Index(
                fields=["farm", "is_credit_sale"], name="pos_sales_farm_id_6bc578_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="possale",
            index=models.Index(
                fields=["sale_number"], name="pos_sales_sale_nu_379734_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="possale",
            index=models.Index(
                fields=["recorded_by", "-sale_date"],
                name="pos_sales_recorde_120f25_idx",
            ),
        ),
    ]
