# Generated by Django 5.2.7 on 2026-01-03 12:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_revenue", "0007_guest_orders_and_pos"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="enable_ads",
            field=models.BooleanField(
                default=True, help_text="Enable Google AdSense ads on platform"
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="enable_government_subsidy",
            field=models.BooleanField(
                default=False,
                help_text="Allow government-subsidized marketplace access for enrolled farmers",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="enable_transaction_commission",
            field=models.BooleanField(
                default=False,
                help_text="Enable commission on completed marketplace sales (Phase 2)",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="enable_verified_seller_tier",
            field=models.BooleanField(
                default=False,
                help_text="Enable verified/priority seller tier (Phase 2)",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="free_tier_can_access_education",
            field=models.BooleanField(
                default=True, help_text="Free users can access educational content"
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="free_tier_can_view_marketplace",
            field=models.BooleanField(
                default=True,
                help_text="Free users can view marketplace listings (without contact info)",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="free_tier_can_view_prices",
            field=models.BooleanField(
                default=True, help_text="Free users can view market price dashboards"
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="government_subsidy_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100.00"),
                help_text="Percentage of marketplace fee covered by government (0-100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="marketplace_activation_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20.00"),
                help_text="Monthly marketplace activation fee (GHS). Default: 20.00",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="marketplace_grace_period_days",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Grace period after payment due before suspension (days)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="marketplace_trial_days",
            field=models.PositiveIntegerField(
                default=14,
                help_text="Free trial period for new marketplace sellers (days)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="verified_seller_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Monthly fee for verified/priority seller status (GHS)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
