# Generated by Django 5.1.3 on 2026-01-03 13:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_revenue", "0008_add_marketplace_monetization_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformsettings",
            name="marketplace_activation_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Monthly marketplace activation fee (GHS). Default: 50.00",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
