# Generated by Django 5.1.3 on 2026-01-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_revenue", "0009_alter_platformsettings_marketplace_activation_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="adsense_connected_at",
            field=models.DateTimeField(
                blank=True, help_text="When AdSense was connected", null=True
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="adsense_oauth_token",
            field=models.JSONField(
                blank=True,
                help_text="Google AdSense OAuth token (encrypted in production)",
                null=True,
            ),
        ),
    ]
