# Generated by Django 5.2.7 on 2026-01-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_revenue", "0010_add_adsense_oauth_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="platformsettings",
            name="enable_verified_seller_tier",
        ),
        migrations.RemoveField(
            model_name="platformsettings",
            name="verified_seller_fee",
        ),
        migrations.AlterField(
            model_name="platformsettings",
            name="enable_transaction_commission",
            field=models.BooleanField(
                default=False,
                help_text="Enable commission on completed marketplace sales. SUSPENDED: Payments happen off-platform, farmers only record sales here.",
            ),
        ),
    ]
