# Generated by Django 5.1.3 on 2026-01-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_revenue", "0011_remove_verified_seller_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestorder",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("pickup", "Farm Pickup"),
                    ("farmer_delivery", "Farmer Delivers"),
                    ("third_party", "Third-Party Delivery"),
                ],
                default="pickup",
                max_length=20,
            ),
        ),
    ]
