# Generated by Django 5.1.3 on 2026-01-14 09:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_revenue", "0012_update_guest_order_delivery_methods"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("production", "Production (Eggs Collected)"),
                    ("market_ready", "Birds Ready for Market"),
                    ("purchase", "Purchased Stock"),
                    ("transfer_in", "Transfer In"),
                    ("adjustment_add", "Inventory Adjustment (Add)"),
                    ("processing", "From Processing Batch"),
                    ("return", "Customer Return"),
                    ("sale", "Sold"),
                    ("spoilage", "Spoiled/Expired"),
                    ("breakage", "Breakage/Loss"),
                    ("personal_use", "Personal/Farm Use"),
                    ("transfer_out", "Transfer Out"),
                    ("adjustment_remove", "Inventory Adjustment (Remove)"),
                    ("sent_to_processing", "Sent to Processing"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "return_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("items_received", "Items Received"),
                            ("refund_issued", "Refund Issued"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("defective", "Defective/Damaged Product"),
                            ("wrong_item", "Wrong Item Delivered"),
                            ("not_as_described", "Not As Described"),
                            ("quality_issue", "Quality Issue"),
                            ("expired", "Expired/Near Expiry"),
                            ("changed_mind", "Changed Mind"),
                            ("duplicate", "Duplicate Order"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "detailed_reason",
                    models.TextField(help_text="Detailed explanation from customer"),
                ),
                ("total_items", models.PositiveIntegerField(default=0)),
                (
                    "total_refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount to be refunded",
                        max_digits=12,
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        choices=[
                            ("original_payment", "Original Payment Method"),
                            ("store_credit", "Store Credit"),
                            ("exchange", "Exchange for Another Product"),
                            ("cash", "Cash"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        default="original_payment",
                        max_length=30,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Farmer notes about the return decision"
                    ),
                ),
                ("items_received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "items_condition",
                    models.TextField(
                        blank=True, help_text="Condition of returned items upon receipt"
                    ),
                ),
                ("refund_issued_at", models.DateTimeField(blank=True, null=True)),
                ("refund_transaction_id", models.CharField(blank=True, max_length=100)),
                ("refund_notes", models.TextField(blank=True)),
                (
                    "return_quality_acceptable",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether returned items can be restocked",
                        null=True,
                    ),
                ),
                (
                    "restocking_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fee deducted from refund for restocking",
                        max_digits=10,
                    ),
                ),
                (
                    "customer_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="URLs of images uploaded by customer",
                    ),
                ),
                (
                    "farmer_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="URLs of images taken by farmer upon receipt",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="sales_revenue.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="sales_revenue.marketplaceorder",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "return_requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("product_sku", models.CharField(blank=True, max_length=50)),
                ("unit", models.CharField(max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantity being returned",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount to refund for this item",
                        max_digits=12,
                    ),
                ),
                (
                    "item_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("defective", "Defective/Damaged Product"),
                            ("wrong_item", "Wrong Item Delivered"),
                            ("not_as_described", "Not As Described"),
                            ("quality_issue", "Quality Issue"),
                            ("expired", "Expired/Near Expiry"),
                            ("changed_mind", "Changed Mind"),
                            ("duplicate", "Duplicate Order"),
                            ("other", "Other"),
                        ],
                        help_text="Reason specific to this item (optional)",
                        max_length=30,
                    ),
                ),
                ("item_notes", models.TextField(blank=True)),
                (
                    "returned_in_good_condition",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether this item was returned in saleable condition",
                        null=True,
                    ),
                ),
                (
                    "stock_restored",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item has been added back to inventory",
                    ),
                ),
                ("stock_restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stock_movement_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Reference to StockMovement record",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="sales_revenue.orderitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_items",
                        to="sales_revenue.product",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_items",
                        to="sales_revenue.returnrequest",
                    ),
                ),
            ],
            options={
                "db_table": "return_items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("refund_method", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Paystack, MTN MoMo, Cash",
                        max_length=50,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_transactions",
                        to="sales_revenue.returnrequest",
                    ),
                ),
            ],
            options={
                "db_table": "refund_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["order", "-requested_at"], name="return_requ_order_i_6103ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["customer", "-requested_at"],
                name="return_requ_custome_a31c56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["status", "-requested_at"], name="return_requ_status_c8cdb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["return_number"], name="return_requ_return__517635_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refundtransaction",
            index=models.Index(
                fields=["return_request", "-created_at"],
                name="refund_tran_return__a53886_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="refundtransaction",
            index=models.Index(
                fields=["status", "-created_at"], name="refund_tran_status_869894_idx"
            ),
        ),
    ]
