# Generated by Django 5.2.7 on 2026-01-15 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sales_revenue",
            "0013_alter_stockmovement_movement_type_returnrequest_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        db_index=True,
                        help_text="e.g., approve_return, reject_return, issue_refund, restore_stock",
                        max_length=50,
                    ),
                ),
                ("previous_state", models.JSONField(blank=True, default=dict)),
                ("new_state", models.JSONField(blank=True, default=dict)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "return_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="sales_revenue.returnrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "return_audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["return_request", "-created_at"],
                        name="return_audi_return__ed1b34_idx",
                    ),
                    models.Index(
                        fields=["operation", "-created_at"],
                        name="return_audi_operati_226bec_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="return_audi_user_id_461a6f_idx",
                    ),
                ],
            },
        ),
    ]
