# Generated by Django 5.2.7 on 2026-01-16 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0016_distress_tracking_fields"),
        ("sales_revenue", "0014_returns_audit_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="possale",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="Client-provided key to prevent duplicate submissions",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="possale",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("farm", "idempotency_key"),
                name="unique_pos_sale_idempotency_key_per_farm",
            ),
        ),
    ]
