# Generated by Django 5.2.7 on 2026-01-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_revenue", "0016_add_guest_order_idempotency_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestorder",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 hash of order content for duplicate detection",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="guestorder",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="Optional client-provided key for duplicate prevention",
                max_length=64,
                null=True,
            ),
        ),
    ]
