# Generated by Django 5.2.10 on 2026-01-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales_revenue", "0017_add_content_hash_for_duplicate_detection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="platformsettings",
            name="enable_government_subsidy",
        ),
        migrations.RemoveField(
            model_name="platformsettings",
            name="government_subsidy_percentage",
        ),
    ]
