# Generated by Django 5.2.7 on 2025-11-26 12:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farms", "0004_farm_approval_workflow_farm_established_since_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Subscription unlocks PUBLIC MARKETPLACE visibility and sales features"
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="Monthly subscription fee (GHS)",
                        max_digits=10,
                    ),
                ),
                (
                    "max_product_images",
                    models.PositiveIntegerField(
                        default=20, help_text="Maximum product images allowed"
                    ),
                ),
                (
                    "max_image_size_mb",
                    models.PositiveIntegerField(
                        default=5, help_text="Maximum size per image (MB)"
                    ),
                ),
                (
                    "marketplace_listing",
                    models.BooleanField(
                        default=True,
                        help_text="Can list products on public marketplace",
                    ),
                ),
                (
                    "sales_tracking",
                    models.BooleanField(
                        default=True, help_text="Can use sales tracking features"
                    ),
                ),
                (
                    "analytics_dashboard",
                    models.BooleanField(
                        default=True, help_text="Access to analytics dashboard"
                    ),
                ),
                (
                    "api_access",
                    models.BooleanField(
                        default=False,
                        help_text="API access for third-party integrations",
                    ),
                ),
                (
                    "trial_period_days",
                    models.PositiveIntegerField(
                        default=14, help_text="Free trial period in days (0 = no trial)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscription_plans",
                "ordering": ["display_order", "price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="GovernmentSubsidyProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "program_name",
                    models.CharField(
                        help_text="Name of the government program (e.g., 'YEA Poultry Module 2025')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "program_code",
                    models.CharField(
                        help_text="Short code for the program (e.g., 'YEA-2025')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Program description and objectives"),
                ),
                ("start_date", models.DateField(help_text="Program start date")),
                ("end_date", models.DateField(help_text="Program end date")),
                (
                    "subsidy_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="Percentage of subscription cost covered (100% for government programs)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "max_farmers",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of farmers covered by program (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "current_farmers_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Current number of farmers enrolled"
                    ),
                ),
                (
                    "implementing_agency",
                    models.CharField(
                        help_text="Agency implementing the program (e.g., 'Ministry of Youth and Sports')",
                        max_length=200,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether program is currently accepting new farmers",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "government_subsidy_programs",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "start_date"],
                        name="government__is_acti_2d08e8_idx",
                    ),
                    models.Index(
                        fields=["program_code"], name="government__program_556c1d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_subsidized",
                    models.BooleanField(
                        default=False,
                        help_text="True if subscription cost is subsidized by government program",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial Period"),
                            ("active", "Active"),
                            ("past_due", "Past Due (Grace Period)"),
                            ("suspended", "Suspended - Marketplace Hidden"),
                            ("cancelled", "Cancelled - Marketplace Hidden"),
                        ],
                        db_index=True,
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(help_text="Subscription start date")),
                (
                    "current_period_start",
                    models.DateField(help_text="Current billing period start"),
                ),
                (
                    "current_period_end",
                    models.DateField(help_text="Current billing period end"),
                ),
                (
                    "next_billing_date",
                    models.DateField(help_text="Next payment due date"),
                ),
                ("trial_start", models.DateField(blank=True, null=True)),
                ("trial_end", models.DateField(blank=True, null=True)),
                ("last_payment_date", models.DateField(blank=True, null=True)),
                (
                    "last_payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "grace_period_days",
                    models.PositiveIntegerField(
                        default=5, help_text="Days after due date before suspension"
                    ),
                ),
                (
                    "suspension_date",
                    models.DateField(
                        blank=True,
                        help_text="Date subscription was suspended",
                        null=True,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="Last payment reminder sent", null=True
                    ),
                ),
                (
                    "reminder_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of payment reminders sent"
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True, help_text="Automatically renew subscription"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="farms.farm",
                    ),
                ),
                (
                    "subsidy_program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Government program covering subscription costs",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subsidized_subscriptions",
                        to="subscriptions.governmentsubsidyprogram",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("card", "Card Payment"),
                            (
                                "government_subsidy",
                                "Government Subsidy (No Farmer Payment)",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Transaction reference/receipt number",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "gateway_provider",
                    models.CharField(
                        blank=True,
                        help_text="Paystack, Flutterwave, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("payment_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who verified manual payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscription_payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Format: SUB-INV-YYYY-MM-XXXXX",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("billing_period_start", models.DateField()),
                ("billing_period_end", models.DateField()),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                            (
                                "government_covered",
                                "Government Subsidy - No Payment Required",
                            ),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice",
                        to="subscriptions.subscriptionpayment",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_invoices",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.AddIndex(
            model_name="subscriptionpayment",
            index=models.Index(
                fields=["subscription", "-payment_date"],
                name="subscriptio_subscri_720f2b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionpayment",
            index=models.Index(fields=["status"], name="subscriptio_status_fd22ef_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["status", "next_billing_date"],
                name="subscriptio_status_5e41b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["farm"], name="subscriptio_farm_id_878eeb_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["is_subsidized"], name="subscriptio_is_subs_44805b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["subsidy_program"], name="subscriptio_subsidy_cbc57f_idx"
            ),
        ),
    ]
