# Generated by Django 5.1.3 on 2026-01-03 13:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="description",
            field=models.TextField(
                help_text="Marketplace activation unlocks PUBLIC MARKETPLACE visibility and sales features"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price_monthly",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Monthly marketplace activation fee (GHS)",
                max_digits=10,
            ),
        ),
    ]
