# Generated by Django 5.2.7 on 2026-01-05 11:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_alter_subscriptionplan_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="failure_reason",
            field=models.TextField(blank=True, help_text="Reason for payment failure"),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="gateway_access_code",
            field=models.CharField(
                blank=True,
                help_text="Paystack access code for authorization",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="gateway_authorization_url",
            field=models.URLField(
                blank=True, help_text="URL for payment authorization (if applicable)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="gateway_fees",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Payment gateway fees (pesewas converted to GHS)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="momo_phone",
            field=models.CharField(
                blank=True,
                help_text="Mobile money phone number used for payment",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="momo_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mtn", "MTN Mobile Money"),
                    ("vodafone", "Vodafone Cash"),
                    ("airteltigo", "AirtelTigo Money"),
                    ("telecel", "Telecel Cash"),
                ],
                help_text="Mobile money provider",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="paid_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Actual timestamp when payment was confirmed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="gateway_provider",
            field=models.CharField(
                default="paystack", help_text="Payment gateway provider", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="gateway_response",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Full gateway response for debugging",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="gateway_transaction_id",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="payment_reference",
            field=models.CharField(
                db_index=True,
                help_text="Unique payment reference (format: SUB-YYYYMMDD-XXXXXXXX)",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("send_otp", "Awaiting OTP"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("abandoned", "Abandoned"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionpayment",
            index=models.Index(
                fields=["payment_reference"], name="subscriptio_payment_02f52b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionpayment",
            index=models.Index(
                fields=["gateway_transaction_id"], name="subscriptio_gateway_22f093_idx"
            ),
        ),
    ]
