# Generated by Django 5.1.3 on 2026-01-08 12:52

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_add_paystack_payment_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionalPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("basic", "Basic - Aggregated Regional Data"),
                            ("professional", "Professional - Detailed Analytics"),
                            ("enterprise", "Enterprise - Full API Access"),
                            ("research", "Research/NGO - Academic Access"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly subscription fee (GHS)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price_annually",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual subscription fee (GHS) - typically discounted",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "requests_per_day",
                    models.PositiveIntegerField(
                        default=100, help_text="Maximum API requests per day"
                    ),
                ),
                (
                    "requests_per_month",
                    models.PositiveIntegerField(
                        default=3000, help_text="Maximum API requests per month"
                    ),
                ),
                (
                    "access_regional_aggregates",
                    models.BooleanField(
                        default=True,
                        help_text="Access to regional production aggregates",
                    ),
                ),
                (
                    "access_constituency_data",
                    models.BooleanField(
                        default=False,
                        help_text="Access to constituency-level breakdown",
                    ),
                ),
                (
                    "access_production_trends",
                    models.BooleanField(
                        default=True, help_text="Access to historical production trends"
                    ),
                ),
                (
                    "access_market_prices",
                    models.BooleanField(
                        default=True, help_text="Access to average market prices"
                    ),
                ),
                (
                    "access_mortality_data",
                    models.BooleanField(
                        default=False, help_text="Access to mortality/health statistics"
                    ),
                ),
                (
                    "access_supply_forecasts",
                    models.BooleanField(
                        default=False, help_text="Access to supply forecasting models"
                    ),
                ),
                (
                    "access_individual_farm_data",
                    models.BooleanField(
                        default=False,
                        help_text="Access to anonymized individual farm performance (Enterprise only)",
                    ),
                ),
                (
                    "max_export_records",
                    models.PositiveIntegerField(
                        default=1000, help_text="Maximum records per export request"
                    ),
                ),
                (
                    "export_formats",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        default=list,
                        help_text="Allowed export formats: json, csv, excel",
                        size=None,
                    ),
                ),
                (
                    "support_level",
                    models.CharField(
                        choices=[
                            ("email", "Email Support"),
                            ("priority", "Priority Email Support"),
                            ("dedicated", "Dedicated Account Manager"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "institutional_plans",
                "ordering": ["display_order", "price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionalSubscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("organization_name", models.CharField(max_length=200)),
                (
                    "organization_category",
                    models.CharField(
                        choices=[
                            ("bank", "Bank / Financial Institution"),
                            ("microfinance", "Microfinance Institution"),
                            ("insurance", "Insurance Provider"),
                            ("agribusiness", "Agribusiness / Aggregator"),
                            ("feed_company", "Feed / Input Supplier"),
                            ("processor", "Food Processor"),
                            ("ngo", "NGO / Development Organization"),
                            ("research", "Research Institution"),
                            ("government", "Government Agency"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Company registration number",
                        max_length=100,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_position", models.CharField(blank=True, max_length=100)),
                ("tech_contact_name", models.CharField(blank=True, max_length=100)),
                ("tech_contact_email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("trial", "Trial Period"),
                            ("active", "Active"),
                            ("past_due", "Payment Past Due"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annually", "Annually")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("subscription_start", models.DateField(blank=True, null=True)),
                ("current_period_start", models.DateField(blank=True, null=True)),
                ("current_period_end", models.DateField(blank=True, null=True)),
                ("next_billing_date", models.DateField(blank=True, null=True)),
                ("trial_start", models.DateField(blank=True, null=True)),
                ("trial_end", models.DateField(blank=True, null=True)),
                (
                    "trial_days",
                    models.PositiveIntegerField(
                        default=14, help_text="Trial period in days"
                    ),
                ),
                (
                    "preferred_regions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Regions of interest (empty = all regions)",
                        size=None,
                    ),
                ),
                (
                    "data_use_purpose",
                    models.TextField(help_text="Description of intended data use"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Organization verified by YEA admin"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes (not visible to subscriber)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscribers",
                        to="subscriptions.institutionalplan",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_institutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "institutional_subscribers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionalPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("paystack", "Paystack Online"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("invoice", "Invoice (Net 30)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("paystack_reference", models.CharField(blank=True, max_length=100)),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("invoice_date", models.DateField()),
                ("invoice_due_date", models.DateField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_institutional_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscriptions.institutionalsubscriber",
                    ),
                ),
            ],
            options={
                "db_table": "institutional_payments",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionalInquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("organization_name", models.CharField(max_length=200)),
                (
                    "organization_category",
                    models.CharField(
                        choices=[
                            ("bank", "Bank / Financial Institution"),
                            ("microfinance", "Microfinance Institution"),
                            ("insurance", "Insurance Provider"),
                            ("agribusiness", "Agribusiness / Aggregator"),
                            ("feed_company", "Feed / Input Supplier"),
                            ("processor", "Food Processor"),
                            ("ngo", "NGO / Development Organization"),
                            ("research", "Research Institution"),
                            ("government", "Government Agency"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_position", models.CharField(blank=True, max_length=100)),
                (
                    "data_use_purpose",
                    models.TextField(help_text="How they plan to use the data"),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="How they found us (referral, website, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("demo_scheduled", "Demo Scheduled"),
                            ("converted", "Converted to Subscriber"),
                            ("declined", "Declined"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("follow_up_notes", models.TextField(blank=True)),
                ("next_follow_up", models.DateField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_institutional_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interested_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="subscriptions.institutionalplan",
                    ),
                ),
                (
                    "converted_subscriber",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_inquiry",
                        to="subscriptions.institutionalsubscriber",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Institutional Inquiries",
                "db_table": "institutional_inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionalAPIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Key name (e.g., 'Production', 'Development')",
                        max_length=100,
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="First 8 chars for identification", max_length=8
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the full key", max_length=64
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_readonly",
                    models.BooleanField(
                        default=True, help_text="Read-only access (always True for now)"
                    ),
                ),
                (
                    "allowed_ips",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.GenericIPAddressField(),
                        blank=True,
                        default=list,
                        help_text="Whitelisted IP addresses (empty = all allowed)",
                        size=None,
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("total_requests", models.PositiveIntegerField(default=0)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Key expiration date (null = never expires)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_institutional_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="subscriptions.institutionalsubscriber",
                    ),
                ),
            ],
            options={
                "db_table": "institutional_api_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionalAPIUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("status_code", models.PositiveIntegerField()),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        help_text="Response time in milliseconds"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("date", models.DateField(db_index=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="subscriptions.institutionalapikey",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage_records",
                        to="subscriptions.institutionalsubscriber",
                    ),
                ),
            ],
            options={
                "db_table": "institutional_api_usage",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["subscriber", "date"],
                        name="institution_subscri_db428d_idx",
                    ),
                    models.Index(
                        fields=["api_key", "date"],
                        name="institution_api_key_836376_idx",
                    ),
                    models.Index(
                        fields=["endpoint", "date"],
                        name="institution_endpoin_8e430a_idx",
                    ),
                ],
            },
        ),
    ]
