# Generated by Django 5.2.7 on 2026-01-08 13:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_institutional_data_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionalpayment",
            name="failure_reason",
            field=models.TextField(blank=True, help_text="Reason for payment failure"),
        ),
        migrations.AddField(
            model_name="institutionalpayment",
            name="gateway_access_code",
            field=models.CharField(
                blank=True,
                help_text="Paystack access code for authorization",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="institutionalpayment",
            name="gateway_authorization_url",
            field=models.URLField(
                blank=True, help_text="URL for payment authorization (if applicable)"
            ),
        ),
        migrations.AddField(
            model_name="institutionalpayment",
            name="gateway_fees",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Payment gateway fees (pesewas converted to GHS)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="institutionalpayment",
            name="gateway_provider",
            field=models.CharField(
                blank=True,
                default="paystack",
                help_text="Payment gateway provider",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="institutionalpayment",
            name="gateway_response",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Full gateway response for debugging",
            ),
        ),
        migrations.AddField(
            model_name="institutionalpayment",
            name="gateway_transaction_id",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name="institutionalpayment",
            name="momo_phone",
            field=models.CharField(
                blank=True,
                help_text="Mobile money phone number used for payment",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="institutionalpayment",
            name="momo_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mtn", "MTN Mobile Money"),
                    ("vodafone", "Vodafone Cash"),
                    ("airteltigo", "AirtelTigo Money"),
                    ("telecel", "Telecel Cash"),
                ],
                help_text="Mobile money provider",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="institutionalpayment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="institutionalpayment",
            name="invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="institutionalpayment",
            name="invoice_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="institutionalpayment",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="institutionalpayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("mobile_money", "Mobile Money"),
                    ("paystack", "Paystack Online"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cheque", "Cheque"),
                    ("invoice", "Invoice (Net 30)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpayment",
            name="payment_reference",
            field=models.CharField(
                db_index=True,
                help_text="Unique payment reference (format: INST-YYYYMMDD-XXXXXXXX)",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpayment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
