# Generated by Django 5.2.7 on 2026-01-10 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0005_add_momo_payment_fields_to_institutional_payment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="institutionalinquiry",
            index=models.Index(
                fields=["contact_email", "created_at"],
                name="institution_contact_9d701a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="institutionalinquiry",
            index=models.Index(
                fields=["status", "created_at"], name="institution_status_51b129_idx"
            ),
        ),
    ]
