# Generated by Django 5.2.7 on 2025-10-26 11:32

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import farms.models
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_id",
                    models.CharField(
                        editable=False,
                        help_text="Format: APP-YYYY-XXXXX",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "farm_id",
                    models.CharField(
                        blank=True,
                        help_text="Format: YEA-REG-CONST-XXXX (assigned on approval)",
                        max_length=30,
                        null=True,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "date_of_birth",
                    models.DateField(validators=[farms.models.validate_age_range]),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                            ("Prefer not to say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ghana_card_number",
                    models.CharField(
                        help_text="Format: GHA-XXXXXXXXX-X",
                        max_length=20,
                        unique=True,
                        validators=[farms.models.validate_ghana_card],
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "number_of_dependents",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(50)],
                    ),
                ),
                (
                    "primary_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="GH", unique=True
                    ),
                ),
                (
                    "alternate_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region="GH"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("Phone Call", "Phone Call"),
                            ("SMS", "SMS"),
                            ("WhatsApp", "WhatsApp"),
                            ("Email", "Email"),
                        ],
                        default="Phone Call",
                        max_length=20,
                    ),
                ),
                ("residential_address", models.TextField()),
                (
                    "nok_full_name",
                    models.CharField(
                        max_length=200, verbose_name="Next of Kin Full Name"
                    ),
                ),
                (
                    "nok_relationship",
                    models.CharField(
                        max_length=100, verbose_name="Next of Kin Relationship"
                    ),
                ),
                (
                    "nok_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="GH", verbose_name="Next of Kin Phone"
                    ),
                ),
                (
                    "nok_residential_address",
                    models.TextField(blank=True, verbose_name="Next of Kin Address"),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("No Formal Education", "No Formal Education"),
                            ("Primary", "Primary"),
                            ("JHS", "JHS"),
                            ("SHS/Technical", "SHS/Technical"),
                            ("Tertiary", "Tertiary"),
                            ("Postgraduate", "Postgraduate"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "literacy_level",
                    models.CharField(
                        choices=[
                            ("Cannot Read/Write", "Cannot Read/Write"),
                            ("Can Read Only", "Can Read Only"),
                            ("Can Read & Write", "Can Read & Write"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "years_in_poultry",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "previous_training",
                    models.TextField(
                        blank=True, help_text="Previous poultry training received"
                    ),
                ),
                ("farming_full_time", models.BooleanField(default=False)),
                ("other_occupation", models.CharField(blank=True, max_length=200)),
                ("farm_name", models.CharField(max_length=200, unique=True)),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("Sole Proprietorship", "Sole Proprietorship"),
                            ("Partnership", "Partnership"),
                            ("Family Business", "Family Business"),
                            ("Cooperative", "Cooperative"),
                            ("Limited Company", "Limited Company"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tin",
                    models.CharField(
                        help_text="Tax Identification Number (MANDATORY)",
                        max_length=11,
                        unique=True,
                        validators=[farms.models.validate_tin],
                    ),
                ),
                (
                    "business_registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Strongly encouraged for procurement priority",
                        max_length=50,
                    ),
                ),
                ("business_registration_date", models.DateField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                ("account_name", models.CharField(blank=True, max_length=200)),
                (
                    "mobile_money_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MTN Mobile Money", "MTN Mobile Money"),
                            ("Vodafone Cash", "Vodafone Cash"),
                            ("AirtelTigo Money", "AirtelTigo Money"),
                            ("Telecel Cash", "Telecel Cash"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "mobile_money_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region="GH"
                    ),
                ),
                (
                    "number_of_poultry_houses",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "total_bird_capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("current_bird_count", models.PositiveIntegerField(default=0)),
                (
                    "housing_type",
                    models.CharField(
                        choices=[
                            ("Deep Litter", "Deep Litter"),
                            ("Battery Cage", "Battery Cage"),
                            ("Free Range", "Free Range"),
                            ("Semi-Intensive", "Semi-Intensive"),
                            ("Mixed", "Mixed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "total_infrastructure_value_ghs",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total value of infrastructure for ROI tracking",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "primary_production_type",
                    models.CharField(
                        choices=[
                            ("Layers", "Layers (Egg Production)"),
                            ("Broilers", "Broilers (Meat Production)"),
                            ("Both", "Both Layers and Broilers"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "layer_breed",
                    models.CharField(
                        blank=True,
                        help_text="Required if primary_production_type includes Layers",
                        max_length=100,
                    ),
                ),
                (
                    "planned_monthly_egg_production",
                    models.PositiveIntegerField(
                        blank=True, help_text="REQUIRED if Layers", null=True
                    ),
                ),
                (
                    "broiler_breed",
                    models.CharField(
                        blank=True,
                        help_text="Required if primary_production_type includes Broilers",
                        max_length=100,
                    ),
                ),
                (
                    "planned_monthly_bird_sales",
                    models.PositiveIntegerField(
                        blank=True, help_text="REQUIRED if Broilers", null=True
                    ),
                ),
                (
                    "planned_production_start_date",
                    models.DateField(
                        help_text="MANDATORY - When will commercial production begin"
                    ),
                ),
                ("hatchery_operation", models.BooleanField(default=False)),
                ("feed_formulation", models.BooleanField(default=False)),
                (
                    "initial_investment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Farmer's capital invested (MANDATORY)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000000),
                        ],
                    ),
                ),
                (
                    "funding_source",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        help_text="Multi-select: Personal Savings, Family, Loan, Grant, Other",
                        size=None,
                    ),
                ),
                (
                    "monthly_operating_budget",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated monthly expenses (MANDATORY)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                    ),
                ),
                (
                    "expected_monthly_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Revenue projection (MANDATORY)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                    ),
                ),
                ("has_outstanding_debt", models.BooleanField(default=False)),
                (
                    "debt_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Required if has_outstanding_debt = True",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000000),
                        ],
                    ),
                ),
                ("debt_purpose", models.CharField(blank=True, max_length=200)),
                (
                    "monthly_debt_payment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                    ),
                ),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Submitted", "Submitted"),
                            ("Under Review", "Under Review"),
                            ("More Info Needed", "More Info Needed"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Active", "Active"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                (
                    "farm_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Suspended", "Suspended"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("review_comments", models.TextField(blank=True)),
                ("site_visit_required", models.BooleanField(default=False)),
                ("site_visit_date", models.DateField(blank=True, null=True)),
                ("site_visit_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("more_info_requested", models.TextField(blank=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("activation_date", models.DateTimeField(blank=True, null=True)),
                ("benefit_package_assigned", models.JSONField(blank=True, null=True)),
                (
                    "farm_readiness_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-calculated based on infrastructure checklist",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "biosecurity_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Count of biosecurity measures / total × 100",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "capacity_utilization",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="(current_birds / total_capacity) × 100",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Beginner", "Beginner (0-1 years)"),
                            ("Intermediate", "Intermediate (2-5 years)"),
                            ("Expert", "Expert (5+ years)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "support_priority_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Based on needs, readiness, location",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "financial_health_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Revenue vs Expenses, Debt-to-Asset ratio",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "total_investment_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-calculated: infrastructure + equipment + initial capital",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_extension_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_farms_as_extension_officer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_farms_as_reviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "farms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("manual_feeders_count", models.PositiveIntegerField(default=0)),
                (
                    "manual_feeders_value_ghs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("automatic_feeders_count", models.PositiveIntegerField(default=0)),
                (
                    "automatic_feeders_value_ghs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("manual_drinkers_count", models.PositiveIntegerField(default=0)),
                (
                    "manual_drinkers_value_ghs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("nipple_drinkers_count", models.PositiveIntegerField(default=0)),
                (
                    "nipple_drinkers_value_ghs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("has_incubator", models.BooleanField(default=False)),
                ("incubator_capacity", models.PositiveIntegerField(default=0)),
                (
                    "incubator_value_ghs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("has_generator", models.BooleanField(default=False)),
                (
                    "generator_capacity_kva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "generator_value_ghs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("feed_storage_capacity_kg", models.PositiveIntegerField(default=0)),
                (
                    "feed_storage_value_ghs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("cold_storage_available", models.BooleanField(default=False)),
                (
                    "cold_storage_value_ghs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("weighing_scale", models.BooleanField(default=False)),
                ("egg_tray_count", models.PositiveIntegerField(default=0)),
                ("cages_count", models.PositiveIntegerField(default=0)),
                (
                    "cages_value_ghs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "db_table": "farm_equipment",
            },
        ),
        migrations.CreateModel(
            name="Biosecurity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("perimeter_fencing", models.BooleanField(default=False)),
                ("fencing_type", models.CharField(blank=True, max_length=100)),
                ("controlled_entry_points", models.BooleanField(default=False)),
                ("visitor_log_maintained", models.BooleanField(default=False)),
                ("footbath_at_entry", models.BooleanField(default=False)),
                ("disinfectant_used", models.CharField(blank=True, max_length=100)),
                ("hand_washing_facilities", models.BooleanField(default=False)),
                ("dedicated_farm_clothing", models.BooleanField(default=False)),
                ("quarantine_area", models.BooleanField(default=False)),
                ("sick_bird_isolation", models.BooleanField(default=False)),
                ("regular_vaccination", models.BooleanField(default=False)),
                ("vaccination_records_kept", models.BooleanField(default=False)),
                (
                    "manure_management_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Composting", "Composting"),
                            ("Biogas", "Biogas"),
                            ("Direct Sale", "Direct Sale"),
                            ("On-farm Use", "On-farm Use"),
                            ("No System", "No Formal System"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "dead_bird_disposal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Burial", "Burial"),
                            ("Incineration", "Incineration"),
                            ("Composting", "Composting"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rodent_control_program", models.BooleanField(default=False)),
                ("wild_bird_exclusion", models.BooleanField(default=False)),
                (
                    "biosecurity_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Count of measures / total × 100",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biosecurity",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Biosecurity",
                "db_table": "farm_biosecurity",
            },
        ),
        migrations.CreateModel(
            name="FarmDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("Ghana Card", "Ghana Card Photo"),
                            ("Passport Photo", "Passport Photo"),
                            (
                                "Farm Photo - Exterior",
                                "Farm Photo - Poultry House Exterior",
                            ),
                            (
                                "Farm Photo - Interior",
                                "Farm Photo - Poultry House Interior",
                            ),
                            ("Farm Photo - Layout", "Farm Photo - Overall Farm Layout"),
                            ("Farm Photo - Feeding", "Farm Photo - Feeding System"),
                            ("Farm Photo - Water", "Farm Photo - Water System"),
                            ("Farm Photo - Equipment", "Farm Photo - Equipment"),
                            ("Farm Photo - Storage", "Farm Photo - Storage Facilities"),
                            (
                                "Farm Photo - Biosecurity",
                                "Farm Photo - Biosecurity Measures",
                            ),
                            ("Title Deed", "Title Deed"),
                            ("Lease Agreement", "Lease Agreement"),
                            ("Chief Letter", "Letter from Chief/Family Head"),
                            ("Survey Plan", "Survey Plan"),
                            (
                                "Business Registration",
                                "Business Registration Certificate",
                            ),
                            ("Production Records", "Previous Production Records"),
                            ("Tax Clearance", "Tax Clearance Certificate"),
                            ("Other", "Other Document"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="farm_documents/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exif_gps_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "exif_gps_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_location_verified",
                    models.BooleanField(
                        default=False, help_text="EXIF GPS matches farm location"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="farms.farm",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "farm_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="FarmLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gps_address_string",
                    models.CharField(
                        help_text="From Ghana GPS app (e.g., AK-0123-4567)",
                        max_length=200,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Auto-extracted from GPS address string", srid=4326
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7, editable=False, max_digits=10
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7, editable=False, max_digits=10
                    ),
                ),
                ("region", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("constituency", models.CharField(max_length=100)),
                ("community", models.CharField(max_length=200)),
                ("nearest_landmark", models.CharField(blank=True, max_length=200)),
                (
                    "distance_from_main_road_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "road_accessibility",
                    models.CharField(
                        choices=[
                            ("All Year", "Accessible All Year"),
                            ("Dry Season Only", "Dry Season Only"),
                            ("Limited", "Limited Access"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "land_size_acres",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "land_ownership_status",
                    models.CharField(
                        choices=[
                            ("Owned", "Owned"),
                            ("Leased", "Leased"),
                            ("Family Land", "Family Land"),
                            ("Government Allocation", "Government Allocation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("lease_expiry_date", models.DateField(blank=True, null=True)),
                ("is_primary_location", models.BooleanField(default=False)),
                (
                    "gps_verified",
                    models.BooleanField(
                        default=False, help_text="GPS within Ghana boundaries verified"
                    ),
                ),
                (
                    "constituency_match_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Stated constituency matches GPS location",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "db_table": "farm_locations",
                "ordering": ["-is_primary_location", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PoultryHouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("house_number", models.CharField(max_length=50)),
                (
                    "house_type",
                    models.CharField(
                        choices=[
                            ("Deep Litter", "Deep Litter"),
                            ("Battery Cage", "Battery Cage"),
                            ("Free Range Shelter", "Free Range Shelter"),
                            ("Brooder House", "Brooder House"),
                            ("Layer House", "Layer House"),
                            ("Grower House", "Grower House"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "house_capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("current_occupancy", models.PositiveIntegerField(default=0)),
                (
                    "length_meters",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "width_meters",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "height_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "construction_material",
                    models.CharField(
                        help_text="e.g., Concrete blocks, Wood, Bamboo", max_length=100
                    ),
                ),
                (
                    "roofing_material",
                    models.CharField(
                        help_text="e.g., Aluminum sheets, Thatch", max_length=100
                    ),
                ),
                ("flooring_type", models.CharField(max_length=100)),
                (
                    "year_built",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "ventilation_system",
                    models.CharField(
                        choices=[
                            ("Natural", "Natural"),
                            ("Mechanical (Fans)", "Mechanical (Fans)"),
                            ("Both", "Both Natural and Mechanical"),
                        ],
                        max_length=50,
                    ),
                ),
                ("number_of_fans", models.PositiveIntegerField(default=0)),
                (
                    "estimated_house_value_ghs",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="For investment tracking",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poultry_houses",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "db_table": "poultry_houses",
                "ordering": ["house_number"],
            },
        ),
        migrations.CreateModel(
            name="SupportNeeds",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assessment_date", models.DateField(auto_now_add=True)),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("Initial", "Initial (At Registration)"),
                            ("Quarterly", "Quarterly Review"),
                            ("Bi-annual", "Bi-annual Review"),
                            ("Ad-hoc", "Ad-hoc (Farmer Requested)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "technical_support_needed",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Disease management, Feeding, Housing, etc.",
                        size=None,
                    ),
                ),
                (
                    "financial_support_needed",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Working capital, Equipment financing, etc.",
                        size=None,
                    ),
                ),
                ("market_access_support", models.BooleanField(default=False)),
                ("input_supply_support", models.BooleanField(default=False)),
                (
                    "overall_priority",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Medium",
                        max_length=20,
                    ),
                ),
                (
                    "major_challenges",
                    models.TextField(
                        blank=True, help_text="Open-ended challenges", max_length=1000
                    ),
                ),
                (
                    "specific_equipment_needs",
                    models.TextField(
                        blank=True,
                        help_text="What equipment is lacking",
                        max_length=500,
                    ),
                ),
                (
                    "training_interests",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Disease Management, Feed Formulation, Record Keeping, etc.",
                        size=None,
                    ),
                ),
                ("support_provided", models.TextField(blank=True)),
                ("effectiveness_notes", models.TextField(blank=True)),
                ("next_assessment_due", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_needs",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Support Needs",
                "db_table": "support_needs",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="Utilities",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "water_source",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        help_text="Multi-select: Borehole, Well, Pipe-borne, River/Stream, Rainwater",
                        size=None,
                    ),
                ),
                (
                    "water_availability",
                    models.CharField(
                        choices=[
                            ("Year-round", "Year-round"),
                            ("Seasonal", "Seasonal"),
                            ("Unreliable", "Unreliable"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "water_storage_capacity_liters",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "electricity_source",
                    models.CharField(
                        choices=[
                            ("National Grid", "National Grid"),
                            ("Solar", "Solar"),
                            ("Generator", "Generator Only"),
                            ("Hybrid", "Hybrid (Grid + Solar/Generator)"),
                            ("None", "No Electricity"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "electricity_reliability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Stable", "Stable"),
                            ("Frequent Outages", "Frequent Outages"),
                            ("Unreliable", "Unreliable"),
                        ],
                        max_length=50,
                    ),
                ),
                ("solar_panel_installed", models.BooleanField(default=False)),
                ("solar_capacity_watts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilities",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Utilities",
                "db_table": "farm_utilities",
            },
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["application_id"], name="farms_applica_f5b543_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(fields=["farm_id"], name="farms_farm_id_32570c_idx"),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["ghana_card_number"], name="farms_ghana_c_367b23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(fields=["tin"], name="farms_tin_aa234d_idx"),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["application_status"], name="farms_applica_51d68c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(fields=["farm_status"], name="farms_farm_st_1f0262_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="farmlocation",
            unique_together={("farm", "gps_address_string")},
        ),
        migrations.AlterUniqueTogether(
            name="poultryhouse",
            unique_together={("farm", "house_number")},
        ),
    ]
