# Generated by Django 5.2.7 on 2025-10-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="paystack_settlement_account",
            field=models.CharField(
                blank=True,
                help_text="Account number used for Paystack settlements",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="paystack_subaccount_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Paystack subaccount code for direct settlements",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="paystack_subaccount_id",
            field=models.CharField(
                blank=True, help_text="Paystack subaccount ID", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="subaccount_active",
            field=models.BooleanField(
                default=False, help_text="Whether Paystack subaccount is active"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="subaccount_created_at",
            field=models.DateTimeField(
                blank=True, help_text="When Paystack subaccount was created", null=True
            ),
        ),
    ]
