# Generated by Django 5.1.3 on 2025-11-27 14:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="target_constituencies",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Specific target constituencies. Leave empty if targeting entire region or national.",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="target_region",
            field=models.CharField(
                blank=True,
                help_text="Primary target region (e.g., 'Greater Accra', 'Ashanti'). Leave empty for national batches.",
                max_length=100,
                null=True,
            ),
        ),
    ]
