# Generated by Django 5.2.7 on 2025-10-26 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0002_farm_paystack_settlement_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="constituency_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="current_review_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("constituency", "Constituency Level"),
                    ("regional", "Regional Level"),
                    ("national", "National Level"),
                ],
                help_text="Current stage in approval workflow",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="final_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="regional_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="farm",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Submitted", "Submitted - Pending Assignment"),
                    ("Constituency Review", "Under Constituency Review"),
                    ("Regional Review", "Under Regional Review"),
                    ("National Review", "Under National Review"),
                    ("Changes Requested", "Changes Requested by Reviewer"),
                    ("Approved", "Approved - Farm ID Assigned"),
                    ("Rejected", "Rejected"),
                ],
                db_index=True,
                default="Draft",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="FarmApprovalQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "review_level",
                    models.CharField(
                        choices=[
                            ("constituency", "Constituency Level"),
                            ("regional", "Regional Level"),
                            ("national", "National Level"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("claimed", "Claimed by Officer"),
                            ("in_progress", "Under Review"),
                            ("completed", "Review Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "auto_assigned",
                    models.BooleanField(
                        default=False,
                        help_text="True if auto-assigned based on GPS location",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher number = higher priority. Default = 0",
                    ),
                ),
                (
                    "entered_queue_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sla_due_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Service Level Agreement deadline",
                        null=True,
                    ),
                ),
                (
                    "is_overdue",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Auto-calculated based on SLA",
                    ),
                ),
                (
                    "suggested_constituency",
                    models.CharField(
                        blank=True,
                        help_text="Auto-detected from farm GPS location",
                        max_length=100,
                    ),
                ),
                (
                    "suggested_region",
                    models.CharField(
                        blank=True,
                        help_text="Auto-detected from farm GPS location",
                        max_length=100,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_farm_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_queue_items",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "db_table": "farm_approval_queue",
                "ordering": ["-priority", "entered_queue_at"],
                "indexes": [
                    models.Index(
                        fields=["review_level", "status"],
                        name="farm_approv_review__dd5fcf_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="farm_approv_assigne_23fefe_idx",
                    ),
                    models.Index(
                        fields=["is_overdue", "sla_due_date"],
                        name="farm_approv_is_over_f96aea_idx",
                    ),
                    models.Index(
                        fields=["suggested_constituency"],
                        name="farm_approv_suggest_f800e8_idx",
                    ),
                ],
                "unique_together": {("farm", "review_level")},
            },
        ),
        migrations.CreateModel(
            name="FarmNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("application_submitted", "Application Submitted"),
                            ("review_started", "Review Started"),
                            ("changes_requested", "Changes Requested"),
                            (
                                "approved_next_level",
                                "Approved - Forwarded to Next Level",
                            ),
                            ("final_approval", "Final Approval - Farm ID Assigned"),
                            ("rejected", "Application Rejected"),
                            ("reminder", "Reminder/Alert"),
                            ("assignment", "Review Assignment"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "In-App Notification"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for 'View Details' button in notification",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("read", "Read (In-App only)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "sms_provider",
                    models.CharField(
                        blank=True, help_text="Hubtel, Arkesel, etc.", max_length=50
                    ),
                ),
                (
                    "sms_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Provider's message ID for tracking",
                        max_length=100,
                    ),
                ),
                (
                    "sms_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Cost in GHS",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="farms.farm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "farm_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="farm_notifi_user_id_e009c9_idx"
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="farm_notifi_notific_b75e86_idx",
                    ),
                    models.Index(
                        fields=["channel", "status"],
                        name="farm_notifi_channel_7fe019_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FarmReviewAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "review_level",
                    models.CharField(
                        choices=[
                            ("constituency", "Constituency Level"),
                            ("regional", "Regional Level"),
                            ("national", "National Level"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("claimed", "Claimed for Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("request_changes", "Request Changes"),
                            ("changes_submitted", "Changes Submitted"),
                            ("reassigned", "Reassigned to Another Officer"),
                            ("note_added", "Internal Note Added"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        help_text="Reviewer comments, feedback, or reasons"
                    ),
                ),
                (
                    "is_internal_note",
                    models.BooleanField(
                        default=False, help_text="If True, farmer cannot see this note"
                    ),
                ),
                (
                    "requested_changes",
                    models.JSONField(
                        blank=True,
                        help_text="List of specific fields/documents that need changes",
                        null=True,
                    ),
                ),
                (
                    "changes_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Deadline for farmer to submit changes",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_actions",
                        to="farms.farm",
                    ),
                ),
                (
                    "reassigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reassigned_farm_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="farm_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "farm_review_actions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["farm", "review_level"],
                        name="farm_review_farm_id_295274_idx",
                    ),
                    models.Index(
                        fields=["reviewer", "created_at"],
                        name="farm_review_reviewe_5927bd_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="farm_review_action_55d0b2_idx",
                    ),
                ],
            },
        ),
    ]
