# Generated by Django 5.2.7 on 2025-12-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0002_add_target_region_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmapplication",
            name="farm_gps_address",
            field=models.CharField(
                blank=True,
                help_text="GhanaPost GPS digital address (e.g., GA-184-2278). Get this from GhanaPost GPS mobile app at farm location.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="farmapplication",
            name="farm_location_description",
            field=models.TextField(
                blank=True,
                help_text="Describe farm location (community, landmarks, etc.) - Optional if GPS address provided",
            ),
        ),
    ]
