# Generated by Django 5.2.7 on 2025-12-08 20:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0003_add_gps_to_application"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmInfrastructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "infrastructure_name",
                    models.CharField(
                        help_text="e.g., Main Borehole, Solar Panel Array, Cold Storage Unit",
                        max_length=200,
                    ),
                ),
                (
                    "infrastructure_type",
                    models.CharField(
                        choices=[
                            ("Water System", "Water System"),
                            ("Electrical System", "Electrical System"),
                            ("Drainage System", "Drainage System"),
                            ("Storage Facility", "Storage Facility"),
                            ("Processing Facility", "Processing Facility"),
                            ("Fencing & Security", "Fencing & Security"),
                            ("Access Road", "Access Road"),
                            ("Waste Management", "Waste Management"),
                            ("Ventilation System", "Ventilation System"),
                            ("Cooling System", "Cooling System"),
                            ("Heating System", "Heating System"),
                            ("Feed Mill", "Feed Mill"),
                            ("Hatchery", "Hatchery"),
                            ("Office Building", "Office Building"),
                            ("Worker Quarters", "Worker Quarters"),
                            ("Loading Bay", "Loading Bay"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the infrastructure",
                    ),
                ),
                (
                    "capacity",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 5000 liters/hour, 10kW, 50 tons",
                        max_length=200,
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional technical specifications as key-value pairs",
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=200)),
                ("supplier_contact", models.CharField(blank=True, max_length=100)),
                ("installation_date", models.DateField(blank=True, null=True)),
                (
                    "installation_cost_ghs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("installer_company", models.CharField(blank=True, max_length=200)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("warranty_terms", models.TextField(blank=True)),
                (
                    "manual_document",
                    models.FileField(
                        blank=True,
                        help_text="Upload user manual or technical documentation",
                        null=True,
                        upload_to="infrastructure/manuals/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Operational", "Operational"),
                            ("Under Maintenance", "Under Maintenance"),
                            ("Non-Operational", "Non-Operational"),
                            ("Planned", "Planned"),
                            ("Under Construction", "Under Construction"),
                        ],
                        default="Operational",
                        max_length=50,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Fair", "Fair"),
                            ("Poor", "Poor"),
                            ("Critical", "Critical"),
                        ],
                        default="Good",
                        max_length=50,
                    ),
                ),
                (
                    "condition_notes",
                    models.TextField(
                        blank=True, help_text="Details about current condition"
                    ),
                ),
                (
                    "maintenance_frequency",
                    models.CharField(
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Bi-Annually", "Bi-Annually"),
                            ("Annually", "Annually"),
                            ("As Needed", "As Needed"),
                        ],
                        default="As Needed",
                        max_length=50,
                    ),
                ),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_due", models.DateField(blank=True, null=True)),
                ("maintenance_provider", models.CharField(blank=True, max_length=200)),
                (
                    "maintenance_cost_ghs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual or per-service maintenance cost",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "photos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of photo URLs or file paths",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_infrastructure",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infrastructure",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "db_table": "farm_infrastructure",
                "ordering": ["infrastructure_type", "infrastructure_name"],
                "indexes": [
                    models.Index(
                        fields=["farm", "infrastructure_type"],
                        name="farm_infras_farm_id_b2e9b5_idx",
                    ),
                    models.Index(
                        fields=["status"], name="farm_infras_status_af5a21_idx"
                    ),
                    models.Index(
                        fields=["next_maintenance_due"],
                        name="farm_infras_next_ma_e5031b_idx",
                    ),
                ],
            },
        ),
    ]
