# Generated by Django 5.2.7 on 2025-11-26 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0003_farm_constituency_approved_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="approval_workflow",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_government", "Full 3-Tier Government Review"),
                    ("simplified", "Simplified Verification"),
                    ("auto_approve", "Auto-Approve with Basic Checks"),
                ],
                help_text="Auto-set based on registration_source and fast_track_eligible",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="established_since",
            field=models.DateField(
                blank=True,
                help_text="For established farmers: when farm was originally established",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="extension_officer",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary extension officer for government program farmers",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_farms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="fast_track_criteria_met",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="\n        Criteria for fast-track approval:\n        {\n            'business_registered': True,\n            'tin_verified': True,\n            'existing_operations': True,\n            'documentation_complete': True,\n            'references_provided': True\n        }\n        ",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="fast_track_eligible",
            field=models.BooleanField(
                default=False,
                help_text="Eligible for simplified approval (established farmers with documentation)",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="government_subsidy_active",
            field=models.BooleanField(
                default=False,
                help_text="Is farmer receiving government marketplace subscription subsidy",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="government_subsidy_end_date",
            field=models.DateField(
                blank=True,
                help_text="When government marketplace subsidy expires",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="government_subsidy_start_date",
            field=models.DateField(
                blank=True,
                help_text="When government marketplace subsidy started",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="government_support_package",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="\n        Details of government support received:\n        {\n            'day_old_chicks': 500,\n            'feed_bags': 100,\n            'training_sessions': 5,\n            'extension_visits': 12,\n            'subsidy_amount': 5000.00\n        }\n        ",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="marketplace_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Is marketplace access enabled (requires subscription)",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="previous_management_system",
            field=models.CharField(
                blank=True,
                help_text="Manual/Excel/Other system used before joining platform",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="product_images_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Current number of product images (max 20 with subscription)",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="referral_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("search_engine", "Google/Search Engine"),
                    ("social_media", "Facebook/Instagram/Twitter"),
                    ("farmer_referral", "Referred by Another Farmer"),
                    ("industry_event", "Agricultural Fair/Conference"),
                    ("advertisement", "Advertisement"),
                    ("other", "Other"),
                ],
                help_text="How independent farmer heard about platform",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="registration_source",
            field=models.CharField(
                choices=[
                    ("government_initiative", "YEA Government Initiative"),
                    ("self_registered", "Self-Registered/Independent"),
                    ("migrated", "Migrated from External System"),
                ],
                db_index=True,
                default="self_registered",
                help_text="How the farmer joined the platform",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("none", "No Subscription (Free Core Platform)"),
                    (
                        "government_subsidized",
                        "Government-Subsidized Marketplace (Free/Reduced)",
                    ),
                    ("standard", "Standard Marketplace Subscription (GHS 100/month)"),
                    ("premium", "Premium Subscription (Future)"),
                ],
                default="none",
                help_text="Type of marketplace subscription",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="yea_program_batch",
            field=models.CharField(
                blank=True,
                help_text="YEA batch/cohort (e.g., 'YEA-2025-Q1')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="yea_program_end_date",
            field=models.DateField(
                blank=True, help_text="Expected program completion date", null=True
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="yea_program_start_date",
            field=models.DateField(
                blank=True, help_text="When farmer joined government program", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["registration_source"], name="farms_registr_5a5f7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["approval_workflow"], name="farms_approva_dec5e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["subscription_type"], name="farms_subscri_71b28b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["marketplace_enabled"], name="farms_marketp_a1c9ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["extension_officer"], name="farms_extensi_394ae3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["fast_track_eligible"], name="farms_fast_tr_e036d5_idx"
            ),
        ),
    ]
