# Generated by Django 5.2.7 on 2025-11-26 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0004_farm_approval_workflow_farm_established_since_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="primary_constituency",
            field=models.CharField(
                db_index=True,
                default="Ayawaso Central",
                help_text="Constituency where farm is located - REQUIRED for ALL farmers (government and independent)",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="farm",
            name="extension_officer",
            field=models.ForeignKey(
                blank=True,
                help_text="Extension officer assigned to farmer. REQUIRED for government farmers, OPTIONAL (but recommended) for independent farmers based on constituency.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_farms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["primary_constituency"], name="farms_primary_db3efb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["registration_source", "primary_constituency"],
                name="farms_registr_55dbbe_idx",
            ),
        ),
    ]
