# Generated by Django 5.2.7 on 2025-12-08 21:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0004_add_farm_infrastructure_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Table already exists from previous migrations, just update Django state
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # No database changes
            state_operations=[
                migrations.DeleteModel(
                    name="Equipment",
                ),
        migrations.CreateModel(
            name="FarmEquipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(help_text="Name/identifier", max_length=200),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("Feeder", "Feeder"),
                            ("Drinker", "Drinker"),
                            ("Brooder", "Brooder"),
                            ("Cage", "Cage"),
                            ("Lighting", "Lighting"),
                            ("Ventilation Fan", "Ventilation Fan"),
                            ("Weighing Scale", "Weighing Scale"),
                            ("Egg Collector", "Egg Collector"),
                            ("Egg Candler", "Egg Candler"),
                            ("Incubator", "Incubator"),
                            ("Sprayer", "Sprayer"),
                            ("Shovel/Rake", "Shovel/Rake"),
                            ("Wheelbarrow", "Wheelbarrow"),
                            ("Nesting Box", "Nesting Box"),
                            ("Perch/Roost", "Perch/Roost"),
                            ("Safety Equipment", "Safety Equipment"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, help_text="Brand/manufacturer", max_length=100
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, help_text="Model number", max_length=100
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, help_text="Serial number", max_length=100
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of units",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("In Use", "In Use"),
                            ("Under Maintenance", "Under Maintenance"),
                            ("Out of Service", "Out of Service"),
                            ("Reserved", "Reserved"),
                        ],
                        default="Available",
                        max_length=30,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Fair", "Fair"),
                            ("Poor", "Poor"),
                            ("Damaged", "Damaged"),
                        ],
                        default="Good",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Where it's stored/used (e.g., 'Poultry House 1')",
                        max_length=200,
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price_ghs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Purchase price in GHS",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_value_ghs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current estimated value in GHS",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_due", models.DateField(blank=True, null=True)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_equipment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_items",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Equipment",
                "verbose_name_plural": "Farm Equipment",
                "db_table": "farm_equipment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="farmequipment",
            index=models.Index(
                fields=["farm", "equipment_type"], name="farm_equipm_farm_id_6e558a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmequipment",
            index=models.Index(
                fields=["farm", "status"], name="farm_equipm_farm_id_f88dc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmequipment",
            index=models.Index(
                fields=["farm", "location"], name="farm_equipm_farm_id_3096e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmequipment",
            index=models.Index(
                fields=["next_maintenance_due"], name="farm_equipm_next_ma_c22e6f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="farmequipment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("serial_number", ""), _negated=True),
                fields=("farm", "serial_number"),
                name="unique_serial_per_farm",
            ),
        ),
            ]  # End state_operations
        ),  # End SeparateDatabaseAndState
    ]
