# Generated by Django 5.2.7 on 2025-11-26 13:54

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0005_farm_primary_constituency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationRateLimit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("registration_attempts", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(auto_now=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
                ("block_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "registration_rate_limits",
                "indexes": [
                    models.Index(
                        fields=["ip_address", "is_blocked"],
                        name="registratio_ip_addr_8a55a3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FarmInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invitation_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique invitation code/token",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "invitation_type",
                    models.CharField(
                        choices=[
                            ("government_farmer", "Government Initiative Farmer"),
                            ("independent_farmer", "Independent/Established Farmer"),
                            (
                                "general",
                                "General Invitation (Type determined during registration)",
                            ),
                        ],
                        default="general",
                        help_text="Type of farmer this invitation is for",
                        max_length=30,
                    ),
                ),
                (
                    "constituency",
                    models.CharField(
                        db_index=True,
                        help_text="Constituency this invitation is valid for",
                        max_length=100,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True,
                        help_text="Pre-assigned email (optional)",
                        max_length=254,
                    ),
                ),
                (
                    "recipient_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Pre-assigned phone number (optional)",
                        max_length=128,
                        region="GH",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        help_text="Pre-assigned farmer name (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "is_single_use",
                    models.BooleanField(
                        default=True,
                        help_text="True = one-time use, False = reusable (e.g., for workshops)",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of times this code can be used (for reusable codes)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "current_uses",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this code has been used"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Expiration date/time for this invitation"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending - Not Yet Used"),
                            ("sent", "Sent via Email/SMS"),
                            ("accepted", "Accepted - Registration Completed"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked by Officer"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_via_email", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_via_sms", models.BooleanField(default=False)),
                ("sms_sent_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Officer notes about this invitation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who registered using this invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        help_text="Constituency officer who issued the invitation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "farm_invitations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invitation_code"],
                        name="farm_invita_invitat_e89b5e_idx",
                    ),
                    models.Index(
                        fields=["status", "expires_at"],
                        name="farm_invita_status_d0e795_idx",
                    ),
                    models.Index(
                        fields=["issued_by", "status"],
                        name="farm_invita_issued__a326bc_idx",
                    ),
                    models.Index(
                        fields=["constituency", "status"],
                        name="farm_invita_constit_e5e68a_idx",
                    ),
                    models.Index(
                        fields=["recipient_email"],
                        name="farm_invita_recipie_211b78_idx",
                    ),
                    models.Index(
                        fields=["recipient_phone"],
                        name="farm_invita_recipie_224b00_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistrationApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("farm_name", models.CharField(max_length=200)),
                (
                    "primary_constituency",
                    models.CharField(
                        db_index=True,
                        help_text="Constituency where farm is located",
                        max_length=100,
                    ),
                ),
                ("ghana_card_number", models.CharField(max_length=20, unique=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="GH"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("phone_verified", models.BooleanField(default=False)),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "spam_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Automated spam detection score (0-100, higher = more likely spam)",
                        max_digits=5,
                    ),
                ),
                (
                    "spam_flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="List of spam indicators detected",
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Officer Review"),
                            ("approved", "Approved by Officer"),
                            ("rejected", "Rejected by Officer"),
                            ("flagged_spam", "Flagged as Spam/Bot"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher number = higher priority (verified applicants get higher priority)",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Officer assigned to review this registration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Officer who approved/rejected this registration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User awaiting registration approval",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_approval",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "registration_approvals",
                "ordering": ["-priority", "submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "primary_constituency"],
                        name="registratio_status_472cd3_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="registratio_assigne_c0f730_idx",
                    ),
                    models.Index(
                        fields=["spam_score"], name="registratio_spam_sc_46b2f6_idx"
                    ),
                    models.Index(
                        fields=["-priority", "submitted_at"],
                        name="registratio_priorit_9c4880_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VerificationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Verification"),
                            ("phone", "Phone/SMS Verification"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="6-digit verification code", max_length=10
                    ),
                ),
                (
                    "target_value",
                    models.CharField(
                        help_text="Email address or phone number being verified",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "verification_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of failed verification attempts"
                    ),
                ),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "verification_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "token_type", "status"],
                        name="verificatio_user_id_7b9ed8_idx",
                    ),
                    models.Index(fields=["token"], name="verificatio_token_c488e1_idx"),
                ],
            },
        ),
    ]
