# Generated by Django 5.2.7 on 2025-11-26 14:09

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0006_registrationratelimit_farminvitation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_number",
                    models.CharField(
                        editable=False,
                        help_text="Format: APP-YYYY-XXXXX",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("government_program", "YEA Government Program"),
                            ("independent", "Independent Farmer"),
                        ],
                        db_index=True,
                        help_text="Type of farmer application",
                        max_length=30,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ghana_card_number",
                    models.CharField(
                        help_text="Format: GHA-XXXXXXXXX-X", max_length=20, unique=True
                    ),
                ),
                (
                    "primary_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="GH"
                    ),
                ),
                (
                    "alternate_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region="GH"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional - for notifications",
                        max_length=254,
                    ),
                ),
                ("residential_address", models.TextField()),
                (
                    "primary_constituency",
                    models.CharField(
                        db_index=True,
                        help_text="Constituency where farm will be located",
                        max_length=100,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("proposed_farm_name", models.CharField(max_length=200)),
                (
                    "farm_location_description",
                    models.TextField(
                        help_text="Describe farm location (community, landmarks, etc.)"
                    ),
                ),
                (
                    "land_size_acres",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Approximate land size",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "primary_production_type",
                    models.CharField(
                        choices=[
                            ("Layers", "Layers (Egg Production)"),
                            ("Broilers", "Broilers (Meat Production)"),
                            ("Both", "Both Layers and Broilers"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "planned_bird_capacity",
                    models.PositiveIntegerField(
                        help_text="How many birds do you plan to raise?",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "years_in_poultry",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Years of experience in poultry farming",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "has_existing_farm",
                    models.BooleanField(
                        default=False,
                        help_text="Do you already have an operational farm?",
                    ),
                ),
                (
                    "yea_program_batch",
                    models.CharField(
                        blank=True,
                        help_text="YEA batch/cohort (if applicable)",
                        max_length=50,
                    ),
                ),
                (
                    "referral_source",
                    models.CharField(
                        blank=True,
                        help_text="How did you hear about this program?",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted - Awaiting Assignment"),
                            ("constituency_review", "Under Constituency Review"),
                            ("regional_review", "Under Regional Review"),
                            ("national_review", "Under National Review"),
                            ("changes_requested", "Changes Requested"),
                            ("approved", "Approved - Invitation Sent"),
                            ("rejected", "Rejected"),
                            ("account_created", "Account Created - Farm Active"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=30,
                    ),
                ),
                (
                    "current_review_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("constituency", "Constituency Level"),
                            ("regional", "Regional Level"),
                            ("national", "National Level"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "constituency_approved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("regional_approved_at", models.DateTimeField(blank=True, null=True)),
                ("final_approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("changes_requested", models.TextField(blank=True)),
                ("changes_deadline", models.DateTimeField(blank=True, null=True)),
                ("invitation_sent_at", models.DateTimeField(blank=True, null=True)),
                ("account_created_at", models.DateTimeField(blank=True, null=True)),
                ("farm_created_at", models.DateTimeField(blank=True, null=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("phone_verified", models.BooleanField(default=False)),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "spam_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Automated spam score (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "spam_flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Spam indicators detected",
                        size=None,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "priority_score",
                    models.IntegerField(default=0, help_text="Higher = reviewed first"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_extension_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "constituency_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="constituency_approved_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm_profile",
                    models.OneToOneField(
                        blank=True,
                        help_text="Farm profile created from application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application",
                        to="farms.farm",
                    ),
                ),
                (
                    "final_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="final_approved_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitation",
                    models.OneToOneField(
                        blank=True,
                        help_text="Invitation sent after approval",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_application",
                        to="farms.farminvitation",
                    ),
                ),
                (
                    "regional_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regional_approved_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_account",
                    models.OneToOneField(
                        blank=True,
                        help_text="User account created after approval",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farm_application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "farm_applications",
                "ordering": ["-priority_score", "-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationReviewAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "review_level",
                    models.CharField(
                        choices=[
                            ("constituency", "Constituency Level"),
                            ("regional", "Regional Level"),
                            ("national", "National Level"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("claimed", "Claimed for Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("request_changes", "Request Changes"),
                            ("changes_submitted", "Changes Submitted"),
                            ("note_added", "Note Added"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_actions",
                        to="farms.farmapplication",
                    ),
                ),
            ],
            options={
                "db_table": "application_review_actions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "review_level",
                    models.CharField(
                        choices=[
                            ("constituency", "Constituency Level"),
                            ("regional", "Regional Level"),
                            ("national", "National Level"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("claimed", "Claimed by Officer"),
                            ("in_progress", "Under Review"),
                            ("completed", "Review Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("auto_assigned", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=0)),
                ("entered_queue_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("sla_due_date", models.DateTimeField(blank=True, null=True)),
                ("is_overdue", models.BooleanField(db_index=True, default=False)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_application_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_items",
                        to="farms.farmapplication",
                    ),
                ),
            ],
            options={
                "db_table": "application_queue",
                "ordering": ["-priority", "entered_queue_at"],
            },
        ),
        migrations.AddIndex(
            model_name="farmapplication",
            index=models.Index(
                fields=["application_number"], name="farm_applic_applica_2539e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmapplication",
            index=models.Index(
                fields=["ghana_card_number"], name="farm_applic_ghana_c_b9a007_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmapplication",
            index=models.Index(
                fields=["primary_phone"], name="farm_applic_primary_6723d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmapplication",
            index=models.Index(
                fields=["status", "current_review_level"],
                name="farm_applic_status_8aaee4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="farmapplication",
            index=models.Index(
                fields=["application_type", "status"],
                name="farm_applic_applica_2d3ecd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="farmapplication",
            index=models.Index(
                fields=["primary_constituency", "status"],
                name="farm_applic_primary_be8b1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="farmapplication",
            index=models.Index(
                fields=["-priority_score", "-submitted_at"],
                name="farm_applic_priorit_0ab30a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="applicationreviewaction",
            index=models.Index(
                fields=["application", "review_level"],
                name="application_applica_80175c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="applicationreviewaction",
            index=models.Index(
                fields=["reviewer", "created_at"], name="application_reviewe_a12235_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationqueue",
            index=models.Index(
                fields=["review_level", "status"], name="application_review__94efcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationqueue",
            index=models.Index(
                fields=["assigned_to", "status"], name="application_assigne_9892c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationqueue",
            index=models.Index(
                fields=["is_overdue", "sla_due_date"],
                name="application_is_over_1f291c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="applicationqueue",
            unique_together={("application", "review_level")},
        ),
    ]
