# Generated by Django 5.2.7 on 2025-12-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0007_restructure_equipment_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("Ghana Card", "Ghana Card Photo"),
                    ("Passport Photo", "Passport Photo"),
                    ("Farm Photo - Exterior", "Farm Photo - Poultry House Exterior"),
                    ("Farm Photo - Interior", "Farm Photo - Poultry House Interior"),
                    ("Farm Photo - Layout", "Farm Photo - Overall Farm Layout"),
                    ("Farm Photo - Feeding", "Farm Photo - Feeding System"),
                    ("Farm Photo - Water", "Farm Photo - Water System"),
                    ("Farm Photo - Equipment", "Farm Photo - Equipment"),
                    ("Farm Photo - Storage", "Farm Photo - Storage Facilities"),
                    ("Farm Photo - Biosecurity", "Farm Photo - Biosecurity Measures"),
                    (
                        "Farm Photo - Products",
                        "Farm Photo - Products/Marketing (Max 20)",
                    ),
                    ("Title Deed", "Title Deed"),
                    ("Lease Agreement", "Lease Agreement"),
                    ("Chief Letter", "Letter from Chief/Family Head"),
                    ("Survey Plan", "Survey Plan"),
                    ("Business Registration", "Business Registration Certificate"),
                    ("Production Records", "Previous Production Records"),
                    ("Tax Clearance", "Tax Clearance Certificate"),
                    ("Other", "Other Document"),
                ],
                max_length=50,
            ),
        ),
    ]
