# Generated by Django 5.2.7 on 2025-11-26 14:20

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0007_farmapplication_applicationreviewaction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernmentProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "program_name",
                    models.CharField(
                        help_text="E.g., 'YEA Poultry Support Program 2025'",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "program_code",
                    models.CharField(
                        help_text="E.g., 'YEA-2025-Q1'", max_length=50, unique=True
                    ),
                ),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("training_support", "Training & Extension Support"),
                            ("input_subsidy", "Input Subsidy (Feed, Chicks, etc.)"),
                            ("financial_grant", "Financial Grant/Loan"),
                            ("infrastructure", "Infrastructure Development"),
                            ("comprehensive", "Comprehensive Support Package"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "implementing_agency",
                    models.CharField(
                        help_text="E.g., 'Youth Employment Agency'", max_length=200
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "application_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Last date to accept new applications",
                        null=True,
                    ),
                ),
                (
                    "min_farm_age_months",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum months farm must be operational (0 for new farms)",
                    ),
                ),
                (
                    "max_farm_age_years",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum farm age (e.g., only for new farms < 2 years)",
                        null=True,
                    ),
                ),
                (
                    "min_bird_capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum bird capacity required",
                        null=True,
                    ),
                ),
                (
                    "max_bird_capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum bird capacity (if targeting small-scale)",
                        null=True,
                    ),
                ),
                ("eligible_farmer_age_min", models.PositiveIntegerField(default=18)),
                ("eligible_farmer_age_max", models.PositiveIntegerField(default=65)),
                (
                    "eligible_constituencies",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Leave empty for all constituencies",
                        size=None,
                    ),
                ),
                ("requires_extension_officer", models.BooleanField(default=True)),
                (
                    "support_package_details",
                    models.JSONField(
                        default=dict,
                        help_text="\n        What beneficiaries receive:\n        {\n            'day_old_chicks': 500,\n            'feed_bags_per_cycle': 100,\n            'training_sessions': 12,\n            'extension_visits_per_month': 2,\n            'monetary_grant': 5000.00,\n            'infrastructure_support': 'Cage construction',\n            'marketplace_subsidy_months': 12\n        }\n        ",
                    ),
                ),
                (
                    "total_slots",
                    models.PositiveIntegerField(
                        help_text="Total number of farmers program can support"
                    ),
                ),
                ("slots_filled", models.PositiveIntegerField(default=0)),
                (
                    "slots_available",
                    models.PositiveIntegerField(
                        editable=False, help_text="Auto-calculated"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active - Accepting Applications"),
                            ("full", "Full - Applications Closed"),
                            ("inactive", "Inactive/Ended"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ProgramEnrollmentApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_number",
                    models.CharField(
                        editable=False,
                        help_text="Format: PROG-YYYY-XXXXX",
                        max_length=25,
                        unique=True,
                    ),
                ),
                (
                    "motivation",
                    models.TextField(help_text="Why farmer wants to join this program"),
                ),
                (
                    "current_challenges",
                    models.TextField(help_text="Current challenges farmer faces"),
                ),
                (
                    "expected_benefits",
                    models.TextField(help_text="How program will help farmer"),
                ),
                (
                    "current_bird_count",
                    models.PositiveIntegerField(
                        help_text="Current number of birds on farm"
                    ),
                ),
                (
                    "current_production_type",
                    models.CharField(
                        choices=[
                            ("Layers", "Layers (Egg Production)"),
                            ("Broilers", "Broilers (Meat Production)"),
                            ("Both", "Both Layers and Broilers"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "monthly_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average monthly revenue (optional)",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "years_operational",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Years farm has been operational",
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "farm_photos",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(),
                        blank=True,
                        default=list,
                        help_text="URLs to uploaded farm photos",
                        size=None,
                    ),
                ),
                (
                    "business_documents",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(),
                        blank=True,
                        default=list,
                        help_text="Business registration, permits, etc.",
                        size=None,
                    ),
                ),
                (
                    "eligibility_score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Auto-calculated score (0-100)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "eligibility_flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Issues flagged during eligibility check",
                        size=None,
                    ),
                ),
                (
                    "meets_eligibility",
                    models.BooleanField(
                        default=False,
                        help_text="Does farm meet program eligibility criteria?",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft - Not Submitted"),
                            ("submitted", "Submitted - Awaiting Assignment"),
                            ("eligibility_check", "Eligibility Check"),
                            ("constituency_review", "Under Constituency Review"),
                            ("regional_review", "Under Regional Review"),
                            ("national_review", "Under National Review"),
                            ("changes_requested", "Changes Requested"),
                            ("approved", "Approved - Enrollment in Progress"),
                            ("enrolled", "Enrolled - Farmer Active in Program"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn by Farmer"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "current_review_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("eligibility", "Automated Eligibility Check"),
                            ("constituency", "Constituency Level"),
                            ("regional", "Regional Level"),
                            ("national", "National Level"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "constituency_reviewed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("regional_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("national_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("final_decision_at", models.DateTimeField(blank=True, null=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ineligible_age", "Farmer age outside program range"),
                            (
                                "ineligible_capacity",
                                "Farm capacity outside program range",
                            ),
                            (
                                "ineligible_location",
                                "Farm not in eligible constituency",
                            ),
                            ("farm_too_new", "Farm not operational long enough"),
                            ("farm_too_old", "Farm too established for program"),
                            ("program_full", "Program slots filled"),
                            ("deadline_passed", "Application submitted after deadline"),
                            ("already_enrolled", "Already enrolled in similar program"),
                            ("documentation_incomplete", "Missing required documents"),
                            ("failed_verification", "Farm verification failed"),
                            ("other", "Other reason (see notes)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rejection_notes", models.TextField(blank=True)),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes from reviewers"
                    ),
                ),
                (
                    "priority_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Higher = more urgent"
                    ),
                ),
                ("enrollment_completed", models.BooleanField(default=False)),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "support_package_allocated",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Actual support package farmer receives",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        help_text="Farmer submitting application",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_extension_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrolled_farmers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="Existing farm applying to program",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_applications",
                        to="farms.farm",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="farms.governmentprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgramEnrollmentQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "review_level",
                    models.CharField(
                        choices=[
                            ("eligibility", "Eligibility Check"),
                            ("constituency", "Constituency"),
                            ("regional", "Regional"),
                            ("national", "National"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Assignment"),
                            ("assigned", "Assigned to Officer"),
                            ("in_review", "Under Review"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("priority", models.PositiveIntegerField(default=0)),
                (
                    "sla_deadline",
                    models.DateTimeField(
                        help_text="When this review level should be completed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="farms.programenrollmentapplication",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_program_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "sla_deadline"],
            },
        ),
        migrations.CreateModel(
            name="ProgramEnrollmentReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "review_level",
                    models.CharField(
                        choices=[
                            ("eligibility", "Eligibility Check"),
                            ("constituency", "Constituency"),
                            ("regional", "Regional"),
                            ("national", "National"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Application Submitted"),
                            ("eligibility_passed", "Passed Eligibility Check"),
                            ("eligibility_failed", "Failed Eligibility Check"),
                            ("assigned", "Assigned to Reviewer"),
                            ("claimed", "Claimed for Review"),
                            ("approved", "Approved at Level"),
                            ("rejected", "Rejected"),
                            ("changes_requested", "Changes Requested"),
                            ("withdrawn", "Withdrawn by Farmer"),
                            ("enrolled", "Enrollment Completed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="farms.programenrollmentapplication",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="governmentprogram",
            index=models.Index(
                fields=["status", "application_deadline"],
                name="farms_gover_status_a562d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="governmentprogram",
            index=models.Index(
                fields=["program_code"], name="farms_gover_program_7b5806_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programenrollmentapplication",
            index=models.Index(
                fields=["status", "priority_score"],
                name="farms_progr_status_657960_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="programenrollmentapplication",
            index=models.Index(
                fields=["program", "status"], name="farms_progr_program_68fc10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programenrollmentapplication",
            index=models.Index(
                fields=["applicant", "status"], name="farms_progr_applica_ad5335_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programenrollmentapplication",
            index=models.Index(
                fields=["current_review_level", "submitted_at"],
                name="farms_progr_current_558d61_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programenrollmentapplication",
            unique_together={("farm", "program")},
        ),
        migrations.AddIndex(
            model_name="programenrollmentqueue",
            index=models.Index(
                fields=["status", "priority"], name="farms_progr_status_d63a09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programenrollmentqueue",
            index=models.Index(
                fields=["review_level", "sla_deadline"],
                name="farms_progr_review__84b950_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="programenrollmentqueue",
            index=models.Index(
                fields=["assigned_to", "status"], name="farms_progr_assigne_c98705_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programenrollmentqueue",
            unique_together={("application", "review_level")},
        ),
        migrations.AddIndex(
            model_name="programenrollmentreview",
            index=models.Index(
                fields=["application", "timestamp"],
                name="farms_progr_applica_ae803d_idx",
            ),
        ),
    ]
