# Generated by Django 5.2.7 on 2025-12-09 00:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0008_add_product_photos_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="poultryhouse",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="poultryhouse",
            name="farm",
        ),
        migrations.CreateModel(
            name="Infrastructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("poultry_house", "Poultry House"),
                            ("farm_system", "Farm System"),
                        ],
                        db_index=True,
                        default="poultry_house",
                        help_text="Discriminator: 'poultry_house' or 'farm_system'",
                        max_length=20,
                    ),
                ),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "house_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Deep Litter", "Deep Litter"),
                            ("Battery Cage", "Battery Cage"),
                            ("Free Range Shelter", "Free Range Shelter"),
                            ("Brooder House", "Brooder House"),
                            ("Layer House", "Layer House"),
                            ("Grower House", "Grower House"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("house_capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("current_occupancy", models.PositiveIntegerField(default=0)),
                (
                    "length_meters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "width_meters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "height_meters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("construction_material", models.CharField(blank=True, max_length=100)),
                ("roofing_material", models.CharField(blank=True, max_length=100)),
                ("flooring_type", models.CharField(blank=True, max_length=100)),
                ("year_built", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ventilation_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Natural", "Natural"),
                            ("Mechanical (Fans)", "Mechanical (Fans)"),
                            ("Both", "Both Natural and Mechanical"),
                        ],
                        max_length=50,
                    ),
                ),
                ("number_of_fans", models.PositiveIntegerField(default=0)),
                (
                    "estimated_house_value_ghs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "infrastructure_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Water System", "Water System"),
                            ("Electrical System", "Electrical System"),
                            ("Drainage System", "Drainage System"),
                            ("Storage Facility", "Storage Facility"),
                            ("Processing Facility", "Processing Facility"),
                            ("Fencing & Security", "Fencing & Security"),
                            ("Access Road", "Access Road"),
                            ("Waste Management", "Waste Management"),
                            ("Ventilation System", "Ventilation System"),
                            ("Cooling System", "Cooling System"),
                            ("Heating System", "Heating System"),
                            ("Feed Mill", "Feed Mill"),
                            ("Hatchery", "Hatchery"),
                            ("Office Building", "Office Building"),
                            ("Worker Quarters", "Worker Quarters"),
                            ("Loading Bay", "Loading Bay"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "infrastructure_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Main Borehole, Solar Panel Array",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "capacity",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 5000 liters/hour, 10kW",
                        max_length=200,
                    ),
                ),
                ("specifications", models.JSONField(blank=True, default=dict)),
                ("supplier", models.CharField(blank=True, max_length=200)),
                ("supplier_contact", models.CharField(blank=True, max_length=100)),
                ("installation_date", models.DateField(blank=True, null=True)),
                (
                    "installation_cost_ghs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("installer_company", models.CharField(blank=True, max_length=200)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("warranty_terms", models.TextField(blank=True)),
                (
                    "manual_document",
                    models.FileField(
                        blank=True, null=True, upload_to="infrastructure/manuals/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Operational", "Operational"),
                            ("Under Maintenance", "Under Maintenance"),
                            ("Non-Operational", "Non-Operational"),
                            ("Planned", "Planned"),
                            ("Under Construction", "Under Construction"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Fair", "Fair"),
                            ("Poor", "Poor"),
                            ("Critical", "Critical"),
                        ],
                        max_length=50,
                    ),
                ),
                ("condition_notes", models.TextField(blank=True)),
                (
                    "maintenance_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Bi-Annually", "Bi-Annually"),
                            ("Annually", "Annually"),
                            ("As Needed", "As Needed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_due", models.DateField(blank=True, null=True)),
                ("maintenance_provider", models.CharField(blank=True, max_length=200)),
                (
                    "maintenance_cost_ghs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_infrastructure",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infrastructure",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "db_table": "infrastructure",
                "ordering": ["category", "house_number", "infrastructure_name"],
            },
        ),
        migrations.DeleteModel(
            name="FarmInfrastructure",
        ),
    ]
