# Generated by Django 5.2.7 on 2025-12-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0009_alter_poultryhouse_unique_together_and_more"),
        ("flock_management", "0002_alter_flock_housed_in"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PoultryHouse",
        ),
        migrations.AddIndex(
            model_name="infrastructure",
            index=models.Index(
                fields=["farm", "category"], name="infrastruct_farm_id_c762a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="infrastructure",
            index=models.Index(
                fields=["category"], name="infrastruct_categor_6401c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="infrastructure",
            index=models.Index(fields=["status"], name="infrastruct_status_bc45a2_idx"),
        ),
        migrations.CreateModel(
            name="FarmInfrastructure",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("farms.infrastructure",),
        ),
        migrations.CreateModel(
            name="PoultryHouse",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("farms.infrastructure",),
        ),
    ]
