# Generated by Django 5.2.7 on 2025-12-09 01:20

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0010_delete_poultryhouse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="infrastructure",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="infrastructure",
            name="infrastruct_farm_id_c762a4_idx",
        ),
        migrations.RemoveIndex(
            model_name="infrastructure",
            name="infrastruct_categor_6401c0_idx",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="category",
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="capacity",
            field=models.CharField(
                blank=True,
                help_text="e.g., '5000 liters/hour', '10kW', '50 tons'",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="current_occupancy",
            field=models.PositiveIntegerField(
                default=0, help_text="Current number of birds"
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="estimated_house_value_ghs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated value for housing infrastructure",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="height_meters",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Housing height in meters",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="house_capacity",
            field=models.PositiveIntegerField(
                blank=True, help_text="Maximum bird capacity for housing", null=True
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="house_number",
            field=models.CharField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="House identification number",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="house_type",
            field=models.CharField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Specific housing type",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="infrastructure_name",
            field=models.CharField(
                help_text="e.g., 'House H1', 'Main Borehole', 'Solar Panel Array'",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="infrastructure_type",
            field=models.CharField(
                choices=[
                    ("Battery Cage Housing", "Battery Cage Housing"),
                    ("Deep Litter Housing", "Deep Litter Housing"),
                    ("Free Range Housing", "Free Range Housing"),
                    ("Brooder Housing", "Brooder Housing"),
                    ("Layer Housing", "Layer Housing"),
                    ("Grower Housing", "Grower Housing"),
                    ("Water System", "Water System"),
                    ("Electrical System", "Electrical System"),
                    ("Drainage System", "Drainage System"),
                    ("Storage Facility", "Storage Facility"),
                    ("Processing Facility", "Processing Facility"),
                    ("Fencing & Security", "Fencing & Security"),
                    ("Access Road", "Access Road"),
                    ("Waste Management", "Waste Management"),
                    ("Ventilation System", "Ventilation System"),
                    ("Cooling System", "Cooling System"),
                    ("Heating System", "Heating System"),
                    ("Feed Mill", "Feed Mill"),
                    ("Hatchery", "Hatchery"),
                    ("Lighting System", "Lighting System"),
                    ("Security System", "Security System"),
                    ("Office Building", "Office Building"),
                    ("Worker Quarters", "Worker Quarters"),
                    ("Loading Bay", "Loading Bay"),
                    ("Other", "Other"),
                ],
                db_index=True,
                help_text="Infrastructure type. Housing types include 'Housing' suffix.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="ventilation_system",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="width_meters",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Housing width in meters",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="infrastructure",
            index=models.Index(
                fields=["farm", "infrastructure_type"],
                name="infrastruct_farm_id_4a35fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="infrastructure",
            index=models.Index(
                fields=["infrastructure_type"], name="infrastruct_infrast_5548bd_idx"
            ),
        ),
    ]
