# Generated by Django 5.2.7 on 2025-12-09 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0011_alter_infrastructure_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="infrastructure",
            name="infrastruct_status_bc45a2_idx",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="construction_material",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="estimated_house_value_ghs",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="flooring_type",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="house_capacity",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="house_number",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="house_type",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="installation_cost_ghs",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="installer_company",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="maintenance_cost_ghs",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="maintenance_provider",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="manual_document",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="number_of_fans",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="photos",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="roofing_material",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="specifications",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="supplier_contact",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="ventilation_system",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="warranty_terms",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="year_built",
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="bird_capacity",
            field=models.IntegerField(
                blank=True,
                help_text="Number of birds this infrastructure can serve/house",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="housing_system",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Battery Cage", "Battery Cage"),
                    ("Deep Litter", "Deep Litter"),
                    ("Free Range", "Free Range"),
                    ("Brooder", "Brooder"),
                    ("Layer", "Layer"),
                    ("Grower", "Grower"),
                ],
                help_text="Housing system type (only for Accommodation)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="capacity",
            field=models.CharField(
                blank=True,
                help_text="General capacity description (e.g., '5000L', '50kW')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="condition",
            field=models.CharField(
                choices=[
                    ("Excellent", "Excellent"),
                    ("Good", "Good"),
                    ("Fair", "Fair"),
                    ("Poor", "Poor"),
                    ("Critical", "Critical"),
                ],
                default="Good",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="condition_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="current_occupancy",
            field=models.IntegerField(
                blank=True,
                help_text="Current number of birds (primarily for Accommodation)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="height_meters",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="infrastructure_type",
            field=models.CharField(
                choices=[
                    ("Accommodation", "Accommodation"),
                    ("Water System", "Water System"),
                    ("Power Supply", "Power Supply"),
                    ("Ventilation", "Ventilation"),
                    ("Heating", "Heating"),
                    ("Cooling", "Cooling"),
                    ("Lighting", "Lighting"),
                    ("Waste Management", "Waste Management"),
                    ("Security", "Security"),
                    ("Other", "Other"),
                ],
                db_index=True,
                help_text="Infrastructure type",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="length_meters",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="maintenance_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("Quarterly", "Quarterly"),
                    ("Bi-Annually", "Bi-Annually"),
                    ("Annually", "Annually"),
                    ("As Needed", "As Needed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="status",
            field=models.CharField(
                choices=[
                    ("Operational", "Operational"),
                    ("Under Maintenance", "Under Maintenance"),
                    ("Non-Operational", "Non-Operational"),
                    ("Planned", "Planned"),
                    ("Under Construction", "Under Construction"),
                ],
                default="Operational",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="supplier",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="width_meters",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
