# Generated by Django 5.2.7 on 2025-12-09 11:09

from django.db import migrations


def convert_housing_types_to_accommodation(apps, schema_editor):
    """
    Convert existing housing infrastructure types to 'Accommodation'
    and populate housing_system field with the specific housing type.
    """
    Infrastructure = apps.get_model('farms', 'Infrastructure')
    
    # Mapping of old housing types to housing_system values
    housing_type_mapping = {
        'Battery Cage Housing': 'Battery Cage',
        'Deep Litter Housing': 'Deep Litter',
        'Free Range Housing': 'Free Range',
        'Brooder Housing': 'Brooder',
        'Layer Housing': 'Layer',
        'Grower Housing': 'Grower',
    }
    
    # Get all infrastructure with housing types
    for old_type, housing_system in housing_type_mapping.items():
        Infrastructure.objects.filter(
            infrastructure_type=old_type
        ).update(
            infrastructure_type='Accommodation',
            housing_system=housing_system
        )
    
    print(f"Converted housing infrastructure to 'Accommodation' type")


def reverse_migration(apps, schema_editor):
    """
    Reverse the conversion - restore original housing type names
    """
    Infrastructure = apps.get_model('farms', 'Infrastructure')
    
    # Reverse mapping
    reverse_mapping = {
        'Battery Cage': 'Battery Cage Housing',
        'Deep Litter': 'Deep Litter Housing',
        'Free Range': 'Free Range Housing',
        'Brooder': 'Brooder Housing',
        'Layer': 'Layer Housing',
        'Grower': 'Grower Housing',
    }
    
    for housing_system, old_type in reverse_mapping.items():
        Infrastructure.objects.filter(
            infrastructure_type='Accommodation',
            housing_system=housing_system
        ).update(
            infrastructure_type=old_type
        )


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0012_remove_infrastructure_infrastruct_status_bc45a2_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(
            convert_housing_types_to_accommodation,
            reverse_migration
        ),
    ]
