# Generated by Django 5.1.3 on 2026-01-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0013_convert_housing_to_accommodation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="government_subsidy_active",
            field=models.BooleanField(
                default=False,
                help_text="Is farmer receiving government marketplace activation subsidy",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="marketplace_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Is marketplace access enabled (requires activation payment)",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="product_images_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Current number of product images (max 20 with activation)",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("none", "No Marketplace Access (Free Core Platform)"),
                    (
                        "government_subsidized",
                        "Government-Subsidized Marketplace Access",
                    ),
                    ("standard", "Standard Marketplace Access (GHS 50/month)"),
                    ("verified", "Verified Seller (GHS 50 + Priority Features)"),
                ],
                default="none",
                help_text="Type of marketplace access (activation level)",
                max_length=30,
            ),
        ),
    ]
