# Generated by Django 5.2.7 on 2026-01-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0014_alter_farm_government_subsidy_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("none", "No Marketplace Access (Free Core Platform)"),
                    (
                        "government_subsidized",
                        "Government-Subsidized Marketplace Access",
                    ),
                    ("standard", "Standard Marketplace Access (GHS 50/month)"),
                ],
                default="none",
                help_text="Type of marketplace access (activation level)",
                max_length=30,
            ),
        ),
    ]
