# Generated by Django 5.2.7 on 2026-01-16 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0015_remove_verified_seller_tier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="days_since_last_sale",
            field=models.PositiveIntegerField(
                default=0, help_text="Days since last recorded sale (any type)"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="distress_last_calculated",
            field=models.DateTimeField(
                blank=True,
                help_text="When distress score was last calculated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="distress_level",
            field=models.CharField(
                choices=[
                    ("STABLE", "Stable - Healthy operations"),
                    ("LOW", "Low - Minor issues"),
                    ("MODERATE", "Moderate - Some difficulties"),
                    ("HIGH", "High - Significant struggle"),
                    ("CRITICAL", "Critical - Urgent intervention needed"),
                ],
                db_index=True,
                default="STABLE",
                help_text="Current distress level category",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="distress_score",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cached distress score (0-100). Updated by background task.",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="inventory_stagnation_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Days oldest inventory has been sitting unsold"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="unsold_inventory_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of birds/crates ready for sale but unsold"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["distress_score"], name="farms_distres_4d4de6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["distress_level"], name="farms_distres_58937f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["-distress_score", "farm_status"],
                name="farms_distres_a12577_idx",
            ),
        ),
    ]
