# Generated by Django 5.2.10 on 2026-01-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0016_distress_tracking_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farm",
            name="government_subsidy_active",
        ),
        migrations.RemoveField(
            model_name="farm",
            name="government_subsidy_end_date",
        ),
        migrations.RemoveField(
            model_name="farm",
            name="government_subsidy_start_date",
        ),
        migrations.AlterField(
            model_name="farm",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("none", "No Marketplace Access (Free Core Platform)"),
                    ("standard", "Standard Marketplace Access (GHS 50/month)"),
                ],
                default="none",
                help_text="Type of marketplace access (activation level)",
                max_length=30,
            ),
        ),
    ]
