# Generated by Django 5.2.7 on 2025-10-26 11:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "flock_number",
                    models.CharField(
                        help_text="Unique flock identifier (e.g., FLOCK-2025-001)",
                        max_length=50,
                    ),
                ),
                (
                    "flock_type",
                    models.CharField(
                        choices=[
                            ("Layers", "Layers (Egg Production)"),
                            ("Broilers", "Broilers (Meat Production)"),
                            ("Breeders", "Breeders (Hatching)"),
                            ("Pullets", "Pullets (Young Layers)"),
                            ("Mixed", "Mixed Purpose"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        help_text="Bird breed (e.g., Isa Brown, Cobb 500, Sasso)",
                        max_length=100,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("YEA Program", "YEA Program (Government Support)"),
                            ("Purchased", "Purchased from Supplier"),
                            ("Hatched On-Farm", "Hatched On-Farm"),
                            ("Donated", "Donated/Gift"),
                        ],
                        default="YEA Program",
                        max_length=30,
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True,
                        help_text="Hatchery or supplier name",
                        max_length=200,
                    ),
                ),
                (
                    "arrival_date",
                    models.DateField(help_text="Date birds arrived at farm"),
                ),
                (
                    "initial_count",
                    models.PositiveIntegerField(
                        help_text="Number of birds at arrival",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "age_at_arrival_weeks",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Age in weeks when birds arrived",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "purchase_price_per_bird",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost per bird (GHS)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_acquisition_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total cost for this flock (GHS)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_count",
                    models.PositiveIntegerField(
                        help_text="Current number of live birds"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Sold", "Sold/Completed"),
                            ("Culled", "Culled"),
                            ("Depleted", "Fully Depleted (All Dead)"),
                        ],
                        db_index=True,
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "production_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when layers started producing eggs (18-20 weeks)",
                        null=True,
                    ),
                ),
                (
                    "expected_production_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected date to cull/sell (70-80 weeks for layers)",
                        null=True,
                    ),
                ),
                (
                    "is_currently_producing",
                    models.BooleanField(
                        default=False, help_text="True if flock is actively laying eggs"
                    ),
                ),
                (
                    "total_feed_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total feed cost accumulated (GHS)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_medication_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total medication cost accumulated (GHS)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_vaccination_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total vaccination cost accumulated (GHS)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_mortality",
                    models.PositiveIntegerField(
                        default=0, help_text="Total birds died since arrival"
                    ),
                ),
                (
                    "mortality_rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="(Total mortality / initial count) × 100",
                        max_digits=5,
                    ),
                ),
                (
                    "average_daily_mortality",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average birds dying per day",
                        max_digits=6,
                    ),
                ),
                (
                    "total_eggs_produced",
                    models.PositiveIntegerField(
                        default=0, help_text="Total eggs produced by this flock"
                    ),
                ),
                (
                    "average_eggs_per_bird",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total eggs / initial count",
                        max_digits=8,
                    ),
                ),
                (
                    "total_feed_consumed_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total feed consumed in kilograms",
                        max_digits=12,
                    ),
                ),
                (
                    "feed_conversion_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Feed consumed (kg) / Production (kg eggs or meat)",
                        max_digits=6,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General notes about this flock"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flocks",
                        to="farms.farm",
                    ),
                ),
                (
                    "housed_in",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current housing location",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flocks",
                        to="farms.poultryhouse",
                    ),
                ),
            ],
            options={
                "db_table": "flocks",
                "ordering": ["-arrival_date", "flock_number"],
            },
        ),
        migrations.CreateModel(
            name="DailyProduction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "production_date",
                    models.DateField(
                        db_index=True, help_text="Date of this production record"
                    ),
                ),
                (
                    "eggs_collected",
                    models.PositiveIntegerField(
                        default=0, help_text="Total eggs collected today"
                    ),
                ),
                (
                    "good_eggs",
                    models.PositiveIntegerField(
                        default=0, help_text="Clean, sellable eggs"
                    ),
                ),
                (
                    "broken_eggs",
                    models.PositiveIntegerField(
                        default=0, help_text="Eggs broken during collection"
                    ),
                ),
                (
                    "dirty_eggs",
                    models.PositiveIntegerField(
                        default=0, help_text="Eggs with dirt/manure (need cleaning)"
                    ),
                ),
                (
                    "small_eggs",
                    models.PositiveIntegerField(
                        default=0, help_text="Undersized eggs (below standard)"
                    ),
                ),
                (
                    "soft_shell_eggs",
                    models.PositiveIntegerField(
                        default=0, help_text="Eggs with soft/thin shells"
                    ),
                ),
                (
                    "production_rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="(Eggs collected / current bird count) × 100",
                        max_digits=5,
                    ),
                ),
                (
                    "birds_died",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of birds that died today"
                    ),
                ),
                (
                    "mortality_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Disease", "Disease/Illness"),
                            ("Predator", "Predator Attack"),
                            ("Cannibalism", "Cannibalism/Pecking"),
                            ("Heat Stress", "Heat Stress"),
                            ("Suffocation", "Suffocation/Overcrowding"),
                            ("Unknown", "Unknown Cause"),
                            ("Culled", "Culled (Selective Removal)"),
                            ("Old Age", "Old Age/Natural"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "mortality_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about mortality"
                    ),
                ),
                (
                    "feed_consumed_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total feed consumed today (kg)",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "feed_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Chick Starter", "Chick Starter (0-8 weeks)"),
                            ("Grower", "Grower (9-18 weeks)"),
                            ("Layer Mash", "Layer Mash"),
                            ("Layer Pellets", "Layer Pellets"),
                            ("Broiler Starter", "Broiler Starter"),
                            ("Broiler Finisher", "Broiler Finisher"),
                            ("Custom Mix", "Custom/Own Mix"),
                        ],
                        help_text="Type of feed given",
                        max_length=50,
                    ),
                ),
                (
                    "feed_cost_today",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost of feed consumed today (GHS)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "birds_sold",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of birds sold today"
                    ),
                ),
                (
                    "birds_sold_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Revenue from birds sold (GHS)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "general_health",
                    models.CharField(
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Fair", "Fair"),
                            ("Poor", "Poor"),
                            ("Critical", "Critical"),
                        ],
                        default="Good",
                        max_length=20,
                    ),
                ),
                (
                    "unusual_behavior",
                    models.TextField(
                        blank=True,
                        help_text="Any unusual behavior observed (lethargy, aggression, etc.)",
                    ),
                ),
                (
                    "signs_of_disease",
                    models.BooleanField(
                        default=False, help_text="Check if disease symptoms observed"
                    ),
                ),
                (
                    "disease_symptoms",
                    models.TextField(
                        blank=True,
                        help_text="Description of disease symptoms if observed",
                    ),
                ),
                (
                    "vaccination_given",
                    models.BooleanField(
                        default=False, help_text="Was vaccination administered today?"
                    ),
                ),
                (
                    "vaccination_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of vaccine given (Newcastle, Gumboro, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "medication_given",
                    models.BooleanField(
                        default=False, help_text="Was medication administered today?"
                    ),
                ),
                (
                    "medication_type",
                    models.CharField(
                        blank=True, help_text="Type of medication given", max_length=100
                    ),
                ),
                (
                    "medication_cost_today",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost of medication/vaccination today (GHS)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_productions",
                        to="farms.farm",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_productions",
                        to="flock_management.flock",
                    ),
                ),
            ],
            options={
                "db_table": "daily_production",
                "ordering": ["-production_date"],
            },
        ),
        migrations.CreateModel(
            name="MortalityRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_discovered",
                    models.DateField(
                        db_index=True, help_text="Date mortality was discovered"
                    ),
                ),
                (
                    "number_of_birds",
                    models.PositiveIntegerField(
                        help_text="Number of birds that died in this incident",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "probable_cause",
                    models.CharField(
                        choices=[
                            (
                                "Disease - Viral",
                                "Disease - Viral (Newcastle, Gumboro, etc.)",
                            ),
                            (
                                "Disease - Bacterial",
                                "Disease - Bacterial (E.coli, Salmonella, etc.)",
                            ),
                            (
                                "Disease - Parasitic",
                                "Disease - Parasitic (Worms, Coccidiosis)",
                            ),
                            ("Predator", "Predator Attack (Snake, Cat, etc.)"),
                            ("Cannibalism", "Cannibalism/Pecking"),
                            ("Heat Stress", "Heat/Environmental Stress"),
                            ("Suffocation", "Suffocation/Overcrowding"),
                            ("Malnutrition", "Malnutrition/Feed Quality"),
                            ("Poisoning", "Poisoning/Toxicity"),
                            ("Unknown", "Unknown Cause"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "disease_suspected",
                    models.CharField(
                        blank=True,
                        help_text="Specific disease suspected (Newcastle Disease, Fowl Pox, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "symptoms_observed",
                    models.JSONField(
                        default=list, help_text="List of symptoms observed (JSON array)"
                    ),
                ),
                (
                    "symptoms_description",
                    models.TextField(
                        blank=True, help_text="Detailed description of symptoms"
                    ),
                ),
                (
                    "vet_inspection_required",
                    models.BooleanField(
                        default=False,
                        help_text="Requires veterinary officer inspection?",
                    ),
                ),
                (
                    "vet_inspection_requested_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "vet_inspected",
                    models.BooleanField(
                        default=False, help_text="Has veterinary officer inspected?"
                    ),
                ),
                ("vet_inspection_date", models.DateField(blank=True, null=True)),
                (
                    "vet_diagnosis",
                    models.TextField(
                        blank=True, help_text="Veterinary officer's diagnosis"
                    ),
                ),
                (
                    "lab_test_conducted",
                    models.BooleanField(
                        default=False, help_text="Was lab test conducted?"
                    ),
                ),
                (
                    "lab_test_results",
                    models.TextField(blank=True, help_text="Laboratory test results"),
                ),
                (
                    "disposal_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Burial", "Burial"),
                            ("Incineration", "Incineration/Burning"),
                            ("Composting", "Composting"),
                            ("Rendering", "Rendering Plant"),
                            ("Other", "Other Method"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "disposal_location",
                    models.CharField(
                        blank=True,
                        help_text="GPS coordinates or description of disposal site",
                        max_length=200,
                    ),
                ),
                ("disposal_date", models.DateField(blank=True, null=True)),
                (
                    "estimated_value_per_bird",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated market value per bird (GHS)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_estimated_loss",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total financial loss (GHS)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "compensation_claimed",
                    models.BooleanField(
                        default=False, help_text="Has compensation been claimed?"
                    ),
                ),
                (
                    "compensation_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Compensation amount claimed (GHS)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "compensation_status",
                    models.CharField(
                        choices=[
                            ("Not Claimed", "Not Claimed"),
                            ("Pending", "Pending Review"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Paid", "Paid"),
                        ],
                        default="Not Claimed",
                        max_length=20,
                    ),
                ),
                (
                    "photo_1",
                    models.FileField(
                        blank=True,
                        help_text="Photo evidence 1 (dead birds)",
                        null=True,
                        upload_to="mortality_evidence/%Y/%m/",
                    ),
                ),
                (
                    "photo_2",
                    models.FileField(
                        blank=True,
                        help_text="Photo evidence 2",
                        null=True,
                        upload_to="mortality_evidence/%Y/%m/",
                    ),
                ),
                (
                    "photo_3",
                    models.FileField(
                        blank=True,
                        help_text="Photo evidence 3",
                        null=True,
                        upload_to="mortality_evidence/%Y/%m/",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes and observations"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_production",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mortality_details",
                        to="flock_management.dailyproduction",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortality_records",
                        to="farms.farm",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortality_records",
                        to="flock_management.flock",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        help_text="Person who reported this mortality",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mortality_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vet_inspector",
                    models.ForeignKey(
                        blank=True,
                        help_text="Veterinary officer who inspected",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mortality_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mortality_records",
                "ordering": ["-date_discovered"],
            },
        ),
        migrations.AddIndex(
            model_name="flock",
            index=models.Index(
                fields=["farm", "status"], name="flocks_farm_id_ec3324_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flock",
            index=models.Index(
                fields=["flock_type", "status"], name="flocks_flock_t_4eb667_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flock",
            index=models.Index(
                fields=["arrival_date"], name="flocks_arrival_519620_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="flock",
            unique_together={("farm", "flock_number")},
        ),
        migrations.AddIndex(
            model_name="dailyproduction",
            index=models.Index(
                fields=["farm", "production_date"],
                name="daily_produ_farm_id_ff7722_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyproduction",
            index=models.Index(
                fields=["flock", "production_date"],
                name="daily_produ_flock_i_6dfa70_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyproduction",
            index=models.Index(
                fields=["-production_date"], name="daily_produ_product_07a04e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyproduction",
            unique_together={("flock", "production_date")},
        ),
        migrations.AddIndex(
            model_name="mortalityrecord",
            index=models.Index(
                fields=["farm", "date_discovered"],
                name="mortality_r_farm_id_361055_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mortalityrecord",
            index=models.Index(
                fields=["flock", "date_discovered"],
                name="mortality_r_flock_i_b9f26f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mortalityrecord",
            index=models.Index(
                fields=["probable_cause"], name="mortality_r_probabl_c77f64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mortalityrecord",
            index=models.Index(
                fields=["vet_inspection_required", "vet_inspected"],
                name="mortality_r_vet_ins_00ec16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mortalityrecord",
            index=models.Index(
                fields=["compensation_claimed", "compensation_status"],
                name="mortality_r_compens_4cc59b_idx",
            ),
        ),
    ]
