# Generated by Django 5.2.7 on 2025-12-09 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0009_alter_poultryhouse_unique_together_and_more"),
        ("flock_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flock",
            name="housed_in",
            field=models.ForeignKey(
                blank=True,
                help_text="Current housing location (must be a poultry house)",
                limit_choices_to={"category": "poultry_house"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flocks",
                to="farms.infrastructure",
            ),
        ),
    ]
