# Generated by Django 5.2.7 on 2025-10-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed_inventory", "0001_initial"),
        ("flock_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyproduction",
            name="feed_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of feed given (links to Feed Inventory)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_production_records",
                to="feed_inventory.feedtype",
            ),
        ),
    ]
