# Generated by Django 5.2.7 on 2025-12-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0013_convert_housing_to_accommodation"),
        ("flock_management", "0002_alter_flock_housed_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flock",
            name="housed_in",
            field=models.ForeignKey(
                blank=True,
                help_text="Current housing location (must be Accommodation type)",
                limit_choices_to={"infrastructure_type": "Accommodation"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flocks",
                to="farms.infrastructure",
            ),
        ),
    ]
