# Generated by Django 5.1.3 on 2025-12-09 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flock_management", "0014_health_record"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="healthrecord",
            new_name="health_reco_farm_id_bf0557_idx",
            old_name="health_reco_farm_id_27b62f_idx",
        ),
        migrations.RenameIndex(
            model_name="healthrecord",
            new_name="health_reco_flock_i_97895d_idx",
            old_name="health_reco_flock_i_519e62_idx",
        ),
        migrations.RenameIndex(
            model_name="healthrecord",
            new_name="health_reco_record__e00e41_idx",
            old_name="health_reco_record__d2acef_idx",
        ),
    ]
