# Generated by Django 5.2.7 on 2026-01-19 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "flock_management",
            "0015_rename_health_reco_farm_id_27b62f_idx_health_reco_farm_id_bf0557_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="flock",
            name="total_bedding_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total litter/bedding cost accumulated (GHS)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="flock",
            name="total_labor_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total labor/wages cost accumulated (GHS)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="flock",
            name="total_maintenance_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total equipment/maintenance cost accumulated (GHS)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="flock",
            name="total_miscellaneous_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total miscellaneous costs accumulated (GHS)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="flock",
            name="total_mortality_loss_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total economic value lost from mortality (GHS)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="flock",
            name="total_overhead_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total overhead/admin cost accumulated (GHS)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="flock",
            name="total_transport_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total transport cost accumulated (GHS)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="flock",
            name="total_utilities_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total utilities (electricity, water) cost accumulated (GHS)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
