# Generated by Django 5.2.7 on 2026-01-20 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "flock_management",
            "0016_flock_total_bedding_cost_flock_total_labor_cost_and_more",
        ),
        ("medication_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="medication_record",
            field=models.OneToOneField(
                blank=True,
                help_text="Auto-created MedicationRecord for detailed tracking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_health_record",
                to="medication_management.medicationrecord",
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="vaccination_record",
            field=models.OneToOneField(
                blank=True,
                help_text="Auto-created VaccinationRecord for detailed tracking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_health_record",
                to="medication_management.vaccinationrecord",
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="vet_visit",
            field=models.OneToOneField(
                blank=True,
                help_text="Auto-created VetVisit for detailed tracking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_health_record",
                to="medication_management.vetvisit",
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("Vaccination", "Vaccination"),
                    ("Medication", "Medication/Treatment"),
                    ("Health Check", "Health Check"),
                    ("Vet Visit", "Veterinary Visit"),
                    ("Other", "Other"),
                ],
                default="Health Check",
                max_length=50,
            ),
        ),
    ]
