# Generated by Django 5.2.7 on 2025-10-26 14:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farms", "0003_farm_constituency_approved_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assignment_number",
                    models.CharField(
                        editable=False,
                        help_text="Format: ORD-YYYY-XXXXX-A01",
                        max_length=25,
                        unique=True,
                    ),
                ),
                (
                    "quantity_assigned",
                    models.PositiveIntegerField(
                        help_text="Quantity assigned to this farm",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "quantity_delivered",
                    models.PositiveIntegerField(
                        default=0, help_text="Quantity actually delivered"
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Agreed price per unit for this farm",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total value of this assignment (auto-calculated)",
                        max_digits=12,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Farm Response"),
                            ("accepted", "Accepted by Farm"),
                            ("rejected", "Rejected by Farm"),
                            ("preparing", "Farm Preparing Order"),
                            ("ready", "Ready for Delivery"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("verified", "Verified & Accepted"),
                            ("paid", "Payment Processed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expected_ready_date",
                    models.DateField(
                        blank=True,
                        help_text="When farm expects to have order ready",
                        null=True,
                    ),
                ),
                ("actual_ready_date", models.DateField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("payment_processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "average_weight_per_bird",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual average weight delivered",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "quality_passed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether delivery passed quality inspection",
                    ),
                ),
                ("quality_notes", models.TextField(blank=True)),
                (
                    "farm_notes",
                    models.TextField(
                        blank=True, help_text="Notes from farm about this assignment"
                    ),
                ),
                (
                    "officer_notes",
                    models.TextField(
                        blank=True, help_text="Notes from procurement officer"
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_assignments",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        editable=False,
                        help_text="Format: ORD-YYYY-XXXXX",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief description of order", max_length=200
                    ),
                ),
                ("description", models.TextField(help_text="Detailed requirements")),
                (
                    "production_type",
                    models.CharField(
                        choices=[
                            ("Broilers", "Broilers (Meat)"),
                            ("Layers", "Layers (Eggs)"),
                            ("Both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_needed",
                    models.PositiveIntegerField(
                        help_text="Total quantity needed (birds or crates of eggs)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("birds", "Birds (for broilers)"),
                            ("crates", "Crates of Eggs (30 eggs each)"),
                            ("kg", "Kilograms (dressed weight)"),
                        ],
                        default="birds",
                        max_length=20,
                    ),
                ),
                (
                    "quantity_assigned",
                    models.PositiveIntegerField(
                        default=0, help_text="Total quantity assigned to farms"
                    ),
                ),
                (
                    "quantity_delivered",
                    models.PositiveIntegerField(
                        default=0, help_text="Total quantity delivered so far"
                    ),
                ),
                (
                    "min_weight_per_bird_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum average weight per bird (for broilers)",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "quality_requirements",
                    models.TextField(
                        blank=True, help_text="Any specific quality/health requirements"
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per bird or crate (GHS)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total budget allocated (GHS)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_cost_actual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Actual total cost from all farm assignments",
                        max_digits=12,
                    ),
                ),
                (
                    "delivery_location",
                    models.TextField(help_text="Where products should be delivered"),
                ),
                ("delivery_location_gps", models.CharField(blank=True, max_length=100)),
                (
                    "delivery_deadline",
                    models.DateField(help_text="Farms must deliver by this date"),
                ),
                (
                    "delivery_instructions",
                    models.TextField(
                        blank=True, help_text="Special delivery instructions"
                    ),
                ),
                (
                    "auto_assign",
                    models.BooleanField(
                        default=True,
                        help_text="Auto-assign to closest farms with capacity",
                    ),
                ),
                (
                    "preferred_region",
                    models.CharField(
                        blank=True,
                        help_text="Prefer farms from this region",
                        max_length=100,
                    ),
                ),
                (
                    "max_farms",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum number of farms to assign",
                        validators=[django.core.validators.MaxValueValidator(50)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published - Accepting Bids"),
                            ("assigning", "Assigning to Farms"),
                            ("assigned", "Assigned to Farms"),
                            ("in_progress", "In Progress - Farms Preparing"),
                            ("partially_delivered", "Partially Delivered"),
                            ("fully_delivered", "Fully Delivered"),
                            ("completed", "Completed - Payments Processed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("normal", "Normal"),
                            ("high", "High Priority"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not visible to farmers)"
                    ),
                ),
                (
                    "assigned_procurement_officer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Officer managing this order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_procurement_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_procurement_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        editable=False,
                        help_text="Format: INV-YYYY-XXXXX",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("quantity_invoiced", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "quality_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Deduction for quality issues",
                        max_digits=10,
                    ),
                ),
                (
                    "mortality_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Deduction for dead on arrival",
                        max_digits=10,
                    ),
                ),
                (
                    "other_deductions",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("deduction_notes", models.TextField(blank=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Subtotal - All Deductions",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved for Payment"),
                            ("processing", "Payment Processing"),
                            ("paid", "Paid"),
                            ("failed", "Payment Failed"),
                            ("disputed", "Disputed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("mobile_money", "Mobile Money"),
                            ("paystack", "Paystack Subaccount"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Bank reference or transaction ID",
                        max_length=200,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "paid_to_account",
                    models.CharField(
                        blank=True,
                        help_text="Account number payment was made to",
                        max_length=100,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("invoice_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField(help_text="Payment due by this date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="procurement.orderassignment",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_invoices",
                        to="farms.farm",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="procurement.procurementorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.AddField(
            model_name="orderassignment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="procurement.procurementorder",
            ),
        ),
        migrations.CreateModel(
            name="DeliveryConfirmation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "delivery_number",
                    models.CharField(
                        editable=False,
                        help_text="Format: DEL-YYYY-XXXXX",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "quantity_delivered",
                    models.PositiveIntegerField(
                        help_text="Quantity in this delivery",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("delivery_date", models.DateField()),
                ("delivery_time", models.TimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("quality_passed", models.BooleanField(default=True)),
                (
                    "average_weight_per_bird",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "mortality_count",
                    models.PositiveIntegerField(default=0, help_text="Dead on arrival"),
                ),
                ("quality_issues", models.TextField(blank=True)),
                (
                    "quality_photos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="URLs to uploaded quality inspection photos",
                    ),
                ),
                ("delivery_note_number", models.CharField(blank=True, max_length=100)),
                ("vehicle_registration", models.CharField(blank=True, max_length=50)),
                ("driver_name", models.CharField(blank=True, max_length=200)),
                ("driver_phone", models.CharField(blank=True, max_length=20)),
                ("delivery_confirmed", models.BooleanField(default=False)),
                (
                    "confirmation_signature",
                    models.TextField(blank=True, help_text="Base64 encoded signature"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "received_by",
                    models.ForeignKey(
                        help_text="Officer who received delivery",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Officer who verified quality",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="procurement.orderassignment",
                    ),
                ),
            ],
            options={
                "ordering": ["-delivery_date", "-delivery_time"],
                "indexes": [
                    models.Index(
                        fields=["assignment"], name="procurement_assignm_cd940c_idx"
                    ),
                    models.Index(
                        fields=["delivery_date"], name="procurement_deliver_2472af_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="procurementorder",
            index=models.Index(
                fields=["status", "priority"], name="procurement_status_82cf2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procurementorder",
            index=models.Index(
                fields=["delivery_deadline"], name="procurement_deliver_ca2039_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procurementorder",
            index=models.Index(
                fields=["created_at"], name="procurement_created_b67f85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procurementinvoice",
            index=models.Index(
                fields=["payment_status"], name="procurement_payment_9b079a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procurementinvoice",
            index=models.Index(fields=["farm"], name="procurement_farm_id_b9eef9_idx"),
        ),
        migrations.AddIndex(
            model_name="procurementinvoice",
            index=models.Index(fields=["order"], name="procurement_order_i_bd81ee_idx"),
        ),
        migrations.AddIndex(
            model_name="procurementinvoice",
            index=models.Index(
                fields=["invoice_date"], name="procurement_invoice_fdaafa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderassignment",
            index=models.Index(
                fields=["order", "status"], name="procurement_order_i_52371a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderassignment",
            index=models.Index(
                fields=["farm", "status"], name="procurement_farm_id_0e723c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderassignment",
            index=models.Index(fields=["status"], name="procurement_status_a6a92a_idx"),
        ),
    ]
