# Generated by Django 5.2.7 on 2026-01-15 22:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("operation", models.CharField(max_length=100)),
                ("resource_type", models.CharField(max_length=100)),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("response_status", models.IntegerField(null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "procurement_idempotency_keys",
                "indexes": [
                    models.Index(fields=["key"], name="procurement_key_3d14c7_idx"),
                    models.Index(
                        fields=["expires_at"], name="procurement_expires_9ca3f1_idx"
                    ),
                    models.Index(
                        fields=["user_id", "operation"],
                        name="procurement_user_id_a7af80_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcurementAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operation", models.CharField(db_index=True, max_length=100)),
                ("resource_type", models.CharField(db_index=True, max_length=100)),
                ("resource_id", models.UUIDField(db_index=True)),
                ("user_role", models.CharField(blank=True, max_length=50, null=True)),
                ("previous_state", models.JSONField(default=dict)),
                ("new_state", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procurement_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "procurement_audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="procurement_resourc_8d08e4_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="procurement_user_id_af74a3_idx",
                    ),
                    models.Index(
                        fields=["operation", "timestamp"],
                        name="procurement_operati_d21ef7_idx",
                    ),
                ],
            },
        ),
    ]
