# Generated by Django 5.2.7 on 2026-01-16 09:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0016_distress_tracking_fields"),
        ("procurement", "0002_add_idempotency_and_audit_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderassignment",
            name="farmer_distress_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STABLE", "Stable"),
                    ("LOW", "Low"),
                    ("MODERATE", "Moderate"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                help_text="Farmer's distress level at time of assignment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderassignment",
            name="farmer_distress_score",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Farmer's distress score at time of assignment (0-100)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderassignment",
            name="selection_reason",
            field=models.CharField(
                choices=[
                    ("DISTRESS_PRIORITY", "Selected due to high distress score"),
                    ("CAPACITY_MATCH", "Selected based on capacity availability"),
                    ("LOCATION_MATCH", "Selected based on geographic proximity"),
                    ("OFFICER_SELECTED", "Manually selected by procurement officer"),
                    ("AUTO_ASSIGNED", "Auto-assigned by system"),
                ],
                default="CAPACITY_MATCH",
                help_text="Why this farm was selected for assignment",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="FarmDistressHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "distress_score",
                    models.PositiveIntegerField(
                        help_text="Distress score at time of recording (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "distress_level",
                    models.CharField(
                        choices=[
                            ("STABLE", "Stable - Healthy operations"),
                            ("LOW", "Low - Minor issues"),
                            ("MODERATE", "Moderate - Some difficulties"),
                            ("HIGH", "High - Significant struggle"),
                            ("CRITICAL", "Critical - Urgent intervention needed"),
                        ],
                        help_text="Distress level category",
                        max_length=20,
                    ),
                ),
                (
                    "factors",
                    models.JSONField(
                        default=dict,
                        help_text="\n        Detailed factor breakdown:\n        {\n            'inventory_stagnation': {'score': 85, 'detail': '...'},\n            'sales_performance': {'score': 70, 'detail': '...'},\n            'financial_stress': {'score': 60, 'detail': '...'},\n            'production_issues': {'score': 30, 'detail': '...'},\n            'market_access': {'score': 40, 'detail': '...'}\n        }\n        ",
                    ),
                ),
                (
                    "intervention_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PROCUREMENT", "Government Procurement Order"),
                            ("LOAN", "Government Loan/Subsidy"),
                            ("TRAINING", "Training/Extension Visit"),
                            ("EQUIPMENT", "Equipment Support"),
                            ("VETERINARY", "Veterinary Intervention"),
                            ("MARKETPLACE", "Marketplace Activation"),
                            ("OTHER", "Other Intervention"),
                        ],
                        help_text="Type of intervention if this record follows an intervention",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "intervention_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Value of intervention (e.g., procurement amount)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "intervention_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference ID of intervention (e.g., order number)",
                        max_length=50,
                    ),
                ),
                (
                    "intervention_notes",
                    models.TextField(
                        blank=True, help_text="Notes about the intervention"
                    ),
                ),
                (
                    "calculated_by",
                    models.CharField(
                        default="system",
                        help_text="Who triggered: 'system' (daily task), 'officer' (on-demand), 'api'",
                        max_length=50,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distress_history",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_farm_distress_history",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["farm", "-recorded_at"],
                        name="procurement_farm_id_51728d_idx",
                    ),
                    models.Index(
                        fields=["distress_level", "-recorded_at"],
                        name="procurement_distres_8700d6_idx",
                    ),
                    models.Index(
                        fields=["intervention_type"],
                        name="procurement_interve_99beda_idx",
                    ),
                ],
            },
        ),
    ]
